### ISSUE TITLE
issue migrating to slick 2.0

### ISSUE THREAD

**Issue by ErunamoJAZZ** [slick/slick#1016]
Hello.

I'm try migrate to Slick 2.0, and now all compile, but, i have a exception with a query: `[SlickException: JdbcProfile has no TypeInfo for type {s2: String/VARCHAR(254)}]`.

i read this: https://github.com/slick/slick/issues/794 but i dont understand were are the error for me. I'm using pg-slick, all strings are defined like `Option[String]`, and the query is a simple filter... i searching for others imports etc, but nothing.

columns are defined like `def description = column[String]("DESCRIPTION", O.Nullable)`,etc...

This is the complete error:
```
play.api.Application$$anon$1: Execution exception[[SlickException: JdbcProfile has no TypeInfo for type {s2: String/VARCHAR(254)}]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.4]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:166) [play_2.10.jar:2.2.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:163) [play_2.10.jar:2.2.4]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
Caused by: scala.slick.SlickException: JdbcProfile has no TypeInfo for type {s2: String/VARCHAR(254)}
	at scala.slick.driver.JdbcTypesComponent$class.typeInfoFor(JdbcTypesComponent.scala:127) ~[slick_2.10-2.0.2.jar:2.0.2]
	at model.MyPostgresDriver$.typeInfoFor(MyPostgresDriver.scala:33) ~[classes/:na]
	at scala.slick.jdbc.JdbcMappingCompilerComponent$MappingCompiler$class.createColumnConverter(JdbcMappingCompilerComponent.scala:18) ~[slick_2.10-2.0.2.jar:0.6.1]
	at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.createColumnConverter(JdbcMappingCompilerComponent.scala:36) ~[slick_2.10-2.0.2.jar:0.6.1]
	at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$class.compileMapping(RelationalProfile.scala:215) ~[slick_2.10-2.0.2.jar:2.0.2]
	at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.compileMapping(JdbcMappingCompilerComponent.scala:36) ~[slick_2.10-2.0.2.jar:0.6.1]
```

I appreciate any clue. Thx.

**Comment by szeiger** [comment]
This looks like a bug in the column flattening algorithm in the query compiler. Does it still fail in 3.0.0-M1? Those parts of the compiler have changed a lot when I added support for nested columns and I remember fixing a bug with these symptoms. Please reopen this ticket with a reproduction if it's still relevant. There's not much I can do without a snippet.
