### ISSUE TITLE
Can slick support MS Access Database by UCanAccess ?

### ISSUE THREAD

**Issue by djx314** [slick/slick#1023]
I use slick in my work. Usually I must work with MS Access in the old project In large part because I am a Chinese. I want to do some things with MS Access by using slick. But I get that AccessDriver is deprecated and will remove. Is there any way to support MS Access ?

**Comment by szeiger** [comment]
Interesting, I didn't know about UCanAccess. It wasn't around yet when I last checked for alternative drivers. If I understand it correctly, it is a database engine that uses Access database files directly, not an interface to the official Access engine (like our current ODBC-based approach), so I'm not surprised that Slick's AccessDriver doesn't work.

**Comment by djx314** [comment]
I read the UCanAccess's documentation again. I knew that the UcanAccess is using Hsqldb to transform the sql to some basic operation that Jackcess can do(It uses java to handle the access database's file like h2's embedded mode). It's not a pure sql interface.  I think what it can do is limited, like it can't resolve the column alias in the demo I have showed. So it disagreed with silck.

**Comment by cvogt** [comment]
Try using the hsqldb slick driver with the uaccessdb jdbc driver. Does that work better?

**Comment by djx314** [comment]
I changed the
```scala
import scala.slick.driver.AccessDriver.simple._
```
to
```scala
import scala.slick.driver.HsqldbDriver.simple._
```
and it reported almost same error:
```
[error] (run-main-3) net.ucanaccess.jdbc.UcanaccessSQLException: unknown token:
x2.
net.ucanaccess.jdbc.UcanaccessSQLException: unknown token: x2.
        at net.ucanaccess.jdbc.UcanaccessConnection.prepareStatement(UcanaccessC
onnection.java:533)
        at scala.slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBa
ckend.scala:152)
        at scala.slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend
.scala:389)
...
```
and the sql is
```
[DEBUG] Preparing statement: select x2."ArticleID", x2."Title" from "PE_Article" x2
```
I think ucansuccess don't support table alias.
Because
```scala
val data = sql"select ArticleId, ChannelId, ClassId, Title from PE_Article".as[(Long, Long, Long, String)].list
data.foreach(s => println(s))
```
works well but
```scala
pEArticles.list
```
reported the error(see the code above).

**Comment by cvogt** [comment]
If it doesn't support aliases, you are likely out of luck. Sorry.

**Comment by szeiger** [comment]
Well, not having an aliasing syntax shouldn't be that hard to work around. I can't see a simple way to add it directly to the code generator but an extra compiler phase could do it: Recurse over the tree, collecting all Symbols that are introduced in FROM clauses (of Comprehension nodes), then do a recursive tree transformation that (1) drops the Symbols from the FROM clauses and (2) removes them from all Paths in the tree. The whole thing shouldn't take more than a few lines of code.

However, this will rule out any kind of join which makes me doubt that UCanAccess really has such a limitation. My guess from the error message would be that the actual problem is a bug in its SQL parser that makes it choke on qualified identifiers which are partially quoted. Or maybe it doesn't support quoted identifiers at all. Both issues are easy to work around by overriding the SymbolNamer in the QueryBuilder.

**Comment by djx314** [comment]
I remove all the double quotation of the column names. it looks like that ucanaccess can parse the sql. But I don't have the access 2003 at home, Let me have a try tomorrow.
Here's the code,
'''
http://git.heshan.gov.cn:8080/gitbucket/djx314/slickAccess
'''
But it's in China, I am not sure you can have a look at it. If my test successes, I will push it  to github.

**Comment by cvogt** [comment]
@szeiger removing aliasing where possible would also help debugging queries and for cases like this one https://github.com/slick/slick/issues/1045   I also bet that it would make a lot of people happy who look at the generated queries the first time. If it is easy to implement it is probably worth it!

**Comment by djx314** [comment]
Oh! I found that it's not the alias's problem. Just the double quotation!!!
I created a *.mdb file and created the tables by MS-Access 2003(not use slick's ddl). Then I created a bit complex query by slick. Of course, it reported an exception. Then I found the sql in the log, and replace all the " to ` , now it works! Because ucanaccess will parse the " as the start of string.
Here's the code:
```
https://github.com/djx314/slickAccess/blob/master/app/controllers/SlickAccess.scala
```
Here's the sql
```sql
select x2.x3, x2.x4, x2.x5, x2.x6 from (select x7.`id` as x3, x7.`auth_name` as x4, x7.`auth_nick_name` as x5, x7.`auth_describe` as x6 from `p_account` x8, `p_entry_account_group_link` x9, `p_entry_group` x10, `p_entry_group_auth_link` x11, `p_entry_authority` x7 where ((((x8.`a_name` = cast('jackie' as varchar(16777216))) and (x9.`ac_id` = x8.`id`)) and (x10.`id` = x9.`gr_id`)) and (x11.`gr_id` = x10.`id`)) and (x7.`id` = x11.`au_id`) union select x12.`id` as x3, x12.`auth_name` as x4, x12.`auth_nick_name` as x5, x12.`auth_describe` as x6 from `p_account` x13, `p_entry_account_authority_link` x14, `p_entry_authority` x12 where ((x13.`a_name` = cast('jackie' as varchar(16777216))) and (x14.`ac_id` = x13.`id`)) and (x12.`id` = x14.`au_id`)) x2 order by x2.x3 desc
```
So I think it's not hard to support ucanaccess in slick. It can support large old projects. For example, my company has many asp projects that uses MS-Access, and I want to do some rest interface by using the database.  But odbc will be removed in java8, so I needed a library to support it. And I think many Chinese has the same problem.

**Comment by cvogt** [comment]
You can probably fix that by creating your own hsqldb subtype and override def quoteIdentifier like this: https://github.com/slick/slick/blob/58fab9017a56c21b49811ea0d900c910b40cd50d/src/main/scala/scala/slick/driver/MySQLDriver.scala#L82

**Comment by djx314** [comment]
Great! Just
```scala
import scala.slick.driver.HsqldbDriver

trait UCanAccessDriver extends HsqldbDriver {
  override def quoteIdentifier(id: String) = '`' + id + '`'
}

object UCanAccessDriver extends UCanAccessDriver
```
And it works well! Thanks very much.

**Comment by cvogt** [comment]
Awesome. We should consider keeping Access support based on this @szeiger  /cc @bhudgeons

**Comment by szeiger** [comment]
So far the options for Access support were:
- Drop it when we switch to Scala 2.12 / Java 8
- Resurrect it as a commercial driver in slick-extensions, based on one of the commercial Access driver solutions for Java, if there's demand for it

UCanAccess opens up a new path. Someone would have to try a proper build integration, i.e. create a new AccessDriver (either based on the old one or HsqldbDriver?) and write the TestKit scaffolding to run all tests on Access (which doesn't happen on a regular basis at the moment).

**Comment by nafg** [comment]
FWIW dealiasing where possible would be a nice feature for when more
readable SQL is of interest.

**Comment by cvogt** [comment]
Yeah. I think @szeiger plans to look at this for 3.1

**Comment by szeiger** [comment]
Avoiding aliasing is not a priority for the rewrite of the SQL phases of the compiler, but it could be a side effect (and avoiding unnecessary subqueries will already remove a lot of aliasing because it is already not generated at the top level)

**Comment by nafg** [comment]
Great to hear!

**Comment by jilen** [comment]
Cannot agree more with @nafg ,  current the generated sql is too complex!! We won't  wan to see sqls like  this ```sql select x2.`id`, x2.`desc`, x2.`staff_id`, x2.`prj_id`, x2.`branch_name`, x2.`status`, x2.`score`, x2.`request_type`, x2.`schedule_date`, x2.`gmt_create`, x2.`gmt_modified` from (select x3.`prj_id` as `prj_id`, x3.`gmt_modified` as `gmt_modified`, x3.`request_type` as `request_type`, x3.`staff_id` as `staff_id`, x3.`score` as `score`, x3.`status` as `status`, x3.`desc` as `desc`, x3.`gmt_create` as `gmt_create`, x3.`branch_name` as `branch_name`, x3.`id` as `id`, x3.`schedule_date` as `schedule_date` from `ops_request` x3 order by x3.`gmt_create` desc limit 10) x2 ```

**Comment by Skamander** [comment]
> UCanAccess opens up a new path. Someone would have to try a proper build integration, i.e. create a new AccessDriver (either based on the old one or HsqldbDriver?) and write the TestKit scaffolding to run all tests on Access (which doesn't happen on a regular basis at the moment).

Hi,

since UCanAccess uses LGPL 2.1: is the LGPL compatible with Slicks license? Slick seems to use a different license as Play, whose license is not  LGPL compatible -> https://github.com/playframework/playframework/issues/4197 and https://github.com/playframework/playframework/pull/4118 so it's probably not a problem, but I'm a license noob and I also think about play-slick. Play-Slick uses the same license as play, could this be a problem?

**Comment by cvogt** [comment]
@Skamander licenses look compatible. Slick uses BSD 2-clause https://groups.google.com/forum/#!topic/cr-48-test-pilots/0-Um2ED-cEA

**Comment by Skamander** [comment]
Thanks for the clarification @cvogt

**Comment by szeiger** [comment]
The licenses are compatible in the sense that you can create an app which depends on both. We cannot allow any use of LGPL licensed code in Slick or as a dependency for the same reason that Play can't. However, none of our drivers depend on third-party JDBC drivers, they only use JDBC itself in a compatible way. If we wanted to depend directly on other drivers (like in slick-pg) I'd have to run that by our legal team first.

On April 30, 2015 9:57:21 PM GMT+02:00, Skamander <notifications@github.com> wrote:
>> UCanAccess opens up a new path. Someone would have to try a proper
>build integration, i.e. create a new AccessDriver (either based on the
>old one or HsqldbDriver?) and write the TestKit scaffolding to run all
>tests on Access (which doesn't happen on a regular basis at the
>moment).
>
>Hi,
>
>since UCanAccess uses LGPL 2.1: is the LGPL compatible with Slicks
>license? Slick seems to use a different license as Play, whose license
>is not  LGPL compatible ->
>https://github.com/playframework/playframework/issues/4197 and
>https://github.com/playframework/playframework/pull/4118 so it's
>probably not a problem, but I'm a license noob and I also think about
>play-slick. Play-Slick uses the same license as play, could this be a
>problem?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/slick/slick/issues/1023#issuecomment-97949963

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by jamadei** [comment]
Anyway, next version ucanaccess(3.0.0) version will likely be under Apache 2.0.
I chose lgpl just for compatibility with the underlying jackcess library, but they relicensed to Apache the latest jackcess version(2.1.0). 
I have just to verify the Apache2.0 compatibility with the hsqldb ad-hoc licence, yet I'm pretty sure it's compatible with.
If I'm right, I have no more reasons to continue with the LGPL 2.1. Cheers Marco

**Comment by lprc** [comment]
Can someone commit a working code snippet for accessing a MS Access DB (2010) using UcanAccess and Slick? I'm using uca 3.0.4, slick 3.1.1 and scala 2.11.8 but I my code just throws the same exception @djx314 also had.
Here's what I've got so far:

```
import net.ucanaccess.jdbc.UcanaccessDriver

import slick.driver.HsqldbDriver
import slick.lifted.Tag
import slick.driver.HsqldbDriver.api._

import scala.concurrent.Await
import scala.concurrent.duration.Duration

object MainTest {

  trait UCanAccessDriver extends HsqldbDriver {
    override def quoteIdentifier(id: String) = '`' + id + '`'
  }

  object ucad extends UCanAccessDriver

  class Tools(tag: Tag) extends ucad.api.Table[(Int, String, String, String)](tag, "tools") {
    def Tool_ID = column[Int]("id", O.PrimaryKey, O.AutoInc)
    def Name = column[String]("name")
    def Sprache = column[String]("sprache")
    def Entwickler = column[String]("entwickler")

    def * = (Tool_ID, Name, Sprache, Entwickler)
  }

  def main(args: Array[String]) = {

    // slick test
    println("Connecting via slick...")
    val db = ucad.api.Database.forURL(url = UcanaccessDriver.URL_PREFIX + "GNN-Tools.mdb;user=sa",
                             driver = "net.ucanaccess.jdbc.UcanaccessDriver")

    val pTools = ucad.api.TableQuery[Tools]
    println("statement: " + pTools.result.statements)

    Await.result(db.run(pTools.result), Duration.Inf).foreach { // Exception here
      println
    }
  }
}
```

Stack Trace: 
```
Connecting via slick...
statement: List(select "id", "name", "sprache", "entwickler" from "tools")
[error] (run-main) net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::3.0.4 unexpected token: tools
net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::3.0.4 unexpected token: tools
	at net.ucanaccess.jdbc.UcanaccessConnection.prepareStatement(UcanaccessConnection.java:528)
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
	at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218)
	at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: unexpected token: tools
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
...
```

**Comment by djx314** [comment]
@lprc 
not to use
```scala
import slick.driver.HsqldbDriver.api._
```

use
```scala
import scala.slick.driver.HsqldbDriver

trait UCanAccessDriver extends HsqldbDriver {
  override def quoteIdentifier(id: String) = '`' + id + '`'
}

object UCanAccessDriver extends UCanAccessDriver

import UCanAccessDriver.api._
//do something
```

**Comment by lprc** [comment]
Yeah that works, thank you so much! :)
