### ISSUE TITLE
crash when inserting with AutoInc return using sqldroid

### ISSUE THREAD

**Issue by tek** [slick/slick#1031]
[test case repo](https://github.com/tek/slick-android-testcase)

I'm using the sqldroid driver on android, which works fine, except when inserting data via the `returning` function like in the test case:

```scala
package org.dbtest

import scala.util.Try

import android.os.Bundle
import android.app.Activity

import scala.slick.driver.SQLiteDriver.simple._

class MainActivity extends Activity {
  override def onCreate(state: Bundle) {
    super.onCreate(state)
    test
  }

  def test {

    class ATable(tag: Tag) extends Table[(Int, String)](tag, "atable") {
      def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
      def name = column[String]("name")
      def * = (id, name)
    }

    val dbPath = new java.io.File(getFilesDir, "dbtest.db")

    val db = Database.forURL(
      url = s"jdbc:sqlite:${dbPath}",
      driver = "org.sqldroid.SQLDroidDriver")

    val query = TableQuery[ATable]

    db withSession { implicit session ⇒
      Try(query.ddl.drop)
      query.ddl.create
      query insert (9, "some")
      query returning query.map(_.id) insert ((5, "some"))
    }
  }
}
```
The first insert works, but the second one results in the following exception:

```
java.lang.NullPointerException
at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:198)
at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:389)
at scala.slick.driver.JdbcInsertInvokerComponent$ReturningInsertInvoker.preparedInsert(JdbcInsertInvokerComponent.scala:301)
at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.internalInsert(JdbcInsertInvokerComponent.scala:180)
at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.insert(JdbcInsertInvokerComponent.scala:175)
at org.dbtest.MainActivity$$anonfun$test$1.apply(main_activity.scala:36)
at org.dbtest.MainActivity$$anonfun$test$1.apply(main_activity.scala:32)
at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
at org.dbtest.MainActivity.test(main_activity.scala:32)
at org.dbtest.MainActivity.onCreate(main_activity.scala:13)
at android.app.Activity.performCreate(Activity.java:5426)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
```

Does this mean that the sqldroid driver doesn't support returning AutoInc values after insert, or is there anything I can do?
The test case should work when launching `sbt android:run`.

**Comment by szeiger** [comment]
It's a SQLDroid limitation: https://github.com/SQLDroid/SQLDroid/blob/master/src/main/java/org/sqldroid/SQLDroidConnection.java#L325-335

You should open an improvement request there.
