### ISSUE TITLE
mysql,data type text,but with max size exceed

### ISSUE THREAD

**Issue by hepin1989** [slick/slick#1070]
/** Database column notify_data DBType(TEXT), Length(65535,true), Default(None) */
```
2015-02-10 19:58:13,524 ERROR a.a.OneForOneStrategy [xxjh-akka.actor.default-dispatcher-4] Column length too big for column 'notify_data' (max = 21845); use BLOB or TEXT instead
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
        at akka.actor.ActorCell.create(ActorCell.scala:596)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column length too big for column 'notify_data' (max = 21845); use BLOB or TEXT instead
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199)
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
        at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.execute(PreparedStatementJavassistProxy.java)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(JdbcInvokerComponent.scala:50)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(JdbcInvokerComponent.scala:50)
        at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:191)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:389)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1.apply(JdbcInvokerComponent.scala:50)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1.apply(JdbcInvokerComponent.scala:49)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.Iterator$JoinIterator.foreach(Iterator.scala:191)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply$mcV$sp(JdbcInvokerComponent.scala:49)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply(JdbcInvokerComponent.scala:49)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply(JdbcInvokerComponent.scala:49)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
        at scala.slick.driver.JdbcInvokerComponent$DDLInvoker.create(JdbcInvokerComponent.scala:48)
        at qgame.engine.pay.module.order.db.DBHelper$$anonfun$checkExistOrCreateTable$1.apply(DBHelper.scala:24)
        at qgame.engine.pay.module.order.db.DBHelper$$anonfun$checkExistOrCreateTable$1.apply(DBHelper.scala:23)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at qgame.engine.pay.module.order.db.DBHelper$.checkExistOrCreateTable(DBHelper.scala:22)
        at qgame.engine.pay.module.order.OrderModuleActor.preStart(OrderModuleActor.scala:60)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at qgame.engine.pay.module.order.OrderModuleActor.aroundPreStart(OrderModuleActor.scala:16)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
```
the generated code is 
```
    /** Database column notify_data DBType(TEXT), Length(65535,true), Default(None) */
    val notifyData: Column[Option[String]] = column[Option[String]]("notify_data", O.Length(10240, varying = true), O.Default(None))
```

the ddl is 
```
DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `channel_id` varchar(255) NOT NULL,
  `role_id` bigint(11) NOT NULL,
  `goods_id` int(11) NOT NULL,
  `order_price` double(10,2) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `channel_order_id` varchar(255) DEFAULT NULL,
  `notify_time` timestamp NULL DEFAULT NULL,
  `success` tinyint(1) unsigned zerofill DEFAULT NULL,
  `real_price` double(10,2) unsigned zerofill DEFAULT NULL,
  `uid` varchar(255) DEFAULT NULL,
  `finish_time` timestamp NULL DEFAULT NULL,
  `info` varchar(255) DEFAULT NULL,
  `notify_data` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by cvogt** [comment]
Which version are you using?

**Comment by hepin1989** [comment]
last version of slick and the mysql driver.
I could make work around that making the size little than 21845. :P.

In fact the notify_data is type ```text``` or I could change the type to ```varchar``` and specified a length.

**Comment by cvogt** [comment]
what version exactly? Milestone or stable?

**Comment by hepin1989** [comment]
slick 2.1.0
mysql driver 5.1.34

**Comment by szeiger** [comment]
This was fixed in #1065

**Comment by cvogt** [comment]
meaning it arrives with slick 3.0 in the very near future

**Comment by hepin1989** [comment]
thanks

**Comment by hepin1989** [comment]
@szeiger  will back port to 2.1.1?Even I am using 3.0,but old project is using the slick 2.1.
thanks

**Comment by cvogt** [comment]
@hepin1989 I don't think there are backports to 2.x versions planned. I suppose you could always hire Typesafe to do it.

**Comment by hepin1989** [comment]
@cvogt thanks :)
