### ISSUE TITLE
Embedded Derby, 42x04 error code, "outside the scope of the join specification"

### ISSUE THREAD

**Issue by oogifu** [slick/slick#1076]
Hello,

I have a simple table:

create table tbl_clients (
  uid varchar(64) not null,
  name varchar(64),
  primary key(uid)
);

and I use LiquidBase to update the schema of an in-memory Derby. All is fine.

I am trying to do a simple select:

 val db = Database.forURL("jdbc:derby:memory:MPTESTDB3;create=true",driver="org.apache.derby.jdbc.EmbeddedDriver")
type TBL_CLIENT = (String, String)
  class TBL_CLIENTS(tag: Tag) extends Table[TBL_CLIENT](tag, "TBL_CLIENTS") {
    def uid = column[String]("uid", O.PrimaryKey)
    def name = column[String]("name")
    def * = (uid, name)
  }
  lazy val allClients = TableQuery[TBL_CLIENTS]

val allClientsQuery = allClients.map(client => (client.name))
  val allClientsResult = db.withSession {implicit session =>
    allClientsQuery.run
  }

This fails with the following error:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at scb.np.investigations.EmbDerbyWithSlick.main(EmbDerbyWithSlick.scala)
Caused by: java.sql.SQLSyntaxErrorException: Column 'X2.name' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'X2.name' is not a column in the target table.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:152)
	at scala.slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:389)
	at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:32)
	at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.driver.JdbcExecutorComponent$QueryExecutorDef.run(JdbcExecutorComponent.scala:29)
	at scb.np.investigations.EmbDerbyWithSlick$$anonfun$7.apply(EmbDerbyWithSlick.scala:59)
	at scb.np.investigations.EmbDerbyWithSlick$$anonfun$7.apply(EmbDerbyWithSlick.scala:58)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
	at scb.np.investigations.EmbDerbyWithSlick$.<init>(EmbDerbyWithSlick.scala:58)
	at scb.np.investigations.EmbDerbyWithSlick$.<clinit>(EmbDerbyWithSlick.scala)
	... 1 more

I have tried Slick 2.1.0, 3.0.0 M1, running Scala 2.11.5 with Java 7.

Any help would be appreciated.

Thanks

**Comment by cvogt** [comment]
your table is called tbl_clients but your Slick Table class says TBL_CLIENT  (see the missing s).

Please put readable code in a ticket next time

**Comment by oogifu** [comment]
Hi CVOGT,

Will do. This is not the issue. May be it is related to Derby, but when I use the lower case version, I have the exception: Caused by: java.sql.SQLSyntaxErrorException: Table/View 'tbl_clients' does not exist.

When I use the upper case version, it works.

You just "fixed" my issue. It is actually related that even the column names should be in upper case.
Weird Derby behaviour.

Thanks

**Comment by cvogt** [comment]
Slick quotes names. Unquoted names (which you probably used during creation) will be treated as upper case in sql by default, iirc, which means in slick you will have to use upper case.
