### ISSUE TITLE
H2DB : column[UUID]("NAME") fails with Deserialization failed unless setting O.DBType("UUID")

### ISSUE THREAD

**Issue by petervandenabeele** [slick/slick#1099]
Using H2DB database and driver.

This works:

```
class FactsInDB(tag: Tag) extends Table[(String, String, String, UUID, String, String, String)](tag, "FACTS") {
  // This is the primary key column:
  def timeStamp: Column[String] = column[String]("FACT_TIMESTAMP", O.PrimaryKey)
  def uuid: Column[String] = column[String]("FACT_UUID")
  def context: Column[String] = column[String]("FACT_CONTEXT")
  def subject: Column[UUID] = column[UUID]("FACT_SUBJECT", O.DBType("UUID")) // explicit
  def predicate: Column[String] = column[String]("FACT_PREDICATE")
  def objectType: Column[String] = column[String]("FACT_OBJECT_TYPE")
  def objectValue: Column[String] = column[String]("FACT_OBJECT_VALUE")

  def * : ProvenShape[(String, String, String, UUID, String, String, String)] = {
    (timeStamp, uuid, context, subject, predicate, objectType, objectValue)
  }
}
```

But this fails:
```
class FactsInDB(tag: Tag) extends Table[(String, String, String, UUID, String, String, String)](tag, "FACTS") {
  // This is the primary key column:
  def timeStamp: Column[String] = column[String]("FACT_TIMESTAMP", O.PrimaryKey)
  def uuid: Column[String] = column[String]("FACT_UUID")
  def context: Column[String] = column[String]("FACT_CONTEXT")
  def subject: Column[UUID] = column[UUID]("FACT_SUBJECT") // implicit
  def predicate: Column[String] = column[String]("FACT_PREDICATE")
  def objectType: Column[String] = column[String]("FACT_OBJECT_TYPE")
  def objectValue: Column[String] = column[String]("FACT_OBJECT_VALUE")

  def * : ProvenShape[(String, String, String, UUID, String, String, String)] = {
    (timeStamp, uuid, context, subject, predicate, objectType, objectValue)
  }
}
```
with the cryptic:

```
Deserialization failed, cause: "java.io.StreamCorruptedException: invalid stream header: 91502BE7" [90027-186]
org.h2.jdbc.JdbcSQLException: Deserialization failed, cause: "java.io.StreamCorruptedException: invalid stream header: 91502BE7" [90027-186]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:407)
	at org.h2.jdbc.JdbcConnection.convertToDefaultObject(JdbcConnection.java:1931)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:502)
	at scala.slick.jdbc.StatementInvoker$$anon$1$$anonfun$extractValue$1.apply(StatementInvoker.scala:60)
	at scala.slick.jdbc.StatementInvoker$$anon$1$$anonfun$extractValue$1.apply(StatementInvoker.scala:60)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at scala.slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:60)
	at scala.slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
	at scala.slick.util.ReadAheadIterator$class.scala$slick$util$ReadAheadIterator$$update(ReadAheadIterator.scala:34)
	at scala.slick.util.ReadAheadIterator$class.hasNext(ReadAheadIterator.scala:40)
	at scala.slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:65)
	at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.build(Invoker.scala:47)
	at scala.slick.jdbc.StatementInvoker.build(StatementInvoker.scala:16)
	at scala.slick.jdbc.Invoker$class.list(Invoker.scala:39)
	at scala.slick.jdbc.StatementInvoker.list(StatementInvoker.scala:16)
	at slick.H2DB$$anonfun$insert_fact$1.apply(H2DB.scala:51)
	at slick.H2DB$$anonfun$insert_fact$1.apply(H2DB.scala:35)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
	at slick.H2DB$.insert_fact(H2DB.scala:35)
	at slick.H2DBSuite$$anonfun$2$$anon$2.<init>(H2DBSuite.scala:34)
	at slick.H2DBSuite$$anonfun$2.apply$mcV$sp(H2DBSuite.scala:33)
	at slick.H2DBSuite$$anonfun$2.apply(H2DBSuite.scala:33)
	at slick.H2DBSuite$$anonfun$2.apply(H2DBSuite.scala:33)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:137)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.StreamCorruptedException: invalid stream header: 91502BE7
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:403)
	... 80 more
```

Is this the expected behavior (then the error message could be made more clear for newcomers)
Or maybe it is not the expected behavior ?

**Comment by szeiger** [comment]
Fixed in https://github.com/slick/slick/commit/d63a0183bdb2748d83f88ccf2d81670ff89914a7
