### ISSUE TITLE
PlainSQL: `sqlu` generates wrong DDL sql?

### ISSUE THREAD

**Issue by tminglei** [slick/slick#1124]
I wrote codes in my tests as below:
```scala
Await.result(db.run(
  DBIO.seq(
    sqlu"""create table JsonTest0(
          id int8 not null primary key,
          json ${MyPlainPostgresDriver.pgjson} not null)
      """,
    ///
```
But I got an exception as below:
```
[info] - Json Plain SQL support *** FAILED ***
[info]   org.postgresql.util.PSQLException: ERROR: syntax error at or near "$1"
[info]   Position: 88
[info]   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
[info]   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
[info]   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
[info]   at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
[info]   at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
[info]   at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:413)
[info]   at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
[info]   at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
[info]   at slick.jdbc.Invoker$class.iterator(Invoker.scala:15)
[info]   at slick.jdbc.StatementInvoker.iterator(StatementInvoker.scala:16)
[info]   ...
```

I'm sure it's related to `${MyPlainPostgresDriver.pgjson}`, because when I replaced it with `json` or `jsonb`, it's back to work.

Pls help take a look.
Thanks!

**Comment by tminglei** [comment]
Did I used wrong way? Is `sqlu` only used to generate parametered sql?

**Comment by szeiger** [comment]
What are you trying to do? Abstract over different JSON types? This is part of the SQL syntax, so it has to be part of the literal string. You can't use bind variables here. Try `json #${MyPlainPostgresDriver.pgjson`

**Comment by tminglei** [comment]
Yeah, I try to abstract over different json types, and `#${MyPlainPostgresDriver.pgjson}` works.
_Thanks so much!_ :+1:
