### ISSUE TITLE
Suspected native thread leakage in Slick 3.0.0-M3

### ISSUE THREAD

**Issue by adatoo** [slick/slick#1132]
Environment:
* Play Framework 2.3.8
* Postgres JDBC Driver 9.4-1201-jdbc41
* JDK 7 / 8 

Having followed (this)[http://blog.knoldus.com/2015/03/03/play-with-reactive-slick-a-simple-crud-application-in-play-framework-using-slick-3-0/] article to integrate Slick into Play, I am finding that running my full test suite results in a `java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: unable to create new native thread` error. Testing a subset of the tests works fine.

Stacktrace:

```
Exception encountered when attempting to run a suite with class name: unit.services.admin.DeviceTypeServiceSpec *** ABORTED ***
[info]   java.lang.OutOfMemoryError: unable to create new native thread
[info]   at java.lang.Thread.start0(Native Method)
[info]   at java.lang.Thread.start(Thread.java:714)
[info]   at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:949)
[info]   at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
[info]   at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
[info]   at slick.backend.DatabaseComponent$DatabaseDef$class.runSynchronousDatabaseAction(DatabaseComponent.scala:224)
[info]   at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:38)
[info]   at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:201)
[info]   at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
[info]   at slick.backend.DatabaseComponent$DatabaseDef$class.runInternal(DatabaseComponent.scala:75)
[info]   ...
```

**Comment by szeiger** [comment]
See https://github.com/knoldus/play-reactive-slick/issues/1
