### ISSUE TITLE
How to return the result from DBIOAction

### ISSUE THREAD

**Issue by DieterLi** [slick/slick#1143]
In doc, all the results end with println, which don't happen in real world cases. I want to know which is the best way to get the results of CRUD in these cases. Even with Future's onSuccess, onFailure, onComplete, I have to declare a mutable variable to catch the result, but what if exception happen?

And so, I try to use Future's map, flatmap, recover and recoverWith, which achieve the pure reactive purpose, but without blocking, it often goes with SQLException: Interrupted during connection acquisition.
Some of my codes are the following:
```scala
    def updateSeveral(): Future[Int] = {
        val now = new Timestamp(DateTime.now().getMillis)
        val db = Database.forConfig("mydb")
        try {
          val f: Future[Int] = db.run(
            Acuser.filter(_.id <= 28733292).map(_.firstname).update(Some("Lee"))
          )

          f map {
            r =>
              r
          } recoverWith {
            case ex: Exception =>
              Future.failed[Int](ex)
          }
        } finally db.close()
      }
```

It's called from a page of Playframework, when I keeps reload the page, the above exception occurs often. But when I change the pattern to Await blocking, everything goes well.

I didn't figure out why. Please help and thanks in advance.

**Comment by DieterLi** [comment]
Detailed exceptions are the following:
```
play.api.Application$$anon$1: Execution exception[[SQLException: Interrupted during connection acquisition]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11.jar:2.3.8]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
Caused by: java.sql.SQLException: Interrupted during connection acquisition
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:220) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93) ~[HikariCP-2.3.7.jar:na]
	at slick.jdbc.HikariCPJdbcDataSource.createConnection(JdbcDataSource.scala:131) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394) ~[slick_2.11-3.0.0.jar:na]
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedLongSynchronizer.tryAcquireSharedNanos(AbstractQueuedLongSynchronizer.java:1104) ~[na:1.8.0_45]
	at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:134) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:201) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93) ~[HikariCP-2.3.7.jar:na]
```

**Comment by julienrf** [comment]
You are closing the database too early. Remember that `db.run` is asynchronous.

**Comment by DieterLi** [comment]
To avoid, it seems that Await has to used, which is not recommended by the doc. And if onComplete, onSuccess, onFailure, or even map, flatMap, they can make whole thing asynchronous. But where should I put db.close, which is following finally of try block. 

Here is where I'm confusing. What's best pattern for this?

**Comment by szeiger** [comment]
The `Database` is a global resource. Create it when you start the app and shut it down with the app. Do not create and close a db for individual statements.

**Comment by DieterLi** [comment]
@szeiger Thank you very much. You've made a very clear point here. It works very well, and all app works asynchronously. Great job!
