### ISSUE TITLE
Update is not working Slick 3.0 with Mongodb (below 2.6)

### ISSUE THREAD

**Issue by pganta** [slick/slick#1168]
For some of our projects we are using Slick 3.0  with Mongo Db. We notice update failures after upgrading to Slick 3.0, this works well with Mongodb 2.6 and above but not below 2.6. Below is the error we are getting while update.
 
[AsyncExecutor.default-8]
                                [s.j.J.benchmark] - Execution of prepared statement took 1ms
reactivemongo.core.commands.LastError: DatabaseException['Mod on _id not allowed' (code = 10148)]
        at reactivemongo.core.commands.LastError$.apply(commands.scala:323)
        at reactivemongo.core.commands.LastError$.apply(commands.scala:321)
        at reactivemongo.core.commands.BSONCommandResultMaker$class.apply(commands.scala:78)
        at reactivemongo.core.commands.LastError$.apply(commands.scala:321)
        at reactivemongo.core.actors.MongoDBSystem$$anonfun$receive$1.applyOrElse(actors.scala:452)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at reactivemongo.core.actors.MongoDBSystem.aroundReceive(actors.scala:96)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by cvogt** [comment]
slick currently does not have mongodb support. your cause must be something else. maybe reactive mongo?
