### ISSUE TITLE
UnassignedType when combining Union, Mapped Table and Option

### ISSUE THREAD

**Issue by markvandertol** [slick/slick#1170]
I tried to combine two queries with unionAll where the queries returned a mapped table and an Option. When the query is executed a `SlickException` is thrown.

Here is a simple case to reproduce the problem. When `q1` is used separately, then it works fine. Also when I remove the mapped table from the result or when I remove the lifting of the `t.id` column to an `Option` the query works fine.
```scala
import slick.driver.PostgresDriver.api._

class ArticleTable(tag: Tag) extends Table[Article](tag, "article") {
	def id = column[String]("id", O.PrimaryKey)
	def name = column[String]("name")

	def * = (id, name) <> (Article.tupled, Article.unapply)
}

val table = TableQuery[ArticleTable]

val q1 = for {
	t <- table
} yield (t, t.id.?)

val q2 = for {
	t <- table
} yield (t, t.id.?)

val q3 = q1.unionAll(q2)
println(q3.result.statements.mkString("\n"))
```
Slick version 3.0.0, Scala version 2.11.6

The exception that was thrown when I run this:
```
slick.SlickException: ProductNode child IfThenElse has UnassignedType
        at slick.ast.ProductNode$$anonfun$buildType$1.apply(Node.scala:173)
        at slick.ast.ProductNode$$anonfun$buildType$1.apply(Node.scala:171)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at slick.ast.ProductNode$class.buildType(Node.scala:175)
        at slick.ast.ProductNode$$anon$2.buildType(Node.scala:189)
        at slick.ast.ProductNode$class.withComputedTypeNoRec(Node.scala:170)
        at slick.ast.ProductNode$$anon$2.withComputedTypeNoRec(Node.scala:189)
        at slick.compiler.HoistClientOps$$anonfun$apply$1$$anonfun$apply$2.apply(HoistClientOps.scala:34)
        at slick.compiler.HoistClientOps$$anonfun$apply$1$$anonfun$apply$2.apply(HoistClientOps.scala:15)
        at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:23)
        at slick.compiler.HoistClientOps$$anonfun$apply$1.apply(HoistClientOps.scala:15)
        at slick.compiler.HoistClientOps$$anonfun$apply$1.apply(HoistClientOps.scala:14)
        at slick.compiler.CompilerState.map(QueryCompiler.scala:181)
        at slick.compiler.HoistClientOps.apply(HoistClientOps.scala:14)
        at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:79)
        at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:78)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at slick.ast.SymbolNamer.use(Symbol.scala:92)
        at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
        at slick.compiler.QueryCompiler$$anonfun$runPhases$4.apply(QueryCompiler.scala:75)
        at slick.compiler.QueryCompiler$$anonfun$runPhases$4.apply(QueryCompiler.scala:75)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.Iterator$class.foreach(Iterator.scala:750)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1202)
        at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:75)
        at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
        at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
        at slick.profile.BasicProfile$API$class.streamableQueryActionExtensionMethods(BasicProfile.scala:71)
        at slick.driver.JdbcProfile$$anon$2.streamableQueryActionExtensionMethods(JdbcProfile.scala:95)
```

**Comment by btd** [comment]
Got the same exception today
