### ISSUE TITLE
Slick 3: Connection starvation. slick.jdbc.JdbcBackend$BaseSession.close() tries to create a new connection

### ISSUE THREAD

**Issue by mustajarvi** [slick/slick#1181]
Works fine when the number of reqs/s is low, but as soon as it hits a burst slick uses up all connections in the connection pool and then becomes unable to close the connections again. The stacktrace looks like this:

```
AsyncExecutor.CallerRunsRejectionPolicy-1" - Thread t@160
   java.lang.Thread.State: TIMED_WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <452a0e43> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.apache.tomcat.jdbc.pool.FairBlockingQueue.poll(FairBlockingQueue.java:152)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:186)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:48)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394)
	- locked <7e099d8> (a slick.jdbc.JdbcBackend$BaseSession)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394)
	at slick.jdbc.JdbcBackend$BaseSession.close(JdbcBackend.scala:408)
	at slick.backend.DatabaseComponent$DatabaseDef$class.releaseSession(DatabaseComponent.scala:217)
	at slick.jdbc.JdbcBackend$DatabaseDef.releaseSession(JdbcBackend.scala:38)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:232)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

From the stack trace it looks like it tries to create a connection when close() is called, which deadlocks since it has already used up all connections.

 Is there a synchronization or visibility issue on the lazy initialization of `conn`?

Around https://github.com/slick/slick/blob/3.0/slick/src/main/scala/slick/jdbc/JdbcBackend.scala#L391

```scala
  class BaseSession(val database: Database) extends SessionDef {
    protected var open = false
    protected var doRollback = false
    protected var inTransactionally = 0

    def isOpen = open
    def isInTransaction = inTransactionally > 0

    lazy val conn = { open = true; database.source.createConnection }
    lazy val metaData = conn.getMetaData()

    def capabilities = {
      val dc = database.capabilities
      if(dc ne null) dc
      else {
        val newDC = new DatabaseCapabilities(this)
        database.capabilities = newDC
        newDC
      }
    }

    def close() {
      if(open) conn.close()
    }
    <snip>
```

**Comment by mustajarvi** [comment]
I realize that I don't have a complete picture of how the various bits and pieces of slick interacts internally so I'm throwing this out.

@szeiger :
Could `close()` be called by another thread than the one which accessed the `lazy var conn`? In that case `open` needs to be `volatile`, right? Otherwise the synchronized write `open = true;` in the lazy val initialization won't necessarily be visible to the thread calling `close()´.

**Comment by szeiger** [comment]
The stack trace definitely looks like that's happening but I'm not sure how it can. JDBC connections in general are not thread-safe, therefore the DBIO interpreter provides the necessary memory barriers when passing connections from one thread to another.

**Comment by szeiger** [comment]
OK, I believe this is the problem: While we mark the Session as open before any chance of initialization failure, a lazy val is only marked as initialized by Scala if it was computed successfully, otherwise initialization is attempted again on the next access:

```
$ scala
Welcome to Scala version 2.11.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_55).
Type in expressions to have them evaluated.
Type :help for more information.

scala> lazy val conn: String = { println("init"); throw new Exception }
conn: String = <lazy>

scala> conn
init
java.lang.Exception
  at .conn$lzycompute(<console>:7)
  at .conn(<console>:7)
  ... 32 elided

scala> conn
init
java.lang.Exception
  at .conn$lzycompute(<console>:7)
  at .conn(<console>:7)
  ... 32 elided
```

So if `database.source.createConnection` fails when initializing `conn` at an earlier point, the Session is already marked as `open` but then accessing `conn` again in `close` causes another initialization attempt.

**Comment by mustajarvi** [comment]
Right. Great catch!
