### ISSUE TITLE
DBIOAction#andThen is not stack-safe

### ISSUE THREAD

**Issue by julienrf** [slick/slick#1186]
When running `DBIO.seq` on a moderately large collection (less than 2000 elements) I get the following SO:

~~~
java.lang.StackOverflowError
	at slick.util.SlickLogger.isDebugEnabled(Logging.scala:11)
	at slick.backend.DatabaseComponent$DatabaseDef$class.logAction(DatabaseComponent.scala:318)
	at slick.jdbc.JdbcBackend$DatabaseDef.logAction(JdbcBackend.scala:38)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:140)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:148)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:148)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
	at slick.backend.DatabaseComponent$DatabaseDef$class.runInContext(DatabaseComponent.scala:148)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
	…
~~~

**Comment by prettynatty** [comment]
I have the same issue with depply nested actions.
