### ISSUE TITLE
Error while running queries using slick-3.1.0-M1

### ISSUE THREAD

**Issue by mohittt8** [slick/slick#1205]
While trying out slick-3.1.0-M1, one of our tests failed, with the exception - 
```
play.api.Application$$anon$1: Execution exception[[MatchError: Path @172189711._1.@1882835008 (of class slick.ast.Select)]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.6.jar:2.3.6]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
Caused by: scala.MatchError: Path @172189711._1.@1882835008 (of class slick.ast.Select)
        at slick.compiler.HoistClientOps.rewriteDBSide(HoistClientOps.scala:88) ~[slick_2.11-3.1.0-M1.jar:na]
        at slick.compiler.HoistClientOps$$anonfun$rewriteDBSide$1.apply(HoistClientOps.scala:90) ~[slick_2.11-3.1.0-M1.jar:na]
        at slick.compiler.HoistClientOps$$anonfun$rewriteDBSide$1.apply(HoistClientOps.scala:90) ~[slick_2.11-3.1.0-M1.jar:na]
        at slick.ast.Util$$anonfun$mapOrNone$1.apply(Util.scala:17) ~[slick_2.11-3.1.0-M1.jar:na]
        at slick.ast.Util$$anonfun$mapOrNone$1.apply(Util.scala:16) ~[slick_2.11-3.1.0-M1.jar:na]
```

I could reduce the code which causes the issue to this 

```
import slick.driver.MySQLDriver.api._

case class User(id: Option[Int], name: String)

class Users(_tableTag: Tag) extends Table[User](_tableTag, "user") {
  def * = (id.?, name) <> (User.tupled, User.unapply)

  val id: Rep[Int] = column[Int]("id", O.AutoInc, O.PrimaryKey)
  val name: Rep[String] = column[String]("name", O.Length(200, varying = true))

}

-- Tables.scala 
case class Payment(id: Option[Int], txnAmount: Int, moId: Option[Int])

class Payments(_tableTag: Tag) extends Table[Payment](_tableTag, "payment") {
  def * = (id.?, txnAmount, eventId) <> (Payment.tupled, Payment.unapply)

  val id: Rep[Int] = column[Int]("id", O.AutoInc, O.PrimaryKey)
  val txnAmount: Rep[Int] = column[Int]("txn_amount")
  val eventId: Rep[Option[Int]] = column[Option[Int]]("event_id", O.Default(None))

  lazy val eventFk = foreignKey("payment_event_fk", eventId, new TableQuery(tag => new Events(tag)))(r => Rep.Some(r.id), onUpdate = ForeignKeyAction.NoAction, onDelete = ForeignKeyAction.NoAction)
}

case class Event(id: Option[Int], title: String, hostId: Int)

class Events(_tableTag: Tag) extends Table[Event](_tableTag, "event") {
  def * = (id.?, title, hostId) <> (Event.tupled, Event.unapply)

  /** Database column id SqlType(INT), AutoInc, PrimaryKey */
  val id: Rep[Int] = column[Int]("id", O.AutoInc, O.PrimaryKey)
  /** Database column title SqlType(VARCHAR), Length(200,true) */
  val title: Rep[String] = column[String]("title", O.Length(200, varying = true))
  /** Database column host_id SqlType(INT) */
  val hostId: Rep[Int] = column[Int]("host_id")

  lazy val userFk = foreignKey("event_user_fk", hostId, new TableQuery(tag => new Users(tag)))(r => r.id, onUpdate = ForeignKeyAction.NoAction, onDelete = ForeignKeyAction.NoAction)
}

case class Follower(followee: Int, follower: Int)

class Followers(_tableTag: Tag) extends Table[Follower](_tableTag, "follower") {
  def * = (followeeId, followerId) <> (Follower.tupled, Follower.unapply)

  /** Database column follower_id SqlType(INT) */
  val followeeId: Rep[Int] = column[Int]("followee_id")
  /** Database column followee_id SqlType(INT) */
  val followerId: Rep[Int] = column[Int]("follower_id")

  lazy val userFk1 = foreignKey("follower_user_fk", followerId, new TableQuery(tag => new Users(tag)))(r => r.id, onUpdate = ForeignKeyAction.NoAction, onDelete = ForeignKeyAction.NoAction)
  lazy val userFk2 = foreignKey("followee_user_fk", followeeId, new TableQuery(tag => new Users(tag)))(r => r.id, onUpdate = ForeignKeyAction.NoAction, onDelete = ForeignKeyAction.NoAction)
}

--- App file 
object HelloSlick extends App {
  val db = Database.forConfig("mysql")
  try {
    val users = TableQuery[Users]
    val payments = TableQuery[Payments]
    val events = TableQuery[Events]
    val followers = TableQuery[Followers]
    val setupAction: DBIO[Unit] = DBIO.seq(
      (followers.schema ++ users.schema ++ payments.schema ++ events.schema).create)

    val setupFuture: Future[Unit] = db.run(setupAction)

    val qcUserDetailsById = Compiled {
      id: Rep[Int] =>
        users
          .joinLeft(events).on { case (user, events) => events.hostId === user.id }.filter { case (user, events) => user.id === id }
          .joinLeft(payments).on { case (((userId), events), payments) => events.map(_.id) === payments.eventId }
          .groupBy { case (((user), events), payments) => (user.id) }
          .map { case ((userId), userWithEventAndPayment) => (userId, userWithEventAndPayment.map(_._1._2.map(_.id)).countDistinct, userWithEventAndPayment.map(_._2.map(_.txnAmount)).sum.getOrElse(0)) }
          .joinLeft(followers).on { case ((userId, sessionCount, txnAmount), followers) => userId === followers.followeeId }
          .groupBy { case ((userId, sessionCount, txnAmount), followers) => (userId, sessionCount, txnAmount) }
          .map { case ((userId, sessionCount, txnAmount), userDetailsWithFollowers) => (userId, sessionCount, txnAmount, userDetailsWithFollowers.map(_._2.map(_.followerId)).countDistinct) }
    }

    println(db.run(qcUserDetailsById(1).result))

  } finally db.close
```

It works fine in slick-3.0. I am using MySQL 5.6 and scala 2.11.6

**Comment by mohittt8** [comment]
It works in slick-3.1.0-M2
