### ISSUE TITLE
Error creating database with sqlu

### ISSUE THREAD

**Issue by Kreinoee** [slick/slick#1227]
When I try to create a datase with sqlu (against a postgresql db):
```
val sql = sqlu"""CREATE DATABASE $dbName with owner = test_user TEMPLATE = $template;"""
val f = initDb.run(sql)
Await.result(f, 5.seconds)
```
Then it fails with the following error:
```
ERROR: syntax error at or near "$1"
[info]   Position: 17
[info]     at dk.cirque.util.inMemDbTest.SlickDatabaseFactoryForRdsPostgresBasedTests.forBilling(SlickDatabaseFactoryForRdsPostgresBasedTests.scala:91)
[info]     at dk.cirque.util.inMemDbTest.SlickDatabaseFactoryForRdsPostgresBasedTestsTest$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(SlickDatabaseFactoryForRdsPostgresBasedTestsTest.scala:33)
[info]     at dk.cirque.util.inMemDbTest.SlickDatabaseFactoryForRdsPostgresBasedTestsTest$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply(SlickDatabaseFactoryForRdsPostgresBasedTestsTest.scala:31)
[info]     at dk.cirque.util.inMemDbTest.SlickDatabaseFactoryForRdsPostgresBasedTestsTest$$anonfun$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply(SlickDatabaseFactoryForRdsPostgresBasedTestsTest.scala:31)
[info]     at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]     at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]     at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:422)
```

It does however work correctly if using the slick.jdbc.StaticQuery:
```
initDb.withSession {implicit session ⇒
    import slick.jdbc.{StaticQuery ⇒ Q}
    Q.updateNA(s"CREATE DATABASE $dbName with owner = test_user TEMPLATE = $template;").execute
}
```

**Comment by szeiger** [comment]
sqlu uses bind variables, not simple string interpolation. You need to use `#$` instead of `$` for that.
