### ISSUE TITLE
object closed when retrieving blob content from h2 using slick3 h2 driver

### ISSUE THREAD

**Issue by zinking** [slick/slick#1231]
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-166]
at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
at org.h2.message.DbException.get(DbException.java:169)
at org.h2.message.DbException.get(DbException.java:146)
at org.h2.message.DbException.get(DbException.java:135)
at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1383)
at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
at org.h2.jdbc.JdbcBlob.checkClosed(JdbcBlob.java:317)
at org.h2.jdbc.JdbcBlob.length(JdbcBlob.java:54)

this happened when I upgraded my slick from 2 to 3 and doing the migration. H2 version itself didn't change. on slick2 the code works fine.
this happened when I first retrieve the blob row record from database using slick db.run and then transforming the blob into some text data [tried both stream & bytes].

it seems to me that, the blob is not able to get back the connections etc...
what is the correct way to pull the blob data out and transform into text using slick3 h2 driver ?

**Comment by zinking** [comment]
some of the findings. it looks to me that now session is now automatically managed. so when the result is returned, the session blob referred to is already closed. 

wrapped the query with `withPinnedSession` this time with a different error, stream already closed.  the only way seem to stream the blob content, but it is not what I want right now. just want to port the previous versions.

**Comment by szeiger** [comment]
A mapping with `<>` should work but it's not the most elegant solution. I think we need to add DriverAction.mapResult, similar to DatabasePublisher.mapResult.
