### ISSUE TITLE
Hard to find error according to stacktrace.

### ISSUE THREAD

**Issue by jilen** [slick/slick#1277]
As with `slick 3.x` below stack trace is usually useless to point out where error occurs. 

```
Caused by: java.util.NoSuchElementException: Invoker.first
	at slick.jdbc.Invoker$class.first(Invoker.scala:39)
	at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
	at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:231)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by cvogt** [comment]
That's general problem with Futures or threads more generally speaking, not specific to Slick at all. The latest Scala IDE (Eclipse) is said to have a debugger that manages to visualize the point of origin across futures, but I haven't tried it. Another solution is using a synchronous executioncontext during debugging. Here is how it can be implemented

```scala
import scala.concurrent._
implicit object SynchronousExecutionContext extends ExecutionContext {
  def execute( runnable: Runnable ): Unit = runnable.run
  def reportFailure( cause: Throwable ): Unit = throw new Exception( cause )
}
```

You'd need to make sure Slick uses it for both cpu-bound and db io bound threads. You are usually providing the former to slick via implicits. The latter is configured through Slick's config. I don't know if and how you can swap it out for the synchronous one. @szeiger should know. 

@szeiger a solution to this may be worth documenting in the docs, despite it being a more general problem.

**Comment by jilen** [comment]
@cvogt What if this occurs on an production server ? I would advice that slick provide some addtional info, such as `table name` or `sql statement` while error occurs.

**Comment by cvogt** [comment]
right, that would indeed be nice. A thing @szeiger and I talked about at some point is potentially allowing to tag query fragments with identifying comments and show them in sql comments. If the above would show the SQL query in a wrapping exception, it would allow pin-pointing exactly.

**Comment by szeiger** [comment]
You can already name a DBIOAction. While this name won't show up in the SQL statement, it is printed to the log, which should make it easier to correlate it with an error message that occurs directly after the log message on the same thread.

We have a team at Typesafe working on more advanced monitoring and debugging integration for asynchronous applications. You will probably see the first the iteration (targeting Akka) in an RP release soon, with Slick following. Eventually the instrumentation inferfaces should find their way into the individual open source projects.

As far as switching execution to synchronous mode goes, the most thorough way to do this is to set the `useSameThread` flag in the JdbcActionContext by subclassing JdbcBackend#DatabaseDef. This will replace all user-provided ExecutionContexts by DBIO.sameThreadExecutionContext. If you control those anyway, you can just replace the database thread pool by specifying a custom AsyncExecutor in the Database.for... call (not in forConfig though; there is currently no way to completely replace the pool when using an external config file)

**Comment by nafg** [comment]
Why can't Futures just pass around an implicit SourceCodeLocation macro?

**Comment by rayronvictor** [comment]
I was getting this error ``Caused by: java.util.NoSuchElementException: Invoker.first`` because I was trying to get from an Option that was None.

**Comment by szeiger** [comment]
The monitoring integration probably won't happen. It would be nice if we could pass some sort of correlation ID through DBIOActions down to the threads that execute them. Maybe an MDC that could contain both an auto-generated ID and the optional action name? And set it up as the logging MDC in the execution threads. Getting the functionality right shouldn't be hard. I expect the main issue will be performance.

**Comment by jilen** [comment]
@szeiger Sounds great! And I think logging something on error actually won't like to cause performance issue

**Comment by gaelrenoux** [comment]
Having the same problem here: in production, I have an error log that is totally uninformative. I need to raise the log level to DEBUG and reproduce to find out which query is having a problem. Just having Slick log the full query at ERROR level when an exception occurs would be enormously helpful.

@szeiger The query name actually doesn't show up in the stack trace, or anywhere in the exception. You need to actually have the action at the point where you catch the exception. The exception is directly the SQLException coming from the driver, and the stack trace looks like that (I'm using Play-Slick 1.1.1, if it changes anything): 
```
org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position : 21
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173) ~[na:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:616) ~[na:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:466) ~[na:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:459) ~[na:na]
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44) ~[na:na]
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.execute(PreparedStatementJavassistProxy.java) ~[na:na]
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39) ~[na:na]
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22) ~[na:na]
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48) ~[na:na]
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) ~[na:na]
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22) ~[na:na]
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:100) ~[na:na]
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:100) ~[na:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[na:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45-internal]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45-internal]
```
If I log the action itself, I get the names:
> AndThenAction(Vector(NamedAction(slick.jdbc.SQLActionBuilder$$anon$1@1391914d,Test 1), NamedAction(slick.jdbc.SQLActionBuilder$$anon$1@2f519f0d,Test 2)))

**Comment by nafg** [comment]
How about using something like @lihaoyi's `sourcecode` which can capture
the line number, variable name, etc., of the offending action(s)?

Honestly Future should do that, but at least DBIO could provide such an
"async stacktrace."

**Comment by cvogt** [comment]
I think that's a good idea @nafg

**Comment by ksaleh** [comment]
@cvogt I'm running into this issue on production.  I made the change you suggested on Sept 8, 201 to run slick synchronously when debugging for both cpu and db threads.

Can I run on production with this change? do you any issues that I'm not aware of.  I don't have any performance problems which require me to run async for this application.

Thank you,

**Comment by cvogt** [comment]
@ksaleh if you are fine with blocking your thread during the database queries, there shouldn't be a problem running it in production. It means that if you have (number of cores) * (number of long running queries) running, your server will be blocked for answering new requests until one returns. Maybe not an issue for you.

**Comment by fedotxxl** [comment]
I just can't understand how people use it in production. Stacktrace is totally useless. I've got two assumptions:
- people don't have bugs
- people don't use it in production

**Comment by vsingal-p** [comment]
Same issue. I don't get the line at which code fails. Nothing informative. 
It's impossible to debug. Any pointers?

**Comment by nafg** [comment]
If anyone has an idea how to solve this, a PR would be great

**Comment by fedotxxl** [comment]
This comment https://github.com/slick/slick/issues/1277#issuecomment-138563794 suggests using `useSameThread`. It will be ok for development but I spent 4 hours and didn't succeed to be able using it - can you provide an example code? I searched GitHub with no luck

**Comment by ljakupi** [comment]
Just like @rayronvictor said,  ".head"-ing on empty lists or Option can through `java.util.NoSuchElementException: Invoker.first`.
