### ISSUE TITLE
Counting not null fields in slick-3.1.0-RC1

### ISSUE THREAD

**Issue by mohittt8** [slick/slick#1285]
While trying out slick 3.1.0-RC1, one of our tests failed. The test counts number of non null fields after a join and group by. 
For that, the query is something along the lines:- 

    tableA
        .leftJoin(tableB)
        .groupBy(...)
        .map {case (...) => _.map(_.tblBNullableField).length

The previous behaviour was to ignore the null values and count the rest. The behaviour was changed for  #1237.

I tried counting using `_.filter(_.tblBNullableField.isDefined).length` but that throws a error saying:- 
<pre><code>slick.SlickTreeException: Cannot convert node to SQL Comprehension
 Path s11._2 : Vector[t2<{s3: Option[String'], s4: Option[String'], s5: String', s6: Int', s7: Option[Int'], s8: Option[String'], s9: String', s10: SOption[OptionDisc/Int]}>]
   at slick.compiler.MergeToComprehensions$$anonfun$21.apply(MergeToComprehensions.scala:146)
   at slick.compiler.MergeToComprehensions$$anonfun$21.apply(MergeToComprehensions.scala:146)
   at scala.Option.getOrElse(Option.scala:121)
   at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertBase$1(MergeToComprehensions.scala:146)
   at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:140)
   at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:140)
   at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:323)
   at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeFilterWhere$1(MergeToComprehensions.scala:140)
   at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeGroupBy$1(MergeToComprehensions.scala:135)
   at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96)
</pre></code>
 
Please let me know how can I count not nullable fields with the new behaviour of `length`

**Comment by szeiger** [comment]
More complicated aggregations, for example ones involving nested `filter` operations, are not yet supported. The behavior should still be the same as in 3.0 as long as you only count a single column. I'll try to reproduce the issue.

**Comment by szeiger** [comment]
It looks like the current behavior is actually what we want for the future, i.e. `length` always counts the length of the collection, no matter the contents. I think the best way forward is to leave it at that, document this change, and add a new aggregation operator that counts a single column (and is only defined for single-column queries in the first place, thus avoiding the ambiguity of the current design).
