### ISSUE TITLE
Slick codegen 3.0.3 crashes with Postgres real or double type e.g.

### ISSUE THREAD

**Issue by bravegag** [slick/slick#1294]
14:11:45.533 [ForkJoinPool-1-worker-57] DEBUG s.backend.DatabaseComponent.action - #137: success slick.jdbc.JdbcModelBuilder$TableBuilder@72fb1f6f
	14:11:45.540 [ForkJoinPool-1-worker-57] DEBUG s.backend.DatabaseComponent.action - #138: success (List(slick.jdbc.JdbcModelBuilder$TableBuilder@103d47d2, slick.jdbc.JdbcModelBuilder$TableBuilder@30105ffe, slick.jdbc.JdbcModelBuilder$TableBuilder@514ba337, slick.jdbc.JdbcModelBuilder$TableBuilder@167db97b, slick.jdbc.JdbcModelBuilder$TableBuilder@7f7a0d0b, slick.jdbc.JdbcModelBuilder$TableBuilder@71bdec94, slick.jdbc.JdbcModelBuilder$TableBuilder@7582667b, slick.jdbc.JdbcModelBuilder$TableBuilder@3080e6af, slick.jdbc.JdbcModelBuilder$TableBuilder@187b58c8, slick.jdbc.JdbcModelBuilder$TableBuilder@1fbda7e1, slick.jdbc.JdbcModelBuilder$TableBuilder@1fa31ce, slick.jdbc.JdbcModelBuilder$TableBuilder@672d2e34, slick.jdbc.JdbcModelBuilder$TableBuilder@50af19e0, slick.jdbc.JdbcModelBuilder$TableBuilder@22df2ebb, slick.jdbc.JdbcModelBuilder$TableBuilder@72fb1f6f),Map(MQName(public.portfolio) -> slick.jdbc.JdbcModelBuilder$TableBuilder@1fbda7e1, MQName(public.fund) -> slick.jdbc.JdbcModelBuilder$TableBuilder@7f7a0d0b, MQName(public.vx_instrument) -> slick.jdbc.JdbcModelBuilder$TableBuilder@50af19e0, MQName(public.configuration) -> slick.jdbc.JdbcModelBuilder$TableBuilder@514ba337, MQName(public.yield_calibration) -> slick.jdbc.JdbcModelBuilder$TableBuilder@22df2ebb, MQName(public.yield_momentum_factor) -> slick.jdbc.JdbcModelBuilder$TableBuilder@72fb1f6f, MQName(public.instrument) -> slick.jdbc.JdbcModelBuilder$TableBuilder@3080e6af, MQName(public.universe) -> slick.jdbc.JdbcModelBuilder$TableBuilder@672d2e34, MQName(public.order_book) -> slick.jdbc.JdbcModelBuilder$TableBuilder@187b58c8, MQName(public.history) -> slick.jdbc.JdbcModelBuilder$TableBuilder@71bdec94, MQName(public.broker) -> slick.jdbc.JdbcModelBuilder$TableBuilder@30105ffe, MQName(public.allocation) -> slick.jdbc.JdbcModelBuilder$TableBuilder@103d47d2, MQName(public.price_momentum_factor) -> slick.jdbc.JdbcModelBuilder$TableBuilder@1fa31ce, MQName(public.history_import) -> slick.jdbc.JdbcModelBuilder$TableBuilder@7582667b, MQName(public.currency) -> slick.jdbc.JdbcModelBuilder$TableBuilder@167db97b),slick.jdbc.JdbcModelBuilder$Builders@79372d8b)
	14:11:45.580 [ForkJoinPool-1-worker-57] DEBUG s.driver.PostgresDriver$ModelBuilder - Ignoring default value now() for column configuration.time of type java.sql.Timestamp, meta data: MColumn(MQName(public.configuration),time,93,timestamp,Some(29),Some(6),10,Some(false),None,Some(now()),29,3,Some(false),None,None,Some(false))
	14:11:45.586 [ForkJoinPool-1-worker-57] DEBUG s.backend.DatabaseComponent.action - #139: SynchronousDatabaseAction.Unpin
	Exception in thread "main" java.lang.NumberFormatException: For input string: "0::real"
		at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
		at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
		at java.lang.Float.parseFloat(Float.java:451)
		at scala.collection.immutable.StringLike$class.toFloat(StringLike.scala:280)
		at scala.collection.immutable.StringOps.toFloat(StringOps.scala:30)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$default$1.apply(JdbcModelBuilder.scala:222)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$default$1.apply(JdbcModelBuilder.scala:213)
		at scala.Option.map(Option.scala:146)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder.default(JdbcModelBuilder.scala:213)
		at slick.driver.PostgresDriver$ModelBuilder$$anon$2.slick$driver$PostgresDriver$ModelBuilder$$anon$$super$default(PostgresDriver.scala:78)
		at slick.driver.PostgresDriver$ModelBuilder$$anon$2$$anonfun$default$3.apply(PostgresDriver.scala:78)
		at slick.driver.PostgresDriver$ModelBuilder$$anon$2$$anonfun$default$3.apply(PostgresDriver.scala:77)
		at scala.Option.getOrElse(Option.scala:121)
		at slick.driver.PostgresDriver$ModelBuilder$$anon$2.default(PostgresDriver.scala:77)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
		at scala.Option.getOrElse(Option.scala:121)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:253)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:263)
		at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:281)
		at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:162)
		at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:162)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.Iterator$class.foreach(Iterator.scala:750)
		at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
		at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
		at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
		at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
		at scala.collection.AbstractTraversable.map(Traversable.scala:104)
		at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
		at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
		at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
		at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:94)
		at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:94)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
		at scala.collection.immutable.List.foreach(List.scala:381)
		at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
		at scala.collection.immutable.List.map(List.scala:285)
		at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:94)
		at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:91)
		at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
		at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
		at slick.backend.DatabaseComponent$DatabaseDef$$anonfun$runInContext$1.apply(DatabaseComponent.scala:146)
		at slick.backend.DatabaseComponent$DatabaseDef$$anonfun$runInContext$1.apply(DatabaseComponent.scala:146)
		at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
		at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
		at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
		at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
		at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
		at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
		at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
		at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
		at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by maquessime** [comment]
@bravegag cannot reproduce with either real or double. Could you specify which postgres jdbc driver are you using and which postgres server version is used?

Here is the testing project : https://github.com/maquessime/slick-codegen-example/tree/postgres

here is my table def : 

````
                               Table "public.films"
   Column    |       Type       | Modifiers | Storage | Stats target | Description 
-------------+------------------+-----------+---------+--------------+-------------
 test        | real             |           | plain   |              | 
 test_double | double precision |           | plain   |              | 
```
thanks!

**Comment by nkconnor** [comment]
try adding a default, e.g. `'1.5'::real`

**Comment by nkconnor** [comment]
``::json` seems to fail as well. (using 3.3.2)

**Comment by bravegag** [comment]
Oh this has been opened for 5 years :D I completely lost context on the versions of that and obviously found a solution to work with. No idea about it now sorry :(

**Comment by maquessime** [comment]
@nkconnor yeah I'm not.
