### ISSUE TITLE
Update docs to avoid: ClassNotFoundException: slick.jdbc.hikaricp.HikariCPJdbcDataSource$

### ISSUE THREAD

**Issue by bthibault** [slick/slick#1330]
New Description:

Have sbt dependency explicitly in the docs:

`"com.typesafe.slick" %% "slick-hikaricp" % "3.1.0"`

Original Description:
Everything works as expected with Slick 3.0, but appears this class isn't there or isn't getting loaded in 3.1 ... 

Exception in thread "main" java.lang.ClassNotFoundException: slick.jdbc.hikaricp.HikariCPJdbcDataSource$
    at java.lang.ClassLoader.findClass(ClassLoader.java:530)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at slick.util.ClassLoaderUtil$$anon$1.loadClass(ClassLoaderUtil.scala:12)
    at slick.jdbc.JdbcDataSource$.loadFactory$1(JdbcDataSource.scala:30)
    at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:35)
    at slick.jdbc.JdbcBackend$DatabaseFactoryDef$class.forConfig(JdbcBackend.scala:268)
    at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:33)
    at slick.jdbc.JdbcBackend$class.createDatabase(JdbcBackend.scala:36)
    at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:498)
    at slick.jdbc.JdbcBackend$.createDatabase(JdbcBackend.scala:498)
    at slick.backend.DatabaseConfig$$anon$1.db$lzycompute(DatabaseConfig.scala:73)
    at slick.backend.DatabaseConfig$$anon$1.db(DatabaseConfig.scala:72)
    at CaseClassMapping$.delayedEndpoint$CaseClassMapping$1(CaseClassMapping.scala:16)
    at CaseClassMapping$delayedInit$body.apply(CaseClassMapping.scala:10)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)

**Comment by szeiger** [comment]
This is no longer part of the core in 3.1. Did you add the slick-hikaricp module?

**Comment by bthibault** [comment]
ah no ... that would do it... i didn't see that anywhere ... is there a doc somewhere?

**Comment by djx314** [comment]
<http://slick.typesafe.com/doc/3.1.0/gettingstarted.html#adding-slick-to-your-project>

**Comment by bthibault** [comment]
:+1:

**Comment by zinking** [comment]
making these kind of dependencies explicit saves people's time 
"com.typesafe.slick" %% "slick-hikaricp" % "3.1.0",

**Comment by cvogt** [comment]
@zinking what exactly do you have in mind?

**Comment by djx314** [comment]
slick's doc havn't any string like "com.typesafe.slick" %% "slick-hikaricp" % "3.1.0"

**Comment by cvogt** [comment]
yeah, I think that would be an improvement. re-opening this as a docs issue

**Comment by cvogt** [comment]
@djx314 @zinking one of you have time to update the docs and create a PR?

**Comment by stewSquared** [comment]
Perhaps the docs should also be updated to make it more obvious that this is a default dependency.
 
The recommended configuration at http://slick.typesafe.com/doc/3.1.1/database.html will fail unless it's added, so we might as well add it to the list of libraryDependencies and save everyone the trouble of looking in the docs for `forConfig`.

**Comment by d6y** [comment]
Closing, as the PR for the documentation change has been merged in. Thanks!

**Comment by raam86** [comment]
There is still nothing in the docs referring to this dependency

**Comment by raam86** [comment]
Nice. Slick is such a good product but it really suffers from lack of docs.
Thank you very much for your efforts

**Comment by setyven** [comment]
Correct me if I'm wrong, but I believe it isn't updated yet.

**Comment by cvogt** [comment]
Reopening for verification

**Comment by d6y** [comment]
Confirming that the Hikaricp dependency is in [the getting started guide](http://slick.lightbend.com/doc/3.2.0/gettingstarted.html):

![getting started slick 3 2 0 documentation 2017-04-18 11-08-18](https://cloud.githubusercontent.com/assets/102661/25125663/86566d0e-2427-11e7-84aa-65d11ce87cb3.png)

**Comment by setyven** [comment]
@d6y yes, sorry I was looking at 3.1 docs.
