### ISSUE TITLE
SlickException: All columns in index must belong to table xxx

### ISSUE THREAD

**Issue by hepin1989** [slick/slick#1350]
```
Caused by: slick.SlickException: All columns in index must belong to table xxjh_order
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder$$anonfun$addColumnList$1.apply(JdbcStatementBuilderComponent.scala:665) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder$$anonfun$addColumnList$1.apply(JdbcStatementBuilderComponent.scala:659) ~[slick_2.11-3.1.0.jar:na]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[scala-library-2.11.7.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder.addColumnList(JdbcStatementBuilderComponent.scala:659) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder.addIndexColumnList(JdbcStatementBuilderComponent.scala:649) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder.createIndex(JdbcStatementBuilderComponent.scala:610) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder$$anonfun$createPhase1$2.apply(JdbcStatementBuilderComponent.scala:585) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder$$anonfun$createPhase1$2.apply(JdbcStatementBuilderComponent.scala:585) ~[slick_2.11-3.1.0.jar:na]
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Forced$class.foreach(TraversableViewLike.scala:141) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$1.foreach(SeqViewLike.scala:195) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168) ~[scala-library-2.11.7.jar:na]
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197) ~[scala-library-2.11.7.jar:na]
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183) ~[scala-library-2.11.7.jar:na]
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45) ~[scala-library-2.11.7.jar:na]
	at scala.collection.TraversableLike$class.$plus$plus(TraversableLike.scala:158) ~[scala-library-2.11.7.jar:na]
	at scala.collection.immutable.List.$plus$plus(List.scala:196) ~[scala-library-2.11.7.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder.createPhase1(JdbcStatementBuilderComponent.scala:585) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder.buildDDL(JdbcStatementBuilderComponent.scala:582) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.JdbcProfile$class.buildTableSchemaDescription(JdbcProfile.scala:40) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.MySQLDriver$.buildTableSchemaDescription(MySQLDriver.scala:280) ~[slick_2.11-3.1.0.jar:na]
	at slick.driver.MySQLDriver$.buildTableSchemaDescription(MySQLDriver.scala:280) ~[slick_2.11-3.1.0.jar:na]
	at slick.profile.RelationalProfile$TableQueryExtensionMethods.schema(RelationalProfile.scala:62) ~[slick_2.11-3.1.0.jar:na]
	at dao.Dao$$anonfun$2.apply(Dao.scala:31) ~[classes/:na]
	at dao.Dao$$anonfun$2.apply(Dao.scala:29) ~[classes/:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.7.jar:na]
	... 2 common frames omitted

```

I have a table definition:
```
  class Order(_tableTag: Tag) extends Table[OrderRow](_tableTag, "order") {
    def * = (id, channel, paymentType, roleId, goodsId, orderPrice, createTime, originalData, channelOrderId, notifyTime, channelSuccess, realPrice, uid, finishTime, processSuccess, info) <> (OrderRow.tupled, OrderRow.unapply)
    /** Maps whole row to an option. Useful for outer joins. */
    def ? = (Rep.Some(id), Rep.Some(channel), Rep.Some(paymentType), Rep.Some(roleId), Rep.Some(goodsId), Rep.Some(orderPrice), Rep.Some(createTime), originalData, channelOrderId, notifyTime, channelSuccess, realPrice, uid, finishTime, processSuccess, info).shaped.<>({ r => import r._; _1.map(_ => OrderRow.tupled((_1.get, _2.get, _3.get, _4.get, _5.get, _6.get, _7.get, _8, _9, _10, _11, _12, _13, _14, _15, _16))) }, (_: Any) => throw new Exception("Inserting into ? projection not supported."))

    /** Database column id SqlType(BIGINT), AutoInc, PrimaryKey */
    val id: Rep[Long] = column[Long]("id", O.AutoInc, O.PrimaryKey)
    /** Database column channel SqlType(VARCHAR), Length(255,true) */
    val channel: Rep[String] = column[String]("channel", O.Length(255, varying = true))
    /** Database column payment_type SqlType(VARCHAR), Length(255,true) */
    val paymentType: Rep[String] = column[String]("payment_type", O.Length(255, varying = true))
    /** Database column role_id SqlType(BIGINT) */
    val roleId: Rep[Long] = column[Long]("role_id")
    /** Database column goods_id SqlType(BIGINT) */
    val goodsId: Rep[Long] = column[Long]("goods_id")
    /** Database column order_price SqlType(DECIMAL UNSIGNED) */
    val orderPrice: Rep[scala.math.BigDecimal] = column[scala.math.BigDecimal]("order_price")
    /** Database column create_time SqlType(TIMESTAMP) */
    val createTime: Rep[java.sql.Timestamp] = column[java.sql.Timestamp]("create_time")
    /** Database column original_data SqlType(VARCHAR), Length(20480,true), Default(None) */
    val originalData: Rep[Option[String]] = column[Option[String]]("original_data", O.Length(20480, varying = true), O.Default(None))
    /** Database column channel_order_id SqlType(VARCHAR), Length(255,true), Default(None) */
    val channelOrderId: Rep[Option[String]] = column[Option[String]]("channel_order_id", O.Length(255, varying = true), O.Default(None))
    /** Database column notify_time SqlType(TIMESTAMP), Default(None) */
    val notifyTime: Rep[Option[java.sql.Timestamp]] = column[Option[java.sql.Timestamp]]("notify_time", O.Default(None))
    /** Database column channel_success SqlType(BIT), Default(None) */
    val channelSuccess: Rep[Option[Boolean]] = column[Option[Boolean]]("channel_success", O.Default(None))
    /** Database column real_price SqlType(DECIMAL), Default(None) */
    val realPrice: Rep[Option[scala.math.BigDecimal]] = column[Option[scala.math.BigDecimal]]("real_price", O.Default(None))
    /** Database column uid SqlType(VARCHAR), Length(255,true), Default(None) */
    val uid: Rep[Option[String]] = column[Option[String]]("uid", O.Length(255, varying = true), O.Default(None))
    /** Database column finish_time SqlType(TIMESTAMP), Default(None) */
    val finishTime: Rep[Option[java.sql.Timestamp]] = column[Option[java.sql.Timestamp]]("finish_time", O.Default(None))
    /** Database column process_success SqlType(BIT), Default(None) */
    val processSuccess: Rep[Option[Boolean]] = column[Option[Boolean]]("process_success", O.Default(None))
    /** Database column info SqlType(VARCHAR), Length(255,true), Default(None) */
    val info: Rep[Option[String]] = column[Option[String]]("info", O.Length(255, varying = true), O.Default(None))

    /** Index over (channel) (database name channel_idx) */
    val index1 = index("channel_idx", channel)
    /** Index over (channel,paymentType) (database name channel_payment_type_idx) */
    val index2 = index("channel_payment_type_idx", (channel, paymentType))
    /** Index over (roleId) (database name order_role_id_index) */
    val index3 = index("order_role_id_index", roleId)
  }
```
and usage with :
```
  override val creator: (MySQLDriver.api.Tag, String) => Tables.Order = {
    case (tag,name) =>
      new Tables.Order(tag){
        override val tableName = name
      }
  }
```

then do a create table with 
```
new TableQuery(creator(_,name)).schema.create
```

then it's the exception,which comes out here :
https://github.com/slick/slick/blob/3.1/slick/src/main/scala/slick/driver/JdbcStatementBuilderComponent.scala#L664

how coud this be?

**Comment by hepin1989** [comment]
close this for https://github.com/slick/slick/issues/1357
