### ISSUE TITLE
"Cannot convert node to SQL Comprehension" error when calling .length after groupBy + map

### ISSUE THREAD

**Issue by gl-vanger** [slick/slick#1355]
Reproduced in Slick  3.1:

``` scala
//Single field table/entity
case class TestInstance(id: String)

class TestQuery(tag: Tag) extends Table[TestInstance](tag, "test_query") {
  def id = column[String]("id")

  override def * = (id) <> (TestInstance.apply, TestInstance.unapply)
}

object TestQuery {
  val table = TableQuery[TestQuery]
  val q = table.groupBy(_.id).map { case (c, tbl)  =>
    (c, tbl.length)
  }

  q.result //this runs just fine producing following query: "select `id`, count(1) from `test_query` group by `id`"
  q.length.result //<-- Here we'll get an "Cannot convert node to SQL Comprehension" error.
}
```

But if I change problem line with the following:

``` scala
q.drop(0).length.result
```

Everything works fine and query returns correct result (count of grouped rows).

Full Stack Trace of the error:

```
[10.11.2015 15:27:21.088] [ERROR] [application-akka.actor.default-dispatcher-12] [application] Error 'internalError - Cannot convert node to SQL Comprehension
| GroupBy t9 : Vector[(t9<String'>, Vector[t17<{s18: String'}>])]
|   from s8: Bind : Vector[t17<{s18: String'}>]
|     from s13: Table test_query : Vector[@t11<{id: String'}>]
|     select: Pure t17 : Vector[t17<{s18: String'}>]
|       value: StructNode : {s18: String'}
|         s18: Path s13.id : String'
|   by: Path s8.s18 : String'
' occured.
slick.SlickTreeException: Cannot convert node to SQL Comprehension
| GroupBy t9 : Vector[(t9<String'>, Vector[t17<{s18: String'}>])]
|   from s8: Bind : Vector[t17<{s18: String'}>]
|     from s13: Table test_query : Vector[@t11<{id: String'}>]
|     select: Pure t17 : Vector[t17<{s18: String'}>]
|       value: StructNode : {s18: String'}
|         s18: Path s13.id : String'
|   by: Path s8.s18 : String'

    at slick.compiler.MergeToComprehensions$$anonfun$26.apply(MergeToComprehensions.scala:167) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$26.apply(MergeToComprehensions.scala:167) ~[slick_2.11-3.1.0.jar:na]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertBase$1(MergeToComprehensions.scala:167) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:161) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:161) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeFilterWhere$1(MergeToComprehensions.scala:161) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeGroupBy$1(MergeToComprehensions.scala:156) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeSortBy$1(MergeToComprehensions.scala:96) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createTopLevel$1(MergeToComprehensions.scala:253) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$createSourceOrTopLevel$1$1.apply(MergeToComprehensions.scala:236) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$createSourceOrTopLevel$1$1.apply(MergeToComprehensions.scala:234) ~[slick_2.11-3.1.0.jar:na]
    at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createSourceOrTopLevel$1(MergeToComprehensions.scala:234) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertBase$1(MergeToComprehensions.scala:166) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:161) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:161) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeFilterWhere$1(MergeToComprehensions.scala:161) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeGroupBy$1(MergeToComprehensions.scala:146) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeSortBy$1(MergeToComprehensions.scala:96) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$9.apply(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$9.apply(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:319) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createTopLevel$1(MergeToComprehensions.scala:253) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:269) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.convert(MergeToComprehensions.scala:289) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$apply$1$$anonfun$15.apply(MergeToComprehensions.scala:29) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$apply$1$$anonfun$15.apply(MergeToComprehensions.scala:28) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:24) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.ClientSideOp$$anonfun$mapResultSetMapping$1.apply(ClientSideOp.scala:25) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.ClientSideOp$$anonfun$mapResultSetMapping$1.apply(ClientSideOp.scala:25) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.UnaryNode$class.mapChildren(Node.scala:224) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.First.mapChildren(ClientSideOp.scala:31) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.First.nodeMapServerSide(ClientSideOp.scala:35) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.First.nodeMapServerSide(ClientSideOp.scala:31) ~[slick_2.11-3.1.0.jar:na]
    at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:25) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$apply$1.apply(MergeToComprehensions.scala:28) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions$$anonfun$apply$1.apply(MergeToComprehensions.scala:28) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.CompilerState.map(QueryCompiler.scala:226) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.MergeToComprehensions.apply(MergeToComprehensions.scala:28) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:79) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:78) ~[slick_2.11-3.1.0.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58) ~[scala-library-2.11.7.jar:na]
    at slick.ast.SymbolNamer.use(Symbol.scala:112) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler$$anonfun$3.apply(QueryCompiler.scala:65) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler$$anonfun$3.apply(QueryCompiler.scala:63) ~[slick_2.11-3.1.0.jar:na]
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155) ~[scala-library-2.11.7.jar:na]
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155) ~[scala-library-2.11.7.jar:na]
    at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:na]
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[scala-library-2.11.7.jar:na]
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155) ~[scala-library-2.11.7.jar:na]
    at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1194) ~[scala-library-2.11.7.jar:na]
    at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:63) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53) ~[slick_2.11-3.1.0.jar:na]
    at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47) ~[slick_2.11-3.1.0.jar:na]
    at slick.profile.BasicProfile$API$class.repQueryActionExtensionMethods(BasicProfile.scala:52) ~[slick_2.11-3.1.0.jar:na]
    at slick.driver.JdbcProfile$$anon$1.repQueryActionExtensionMethods(JdbcProfile.scala:69) ~[slick_2.11-3.1.0.jar:na]
```

**Comment by sarahgerweck** [comment]
I too am running into this issue in Slick 3.1.1. Fortunately the `.drop(0)` seems to fix it, so we have a workaround.

**Comment by ClementMalaingre** [comment]
We have the same problem here, Slick 3.1

**Comment by prascuna** [comment]
Same issue, Slick 3.2.1

**Comment by YvanZhong** [comment]
Same issue, Slick 3.2.0

**Comment by Reeebuuk** [comment]
Still have this issue in 3.2.3

```
.groupBy(_.productId)
      .map {
        case (productId, grouppedTransactions) =>

            Case If (grouppedTransactions.map(_.client).distinct.length > 1) Then MULTIPLE_CLIENTS Else grouppedTransactions
              .map(_.client)
              .max
              .getOrElse("")
      }
```

grouppedTransactions.map(_.client).distinct.length is giving the exception
grouppedTransactions.map(_.client).length is working fine but it doesn't fit my requirement

**Comment by dope9967** [comment]
Have you tried `.groupBy(...).map(...).subquery.length`? Sometimes `.subquery(...)` helps with errors or incorrect queries being generated.

**Comment by Reeebuuk** [comment]
```
.groupBy(_.productId)
      .map {
        case (productId, grouppedTransactions) =>

            Case If (grouppedTransactions.map(_.client).countDistinct > 1) Then MULTIPLE_CLIENTS Else grouppedTransactions
              .map(_.client)
              .max
              .getOrElse("")
      }
```

countDistinct is depracated but works in this case

**Comment by AnirudhVyas** [comment]
this is still broken in `3.3.3`
here's the code snippet:
```scala
 val subQuery = some_great_table
      .groupBy(_.queryId)
      .map {
        case (queryId, group) =>
          (queryId, group.filter(_.isEnabled).length, group.filter(!_.isEnabled).length)
      }

```

I use above sub-query as a join with other joins - it fails with:

```scala
slick.SlickTreeException: Cannot convert node to SQL Comprehension
| Path s5._2 : Vector[t2<{s3: String', s4: Boolean'}>]

	at slick.compiler.MergeToComprehensions.$anonfun$convert$60(MergeToComprehensions.scala:179)
	at scala.Option.getOrElse(Option.scala:189)
	at slick.compiler.MergeToComprehensions.convertBase$1(MergeToComprehensions.scala:179)
	at slick.compiler.MergeToComprehensions.$anonfun$convert$59(MergeToComprehensions.scala:173)
	at slick.compiler.MergeToComprehensions.$anonfun$convert$59$adapted(MergeToComprehensions.scala:173)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:356)
	at slick.compiler.MergeToComprehensions.mergeFilterWhere$1(MergeToComprehensions.scala:173)
	at slick.compiler.MergeToComprehensions.mergeGroupBy$1(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions.$anonfun$convert$36(MergeToComprehensions.scala:103)
```

**Comment by OlegYch** [comment]
@AnirudhVyas i think this is currently fixed, can you check?

**Comment by cptwunderlich** [comment]
I just had the same (or similar) issue, using Slick 3.4.x on Scala 2.13.

It's a long, complicated query and after a groupBy, I put a `map` with `foo.distinct.length` in there and got a `SlickTreeException` exception. But it does work with `countDistinct`...

**Comment by nafg** [comment]
> I just had the same (or similar) issue, using Slick 3.4.x on Scala 2.13.
> 
> It's a long, complicated query and after a groupBy, I put a `map` with `foo.distinct.length` in there and got a `SlickTreeException` exception. But it does work with `countDistinct`...

@cptwunderlich how about 3.5.2?

**Comment by cptwunderlich** [comment]
@nafg Yes, still happens. I created a reproducer based on the hello-slick project here:
https://github.com/cptwunderlich/hello-slick
