### ISSUE TITLE
Query regression in 3.1.0.

### ISSUE THREAD

**Issue by aloiscochard** [slick/slick#1360]
I got the following run-time exception with a piece code which work fine under `3.0.2`:

```
[info]   Cause: slick.SlickTreeException: Unreachable reference to s2 after resolving monadic joins                                                                                 [268/16123]
[info] | Join Inner : Vector[(@t18<{node_id: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], point: com.vi
vidsolutions.jts.geom.Point', attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]']}>, (@t19<{node_id: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], gr
aph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], point: com.vividsolutions.jts.geom.Point', attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]']}>, (@
t20<{points: com.vividsolutions.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long
'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]'], edge_id: MappedJdbcType[com.bestmile.m
odel.LocalGraph$Edge$ID -> Long']}>, @t21<{points: com.vividsolutions.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[co
m.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]'], 
edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Long']}>)))]
[info] |   left s2: < Table > local_graph_nodes : Vector[@t18<{node_id: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$
ID -> Long'], point: com.vividsolutions.jts.geom.Point', attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]']}>]
[info] |   right s17: Join Inner : Vector[(@t19<{node_id: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], 
point: com.vividsolutions.jts.geom.Point', attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]']}>, (@t20<{points: com.vividsolutions.jts.geom.LineString', source: Mappe
dJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID ->
 Long'], attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]'], edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Long']}>, @t21<{points: com.vividsolutio
ns.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[co
m.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]'], edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Lo
ng']}>))]
[info] |     left s22: Table local_graph_nodes : Vector[@t19<{node_id: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$I
D -> Long'], point: com.vividsolutions.jts.geom.Point', attributes: MappedJdbcType[scala.collection.immutable.List -> Array[byte]']}>]
[info] |     right s23: Join Inner : Vector[(@t20<{points: com.vividsolutions.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_id: MappedJdb
cType[com.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scala.collection.immutable.List -> Array[b
yte]'], edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Long']}>, @t21<{points: com.vividsolutions.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$
Node$ID -> Long'], graph_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scal
a.collection.immutable.List -> Array[byte]'], edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Long']}>)]
[info] |       left s24: Table local_graph_edges : Vector[@t20<{points: com.vividsolutions.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph_
id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scala.collection.immutable.Li
st -> Array[byte]'], edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Long']}>]
[info] |       right s25: Table local_graph_edges : Vector[@t21<{points: com.vividsolutions.jts.geom.LineString', source: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], graph
_id: MappedJdbcType[com.bestmile.model.LocalGraph$ID -> Long'], target: MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], attributes: MappedJdbcType[scala.collection.immutable.L
ist -> Array[byte]'], edge_id: MappedJdbcType[com.bestmile.model.LocalGraph$Edge$ID -> Long']}>]
[info] |       on: Apply Function and : Boolean
[info] |         0: Apply Function = : Boolean
[info] |           0: Path s24.source : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |           1: < Path > s2.node_id : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |         1: Apply Function = : Boolean
[info] |           0: Path s25.target : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |           1: Path s2.node_id : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |     on: Apply Function and : Boolean
[info] |       0: Apply Function and : Boolean
[info] |         0: Apply Function in : Boolean
[info] |           0: Path s22.node_id : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |           1: ProductNode : (MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], MappedJdbcType[com.bestmil
e.model.LocalGraph$Node$ID -> Long'])
[info] |             1: LiteralNode ID(36) (volatileHint=false) : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |             2: LiteralNode ID(30) (volatileHint=false) : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |             3: LiteralNode ID(26) (volatileHint=false) : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |         1: Apply Function = : Boolean
[info] |           0: Path s23._1.target : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |           1: Path s22.node_id : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |       1: Apply Function = : Boolean
[info] |         0: Path s23._2.source : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |         1: Path s22.node_id : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |   on: Apply Function and : Boolean
[info] |     0: Apply Function in : Boolean
[info] |       0: Path s2.node_id : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |       1: ProductNode : (MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long'], MappedJdbcType[com.bestmile.mo
del.LocalGraph$Node$ID -> Long'])
[info] |         1: LiteralNode ID(36) (volatileHint=false) : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |         2: LiteralNode ID(30) (volatileHint=false) : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |         3: LiteralNode ID(26) (volatileHint=false) : MappedJdbcType[com.bestmile.model.LocalGraph$Node$ID -> Long']
[info] |     1: LiteralNode true (volatileHint=false) : Boolean
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1(VerifySymbols.scala:17)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1$$anonfun$slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1$2.apply(VerifySymbols.scala:38)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1$$anonfun$slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1$2.apply(VerifySymbols.scala:38)
[info]   at slick.util.ConstArray.foreach(ConstArray.scala:29)
[info]   at slick.ast.Node$class.childrenForeach(Node.scala:60)
[info]   at slick.ast.Apply.childrenForeach(Node.scala:539)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1(VerifySymbols.scala:38)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1$$anonfun$slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1$2.apply(VerifySymbols.scala:38)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1$$anonfun$slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1$2.apply(VerifySymbols.scala:38)
[info]   at slick.util.ConstArray.foreach(ConstArray.scala:29)
[info]   at slick.ast.Node$class.childrenForeach(Node.scala:60)
[info]   at slick.ast.Apply.childrenForeach(Node.scala:539)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1(VerifySymbols.scala:38)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1(VerifySymbols.scala:35)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1(VerifySymbols.scala:35)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.slick$compiler$VerifySymbols$$anonfun$$verifyScoping$1(VerifySymbols.scala:19)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.apply(VerifySymbols.scala:40)
[info]   at slick.compiler.VerifySymbols$$anonfun$apply$1.apply(VerifySymbols.scala:12)
[info]   at slick.compiler.CompilerState.map(QueryCompiler.scala:226)
[info]   at slick.compiler.VerifySymbols.apply(VerifySymbols.scala:12)
[info]   at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:79)
[info]   at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:78)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[info]   at slick.ast.SymbolNamer.use(Symbol.scala:112)
[info]   at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
[info]   at slick.compiler.QueryCompiler$$anonfun$runPhases$4.apply(QueryCompiler.scala:75)
[info]   at slick.compiler.QueryCompiler$$anonfun$runPhases$4.apply(QueryCompiler.scala:75)
[info]   at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
[info]   at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:742)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
[info]   at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
[info]   at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1194)
[info]   at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:75)
[info]   at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
[info]   at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
[info]   at slick.profile.BasicProfile$API$class.streamableQueryActionExtensionMethods(BasicProfile.scala:54)
[info]   at com.bestmile.persistence.postgresql.PGDriver$PGAPI$.streamableQueryActionExtensionMethods(PGDriver.scala:29)
[info]   at com.bestmile.persistence.schema.LocalGraphSchemaTest$$anonfun$1$$anonfun$8$$anonfun$com$bestmile$persistence$schema$LocalGraphSchemaTest$$anonfun$$anonfun$$f$2$1.apply(LocalGraphS
chemaTest.scala:158)
[info]   at com.bestmile.persistence.schema.LocalGraphSchemaTest$$anonfun$1$$anonfun$8$$anonfun$com$bestmile$persistence$schema$LocalGraphSchemaTest$$anonfun$$anonfun$$f$2$1.apply(LocalGraphS
chemaTest.scala:157)
[info]   at slick.backend.DatabaseComponent$DatabaseDef$$anonfun$runInContext$1.apply(DatabaseComponent.scala:146)
[info]   at slick.backend.DatabaseComponent$DatabaseDef$$anonfun$runInContext$1.apply(DatabaseComponent.scala:146)
[info]   at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[info]   at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[info]   at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[info]   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info]   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info]   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info]   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Is that a known regression? What information would you need to investigate?

Thanks

**Comment by aloiscochard** [comment]
FWIW, during my test I did use `slick-3.1.0` with `slick-pg-0.10.1` (and `joda-time`, `jts` addson), while previously it was `slick-pg-0.9.1`.

**Comment by lisinge** [comment]
Without seeing the actual code it could be the same as #1316

**Comment by aloiscochard** [comment]
@lisinge thanks a lot! according to the example it's exactly the same issue.

I close it for now, and I'll follow the other one, thanks a lot!
