### ISSUE TITLE
Suspected race condition in DriverDataSource.init causing NPEs

### ISSUE THREAD

**Issue by mustajarvi** [slick/slick#1400]
I'm getting NPEs as follows when multiple threads tries to init the driver.

Example program:
```scala
object DriverNPETest extends App{
  import scala.concurrent.ExecutionContext.Implicits.global

  import com.example.db.PgDriver.api._
  import slick._

  import com.example.db.DBConfig

  val DB = DBConfig.defaultDB()

  (1 to 10).foreach{_ =>
    val fut = DB.run(sql"""SELECT 1""".as[Int])
    fut.onFailure{ case e: Exception => e.printStackTrace }
    fut.onSuccess{ case res => println(res) }
  }

  Thread.sleep(2000)
}
```

Throws:
```
java.lang.NullPointerException
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:98)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:64)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:297)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:407)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:100)
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:100)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Looking at `DriverDataSource.scala:98` it seems like `driver` is null. `driver` is initialized in `init` where the initialization is guarded with a volatile boolean variable `initialized`. `initialized` is set to true before the driver is assigned.

I believe that using double checked locking would solve the issue without any performance penalties.

I.e

```scala
  def init: Unit = if(!initialized) {
    try {
      initialized = true
      ....
```

==> 

```scala
  def init: Unit = if(!initialized) {
    this.synchronized {
      if(!initialized) {
          try {
            initialized = true
            ....
```

https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/DriverDataSource.scala#L52

**Comment by mustajarvi** [comment]
Decided to fix and create a PR.

https://github.com/slick/slick/pull/1401

**Comment by nu11ptr** [comment]
Is there a simple workaround until the pull request is merged and released? I've tried a 'same thread' executor and single thread executor and both yield the same NPE and stack trace.

**Comment by mustajarvi** [comment]
If you do something alone the lines of

```scala
DB.run(sql"""SELECT 1""".as[Int])
```

before the first real DB query and and wait for the above future to complete you should have a properly initialized DriverDataSource.

**Comment by reid-spencer** [comment]
:+1: This is biting me too.

**Comment by nu11ptr** [comment]
Interestingly enough, after I fixed some other bugs (that I THOUGHT were unrelated) and got my tests passing again, my NPE's stopped. I always thought my code should have only tried to grab a single instance of the driver, and it seems like in my particular design, that is the case. Back on main train 3.1.1.

**Comment by yadavan88** [comment]
I  am also facing the same issue. Using Slick 3.1.1. 
I was not using connection pooling before, but once I faced this issue, I applied connection pooling using HikariCP and the issue seems to have fixed.

[Link](http://stackoverflow.com/questions/35130399/nullpointerexception-on-executing-concurrent-queries-using-slick) to my question in SO.

**Comment by gantamk** [comment]
+1

I am facing exactly same issue. the above mentioned exception is coming randomly if there are concurrent calls.

Any help would be appreciated.

**Comment by szeiger** [comment]
Fixed in #1445

**Comment by gantamk** [comment]
Thanks Stefan

**Comment by szeiger** [comment]
BTW, here's a simple work-around:

```
  // Obtaining a Database, for example:
  val dc = DatabaseConfig.for...
  val db = dc.database

  // Force initialization here to work around #1400:
  val session = db.createSession()
  try session.force() finally session.close()
```

**Comment by jrglee** [comment]
Is there a release `3.1.2` coming in a near future? I am building a Play 2.5 demo app and I was surprised to face this bug with a minimum setup (slick and slick evolution only). I believe other people starting a new project today now will face this issue too.
