### ISSUE TITLE
Datetime de-serialisation fails with "2015-12-24 14:46:01.949" is too short since 3.1.1

### ISSUE THREAD

**Issue by jheijkoop** [slick/slick#1403]
We have a Slick + pg_slick on postgres 9.4.5 setup, where datetimes (timestamp with time zone / TIMESTAMPTZ) are deserialised to joda DateTime. The `+01` timezone info seems to be lost in one of the steps from data in DB to construction from a string. It is present in the DB.
Our application works fine with Slick 3.1.0 and 3.0.3.

**Comment by xavier-fernandez** [comment]
PostgreSQL 'TIMESTAMPTZ' stores timestamp in UTC, it does not store timestamp offset, it only converts the input timestamp. When retrieving the timestamps from the database, PostgreSQL retrieves them on the Local Timezone.

If you want to store the offset, consider using a ISO-8601 notation, like the one from the Joda's `DateTime` class, or maybe you can use some custom PostgreSQL type, storing the timestamp and the offset: http://www.postgresql.org/docs/9.4/static/sql-createtype.html

@tminglei, maybe you would like to take a look to this issue.

**Comment by tminglei** [comment]
As the [comment](https://github.com/tminglei/slick-pg/issues/220#issuecomment-158031094) said, the time zone info was lost when retrieving timestamptz from DB.

**Comment by jheijkoop** [comment]
I happy to provide more info if you can give me some pointers where to find it. This is the full stack trace if that help:
```
java.lang.IllegalArgumentException: Invalid format: "2015-12-26 22:17:25.152" is too short
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[joda-time-2.9.1.jar:2.9.1]
        at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.9.1.jar:2.9.1]
        at com.github.tminglei.slickpg.PgDateSupportJoda$JodaDateTimeImplicits$$anonfun$8.apply(PgDateSupportJoda.scala:40) ~[slick-pg_joda-time_2.11-0.10.2.jar:0.10.2]
        at com.github.tminglei.slickpg.PgDateSupportJoda$JodaDateTimeImplicits$$anonfun$8.apply(PgDateSupportJoda.scala:40) ~[slick-pg_joda-time_2.11-0.10.2.jar:0.10.2]
        at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.getValue(PgCommonJdbcTypes.scala:24) ~[slick-pg_core_2.11-0.10.2.jar:0.10.2]
        at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:26) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24) ~[slick_2.11-3.1.1.jar:na]
        at slick.relational.ProductResultConverter.read(ResultConverter.scala:56) ~[slick_2.11-3.1.1.jar:na]
        at slick.relational.ProductResultConverter.read(ResultConverter.scala:46) ~[slick_2.11-3.1.1.jar:na]
        at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:136) ~[slick_2.11-3.1.1.jar:na]
        at slick.driver.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:37) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:67) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176) ~[slick_2.11-3.1.1.jar:na]
        at slick.util.ReadAheadIterator$class.slick$util$ReadAheadIterator$$update(ReadAheadIterator.scala:34) ~[slick_2.11-3.1.1.jar:na]
        at slick.util.ReadAheadIterator$class.hasNext(ReadAheadIterator.scala:40) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167) ~[slick_2.11-3.1.1.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:na]
        at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.Invoker$class.foreach(Invoker.scala:49) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.Invoker$class.firstOption(Invoker.scala:24) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:57) ~[slick_2.11-3.1.1.jar:na]
        at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:56) ~[slick_2.11-3.1.1.jar:na]
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[slick_2.11-3.1.1.jar:na]
        at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[slick_2.11-3.1.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
```

**Comment by jheijkoop** [comment]
the column definition is `column[DateTime]("time_created", O.PrimaryKey)` and is part of a composed primary key. The postgres defintion is `time_created TIMESTAMPTZ NOT NULL`

**Comment by tminglei** [comment]
Which version of postgres JDBC driver did you use?
If you use a version of `9.4-1201-jdbc41` or before, it should work.

Another way to avoid the exception is [here](https://github.com/tminglei/slick-pg/issues/220#issuecomment-160780444).


_Note: the time zone info is still lost, the purpose of what I do is just to prevent your program from crashing._

**Comment by jheijkoop** [comment]
Current version we have is `9.4-1202-jdbc42`.
Thanks for the work around, but I'm not sure it is the right thing for us: our application runs on AWS in multiple data centres across the globe. We might have to deal with different timezones. 
Do you know if the the error silently ignored in with slick `>3.1.1` or might they have introduced a regression with the latests version?

**Comment by jheijkoop** [comment]
With `9.4-1201-jdbc41` and slick `3.1.1` the error does not seem to occur

**Comment by xavier-fernandez** [comment]
Hi @jheijkoop. If you want to store the timezones, you need to store the time using some ISO-8601 convention, for example: `2015-12-27T23:19:58.456+01:00`.

Current slick-pg implementation uses the PostgreSQL 'TIMESTAMPTZ' data type, which stores the time as UTC time, it does not store the timezone, that problem will pop on any Slick version.

The PR #1349 implements the Java8 time classes without losing any type of capabilities, offset is persisted because offset dates are stored as ISO strings. you can overload the `DateTime` implementation to this one in your database connection:

```scala
override val dateTimeType = new DateTimeJdbcType

class DateTimeJdbcType extends DriverJdbcType[DateTime] {
     override def sqlType : Int = {
       /**
         * Stores the [[DateTime]] as a 'VARCHAR' in databases with no specific
         * 'TIMESTAMP WITH OFFSET' implementations, like SQLite. It's implemented in this
         * way because almost any database support 'TIMESTAMP WITH OFFSET' by default,
         * and the ones supporting it do not have an standardized implementation.
         *
         * A persisted value would be '2015-10-01T12:57:20.293+02:00'.
         */
       java.sql.Types.VARCHAR
     }
     override def setValue(v: OffsetDateTime, p: PreparedStatement, idx: Int): Unit = {
       p.setString(idx, v.toString)
     }
     override def getValue(r: ResultSet, idx: Int): OffsetDateTime = {
       r.getString(idx) match {
         case null => null
         case iso8601String : String => OffsetDateTime.parse(iso8601String)
       }
     }
     override def updateValue(v: OffsetDateTime, r: ResultSet, idx: Int): Unit = {
       r.updateString(idx, v.toString)
     }
     override def valueToSQLLiteral(value: OffsetDateTime) = {
       s"'${value.toString}'"
     }
 }
```

**Comment by jheijkoop** [comment]
Thnx, the bug is still there, but we have work-around with slick-pg-0.10.2 when downgrading the postgres driver to `9.4-1201-jdbc41`. Though we are clearly expecting `TIMESTAMPTZ` to something it does not do. We will migrate to a different column type in the near future

**Comment by jheijkoop** [comment]
Closing, because it is not a Slick, but postgres driver bug and a workaround is provided with older `9.4-1201-jdbc41` postgres driver plus slick-pg `0.10.2`

**Comment by jheijkoop** [comment]
Closing, because it is not a Slick, but postgres driver bug and a workaround is provided with older `9.4-1201-jdbc41` postgres driver plus slick-pg `0.10.2`
