### ISSUE TITLE
Slick codegen does not postgresql's text type

### ISSUE THREAD

**Issue by mootech** [slick/slick#1420]
get the following error msg.
[error](run-main-3) slick.SlickException: Could not parse default value Some('active'::text) for column test_case.active of type String, meta data: MColumn(MQName(public.test_case),active,12,text,Some(2147483647),Some(0),10,Some(false),None,Some('active'::text),2147483647,9,Some(false),None,None,Some(false))
slick.SlickException: Could not parse default value Some('active'::text) for column test_case.active of type String, meta data: MColumn(MQName(public.test_case),active,12,text,Some(2147483647),Some(0),10,Some(false),None,Some('active'::text),2147483647,9,Some(false),None,None,Some(false))
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:270)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:279)
    at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:161)
    at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:161)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
    at scala.collection.Iterator$class.foreach(Iterator.scala:750)

Changed to varchar after reading the code and solves the problem.

**Comment by mootech** [comment]
a mistake. Acutally removed the default text value fixed the problem

**Comment by stewSquared** [comment]
@mootech What do you mean you made a mistake? There's nothing wrong with having a column of text default to an empty string. This doesn't look like your mistake.
