### ISSUE TITLE
"Invalid UUID string: uuid_generate_v4()" when using codegen with Postgres UUID primary key

### ISSUE THREAD

**Issue by rf-** [slick/slick#1432]
With Slick 3.1.1, running codegen on the following table:

``` sql
CREATE TABLE applications (
  id uuid DEFAULT uuid_generate_v4() NOT NULL,
  CONSTRAINT applications_pkey PRIMARY KEY (id)
);
```

Gives the following exception and backtrace:

```
java.lang.IllegalArgumentException: Invalid UUID string: uuid_generate_v4()
	at java.util.UUID.fromString(UUID.java:194)
	at slick.driver.PostgresDriver$ModelBuilder$$anon$2$$anonfun$default$1.applyOrElse(PostgresDriver.scala:77)
	at slick.driver.PostgresDriver$ModelBuilder$$anon$2$$anonfun$default$1.applyOrElse(PostgresDriver.scala:67)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at scala.Option.collect(Option.scala:282)
	at slick.driver.PostgresDriver$ModelBuilder$$anon$2.default(PostgresDriver.scala:67)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:252)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:252)
	at scala.Option.getOrElse(Option.scala:121)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:251)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:261)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:279)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:161)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:161)
...
```

Relevant code:

``` scala
    override def createColumnBuilder(tableBuilder: TableBuilder, meta: MColumn): ColumnBuilder = new ColumnBuilder(tableBuilder, meta) {
      // ...
      override def default = meta.columnDef.map((_,tpe)).collect{
        // ...
        case (v,"java.util.UUID") => {
          val uuid = v.replaceAll("[\'\"]", "") //strip quotes
                      .stripSuffix("::uuid") //strip suffix
          Some(Some(java.util.UUID.fromString(uuid)))
        }
      }
```

This is fine for the case where a column has a specific UUID as its default value, but fails when the default is a function.

**Comment by cvogt** [comment]
As a workaround, you can ignore invalid default values in the code generator. The place to do this is shown in this PR (and ignoring is on by default from Slick 3.2 forward): https://github.com/slick/slick/pull/1430

**Comment by cvogt** [comment]
There already is a feature to add support for this https://github.com/slick/slick/issues/214 so I am closing this as a duplicate.

**Comment by rf-** [comment]
Cool, thanks.

**Comment by rf-** [comment]
Sorry, I tried switching to 3.2.0-SNAPSHOT and specifying `ignoreInvalidDefaults = true`, but I'm still getting basically the same error:

```
java.lang.IllegalArgumentException: Invalid UUID string: uuid_generate_v4()
	at java.util.UUID.fromString(UUID.java:194)
	at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2$$anonfun$default$1.applyOrElse(PostgresProfile.scala:78)
	at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2$$anonfun$default$1.applyOrElse(PostgresProfile.scala:68)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at scala.Option.collect(Option.scala:282)
	at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2.default(PostgresProfile.scala:68)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
	at scala.Option.getOrElse(Option.scala:121)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:253)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:263)
	at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:281)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
```

I added a `println` to confirm that it's running the correct version of the code and that the `ignoreInvalidDefaults` field of the ModelBuilder is getting set to `true`.

**Comment by rf-** [comment]
Hi @cvogt, just wanted to make sure you saw my previous comment. It looks to me like there's still a bug in the behavior of `ignoreInvalidDefaults` in 3.2.

**Comment by cvogt** [comment]
mh, maybe we should catch the exception and suppress it if ignoreInvalidDefaults is true.

here: https://github.com/slick/slick/blob/3b3bd36c93c6d9c63b0471ff4d8409f913954b2b/slick/src/main/scala/slick/jdbc/JdbcModelBuilder.scala#L254 
or here:
https://github.com/slick/slick/blob/3b3bd36c93c6d9c63b0471ff4d8409f913954b2b/slick/src/main/scala/slick/jdbc/PostgresProfile.scala#L68

@rf-  you want to give it a try?

**Comment by cvogt** [comment]
Probably putting it in the first place and ignoring IllegalArgumentException is fine. Hope that's not too intrusive.

**Comment by Deliganli** [comment]
after my last migration codegen suddenly didn't give any output. But there was no error on the console, it was succeeding.

it appears that this piece of code caused this and yes, ignoreInvalidDefaults was set true.

```
alter table myTable
  add column myId UUID not null constraint fk_myTable_myOtherTable references myOtherTable default '00000000-0000-0000-0000-000000000000';
```
after dropping the default value it started working 

was very hard for me to realize that since there was no indicator.
I am not sure if this behaviour is related with pg_slick library for postgres or slick-codegen
