### ISSUE TITLE
Python3 - unable to generate docs locally

### ISSUE THREAD

**Issue by Sumith1896** [slick/slick#1435]
I am new to sbt so this might not be bug and may be a mistake from my side.
```
[trace] Stack trace suppressed: run last slick/sphinx:generateHtml for the full output.
[error] (slick/sphinx:generateHtml) Failed to build Sphinx html documentation.
[error] Total time: 318 s, completed Feb 8, 2016 3:09:09 PM
> last slick/sphinx:generateHtml
[info] Generating Sphinx html documentation...
[debug] Command: sphinx-build -a -E -b html -d /home/sumith1896/github/slick/slick/slick/target/sphinx/doctrees/html /home/sumith1896/github/slick/slick/slick/src/sphinx /home/sumith1896/github/slick/slick/slick/target/sphinx/html
[debug] Environment: Map(PYTHONPATH -> , version -> 3.2, release -> 3.2.0-SNAPSHOT, slick_extensions_version -> 3.2.0-SNAPSHOT)
[debug] Running Sphinx v1.3.5
[debug] making output directory...
[debug] 
[debug] Exception occurred:
[debug]   File "/home/sumith1896/github/slick/slick/slick/src/sphinx/exts/apilinks.py", line 34, in setup_link_roles
[debug]     for name, base_url in app.config.apilinks.iteritems():
[debug] AttributeError: 'dict' object has no attribute 'iteritems'
[debug] The full traceback has been saved in /tmp/sphinx-err-f94wvnta.log, if you want to report the issue to the developers.
[debug] Please also report this if it was a user error, so that a better error message can be provided next time.
[debug] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
java.lang.RuntimeException: Failed to build Sphinx html documentation.
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.sbt.sphinx.CommandLineSphinxRunner$$anonfun$1.apply(SphinxRunner.scala:120)
	at com.typesafe.sbt.sphinx.CommandLineSphinxRunner$$anonfun$1.apply(SphinxRunner.scala:104)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at com.typesafe.sbt.sphinx.CommandLineSphinxRunner.sphinxBuild(SphinxRunner.scala:126)
	at com.typesafe.sbt.sphinx.CommandLineSphinxRunner.generateHtml(SphinxRunner.scala:58)
	at com.typesafe.sbt.site.SphinxSupport$$anonfun$generateHtmlTask$1.apply(SphinxSupport.scala:88)
	at com.typesafe.sbt.site.SphinxSupport$$anonfun$generateHtmlTask$1.apply(SphinxSupport.scala:83)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (slick/sphinx:generateHtml) Failed to build Sphinx html documentation.
> 
```

**Comment by d6y** [comment]
Discussion at: https://gitter.im/slick/slick?at=56b86296d09b3b1c4dda3ddc

**Comment by Sumith1896** [comment]
Thanks to @d6y. The issue is only when the default Python version is 3.

**Comment by cvogt** [comment]
Is there a way we can print an error message that people should be using Python 2 instead of just a crazy exception? Maybe put an assertion into the conf.py or something?

**Comment by Sumith1896** [comment]
Yes. That would serve a temporary fix.

**Comment by Sumith1896** [comment]
Trying to raise an error for Python 3 on the first line of conf.py still results in this stacktrace.
I speculate it's happening sometime before. I'm not very comfortable with sbt, can you direct me to the relevant code?

**Comment by cvogt** [comment]
so the sbt plugin we use is https://github.com/sbt/sbt-site/ which in turn uses sphinx to compile the html pages. This sounds like something that sphinx would have to address really. Maybe you can check if it still happens with the latest sphinx version. Googling the for error message in the stack trace `'dict' object has no attribute 'iteritems'` turns up http://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems-when-trying-to-use-networkx which clearly hints to this being a python 2 vs. 3 issue. So I wouldn't be too concerned about this on our side I think. Closing this for now.
