### ISSUE TITLE
Hello Slick! (Slick 3.1) activator template does not work

### ISSUE THREAD

**Issue by intracer** [slick/slick#1451]
https://www.lightbend.com/activator/template/hello-slick-3.1

Similiar issue reported here https://github.com/typesafehub/activator/issues/1036 long ago, but no one cares. Maybe Slick maintaners care that the template metioned in http://slick.typesafe.com/doc/3.1.1/gettingstarted.html  - "To learn the basics of Slick, start with the Hello Slick template" does not work out of the box?

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#sbt-fork-run-protocol_2.10;2.3.8: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:sbt-fork-run-protocol_2.10:2.3.8
[warn] 		  +- com.typesafe.play:sbt-fork-run-plugin:2.3.8 (scalaVersion=2.10, sbtVersion=0.13) (/home/ilya/wm/finance/hello-slick-3.1/project/play-fork-run.sbt#L3-4)
[warn] 		  +- default:hello-slick-3-1-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-fork-run-protocol_2.10;2.3.8: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
	at sbt.IvySbt.withIvy(Ivy.scala:123)
	at sbt.IvySbt.withIvy(Ivy.scala:120)
	at sbt.IvySbt$Module.withModule(Ivy.scala:151)
	at sbt.IvyActions$.updateEither(IvyActions.scala:157)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-fork-run-protocol_2.10;2.3.8: not found

**Comment by szeiger** [comment]
Does it work now with https://github.com/typesafehub/activator-hello-slick/pull/21?

**Comment by Vistritium** [comment]
+1, Still doesn't work :( and examples from site doesn't compile too, can't learn slick

**Comment by cvogt** [comment]
@szeiger still a problem. replicated the issue here: https://github.com/typesafehub/activator-hello-slick/issues/25

**Comment by cvogt** [comment]
PR for fix is open https://github.com/typesafehub/activator-hello-slick/pull/28
