### ISSUE TITLE
Simple groupBy cannot be converted to SQL

### ISSUE THREAD

**Issue by ksilin** [slick/slick#1453]
Slick 3.1.1

reproducible by

```
  case class TestType(id: Option[Int], name: String)

  class TestTable(tag: Tag) extends Table[TestType](tag, "test") {

    def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
    def name = column[String]("name")
    def * = (id.?, name) <>(TestType.tupled, TestType.unapply)
  }
  val testTable = TableQuery[TestTable]

  db.run(testTable.groupBy(_.id).result)
  db.run(testTable.groupBy(_.name).result)
```

Both actions result in a `SlickTreeException`. 

Stack trace for the `_name` query:
```
Cannot convert node to SQL Comprehension
| Path s9._2 : Vector[t12<{s14: String'}>]

slick.SlickTreeException: Cannot convert node to SQL Comprehension
| Path s9._2 : Vector[t12<{s14: String'}>]

	at slick.compiler.MergeToComprehensions$$anonfun$26.apply(MergeToComprehensions.scala:167)
	at slick.compiler.MergeToComprehensions$$anonfun$26.apply(MergeToComprehensions.scala:167)
	at scala.Option.getOrElse(Option.scala:121)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertBase$1(MergeToComprehensions.scala:167)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:161)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:161)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeFilterWhere$1(MergeToComprehensions.scala:161)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeGroupBy$1(MergeToComprehensions.scala:156)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$10.apply(MergeToComprehensions.scala:96)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeSortBy$1(MergeToComprehensions.scala:96)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:344)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createTopLevel$1(MergeToComprehensions.scala:253)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:269)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convert1$1$6.apply(MergeToComprehensions.scala:280)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convert1$1$6.apply(MergeToComprehensions.scala:280)
	at slick.util.ConstArray.endoMap(ConstArray.scala:122)
	at slick.ast.Node$class.mapChildren(Node.scala:51)
	at slick.ast.StructNode.mapChildren(Node.scala:151)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:280)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1(MergeToComprehensions.scala:286)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:285)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:285)
	at slick.ast.UnaryNode$class.mapChildren(Node.scala:224)
	at slick.ast.Pure.mapChildren(Node.scala:243)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1(MergeToComprehensions.scala:285)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:285)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:285)
	at slick.util.ConstArray.endoMap(ConstArray.scala:122)
	at slick.ast.Node$class.mapChildren(Node.scala:51)
	at slick.ast.Comprehension.mapChildren(Comprehension.scala:8)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1(MergeToComprehensions.scala:285)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:269)
	at slick.compiler.MergeToComprehensions.convert(MergeToComprehensions.scala:289)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1$$anonfun$15.apply(MergeToComprehensions.scala:29)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1$$anonfun$15.apply(MergeToComprehensions.scala:28)
	at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:24)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1.apply(MergeToComprehensions.scala:28)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1.apply(MergeToComprehensions.scala:28)
	at slick.compiler.CompilerState.map(QueryCompiler.scala:226)
	at slick.compiler.MergeToComprehensions.apply(MergeToComprehensions.scala:28)
	at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:79)
	at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:78)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at slick.ast.SymbolNamer.use(Symbol.scala:112)
	at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
	at slick.compiler.QueryCompiler$$anonfun$3.apply(QueryCompiler.scala:65)
	at slick.compiler.QueryCompiler$$anonfun$3.apply(QueryCompiler.scala:63)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1194)
	at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:63)
	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
	at slick.profile.BasicProfile$API$class.streamableQueryActionExtensionMethods(BasicProfile.scala:54)
	at slick.driver.JdbcProfile$$anon$1.streamableQueryActionExtensionMethods(JdbcProfile.scala:69)
	at com.example.data.GroupBySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(GroupBySpec.scala:44)
	at com.example.data.GroupBySpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(GroupBySpec.scala:44)
	at org.scalatest.AsyncSuite$$anonfun$transformToOutcome$1.apply(AsyncSuite.scala:214)
	at org.scalatest.AsyncSuite$$anonfun$transformToOutcome$1.apply(AsyncSuite.scala:213)
	at org.scalatest.AsyncFunSpecLike$$anon$1.apply(AsyncFunSpecLike.scala:458)
	at org.scalatest.AsyncSuite$class.withAsyncFixture(AsyncSuite.scala:294)
	at org.scalatest.AsyncFunSpec.withAsyncFixture(AsyncFunSpec.scala:2268)
	at org.scalatest.AsyncFunSpecLike$class.invokeWithAsyncFixture$1(AsyncFunSpecLike.scala:455)
	at org.scalatest.AsyncFunSpecLike$$anonfun$runTest$1.apply(AsyncFunSpecLike.scala:468)
	at org.scalatest.AsyncFunSpecLike$$anonfun$runTest$1.apply(AsyncFunSpecLike.scala:468)
	at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:294)
	at org.scalatest.AsyncFunSpecLike$class.runTest(AsyncFunSpecLike.scala:468)
	at org.scalatest.AsyncFunSpec.runTest(AsyncFunSpec.scala:2268)
	at org.scalatest.AsyncFunSpecLike$$anonfun$runTests$1.apply(AsyncFunSpecLike.scala:501)
	at org.scalatest.AsyncFunSpecLike$$anonfun$runTests$1.apply(AsyncFunSpecLike.scala:501)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:434)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:420)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:420)
	at org.scalatest.AsyncSuperEngine.org$scalatest$AsyncSuperEngine$$runTestsInBranch(AsyncEngine.scala:410)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:454)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:420)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:420)
	at org.scalatest.AsyncSuperEngine.org$scalatest$AsyncSuperEngine$$runTestsInBranch(AsyncEngine.scala:416)
	at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:522)
	at org.scalatest.AsyncFunSpecLike$class.runTests(AsyncFunSpecLike.scala:501)
	at org.scalatest.AsyncFunSpec.runTests(AsyncFunSpec.scala:2268)
	at org.scalatest.Suite$class.run(Suite.scala:1320)
	at org.scalatest.AsyncFunSpec.org$scalatest$AsyncFunSpecLike$$super$run(AsyncFunSpec.scala:2268)
	at org.scalatest.AsyncFunSpecLike$$anonfun$run$1.apply(AsyncFunSpecLike.scala:505)
	at org.scalatest.AsyncFunSpecLike$$anonfun$run$1.apply(AsyncFunSpecLike.scala:505)
	at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:592)
	at org.scalatest.AsyncFunSpecLike$class.run(AsyncFunSpecLike.scala:505)
	at com.example.data.SpecBase.org$scalatest$BeforeAndAfterAll$$super$run(SpecBase.scala:8)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at com.example.data.SpecBase.run(SpecBase.scala:8)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:46)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
```

Not sure how this relates to #1355 since #1355 reports `groupBy` without `length` not to produce any issues

**Comment by djx314** [comment]
the result of query
```scala
testTable.groupBy(_.name)
```
has a query property, slick can't shape a query, you must use a map to make the result to the simple data.
<http://slick.typesafe.com/doc/3.1.1/sql-to-slick.html#group-by>

**Comment by ksilin** [comment]
Ah, my bad. RTFM strikes again. Sorry for the inconvenience :flushed:
