### ISSUE TITLE
There is no mapping for Postgres Timestamp with time zone 

### ISSUE THREAD

**Issue by ximagination80** [slick/slick#1463]
I want to use slick reverse engineering tool. In the moment when I ran slick reverse eng. tool with my postgres schema I got next exception:

Caused by: scala.MatchError: ('2016-03-17 16:15:07.899+02'::timestamp with time zone,java.sql.Timestamp) (of class scala.Tuple2)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$default$1.apply(JdbcModelBuilder.scala:215)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$default$1.apply(JdbcModelBuilder.scala:212)
        at scala.Option.map(Option.scala:146)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.default(JdbcModelBuilder.scala:212)

As I can see from this reference 
https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/JdbcModelBuilder.scala
slick doesn't support Postgres TimeStamp with time zone feature. Am I right?

**Comment by djx314** [comment]
Have a try with <https://github.com/tminglei/slick-pg> ?

**Comment by ximagination80** [comment]
Thanks a lot! I belived that 
http://slick.typesafe.com/doc/3.1.1/code-generation.html 
works properly for postgres

**Comment by cvogt** [comment]
@ximagination80 slick-pg has additional types slick's main code generator does not use.

You can customize the code generator and model builder to handle this case properly and generate the type you like. It's not hard actually. This gets you half of the way there: https://github.com/slick/slick-codegen-customization-example/tree/3.1.0

**Comment by cvogt** [comment]
built-in we should at least not fail on this. assigning it to the revamp milestone

**Comment by ximagination80** [comment]
Yes, thanks. I have already used @djx314 example of code gen :+1:

**Comment by cvogt** [comment]
let's keep it open, so we can at least take care of the failure when we get to it

**Comment by ximagination80** [comment]
Ok

**Comment by cvogt** [comment]
Let's write a test for this
