### ISSUE TITLE
Support for function-based indexes

### ISSUE THREAD

**Issue by Pyppe** [slick/slick#148]
It would make sense to support function-based indexes. For example, a lower-case index:

``` scala
def word = column[String]("word")
def wordIndex = index("dictionary_word_lower_idx", word.toLowerCase)
```

With Slick 1.0 this compiles, but throws an exception at runtime:

```
scala.slick.SlickException: Cannot use column Apply Function lcase in index (only named columns are allowed)
    at scala.slick.driver.BasicStatementBuilderComponent$TableDDLBuilder$$anonfun$addColumnList$1.apply(BasicStatementBuilderComponent.scala:561)
    at scala.slick.driver.BasicStatementBuilderComponent$TableDDLBuilder$$anonfun$addColumnList$1.apply(BasicStatementBuilderComponent.scala:554)
```

Original discussion: https://groups.google.com/forum/?fromgroups=#!topic/scalaquery/tGdyddJWKWw

**Comment by Mast3rPlan** [comment]
:+1:

**Comment by romansky** [comment]
:+1:

**Comment by ejisan** [comment]
👍

**Comment by XoJIoD89** [comment]
Move this from Future to Present please :)

**Comment by Daenyth** [comment]
Is there a clear path to implementing this? I might be able to find some time to work on it since it appears the main contributors don't see it as a priority, but I don't know much of anything about internals so I'd need some guidance
