### ISSUE TITLE
Slick throws if Scala model class does not include the `id` field

### ISSUE THREAD

**Issue by yln** [slick/slick#1506]
Slick version: 3.1.0
Is it possible to avoid including an `id` field in Scala model classes, but still having an auto-generated `id` column in the table?

Setup:
```scala
case class Product(name: String, desc: String)

class ProductTable(tag: Tag) extends Table[Product](tag, "product") {
  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def name = column[String]("name")
  def desc = column[String]("desc")

  def * = (name, desc) <> (Product.tupled, Product.unapply)
}

val products = TableQuery[ProductTable]

// Throws (see blow)
def insert(p: Product): Future[Long] = db.run {
  products.returning(products.map(_.id)) += p
}

// Works as expected
def insert2(p: Product): Future[Unit] = db.run {
  (products += p).map(_ => ())
}
```
Usage:
```scala
val id = Await.result(userRepo.insert(p), Duration.Inf)
//Caused by: java.util.NoSuchElementException: Invoker.first
//  at slick.jdbc.Invoker$class.first(Invoker.scala:34)
//  at slick.jdbc.ResultSetInvoker.first(ResultSetInvoker.scala:14)
//  at slick.driver.JdbcActionComponent$ReturningInsertActionComposerImpl.retOne(JdbcActionComponent.scala:638)
//  at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:508)
//  at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:504)
//  at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:354)
//  at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:407)
//  at slick.driver.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:636)
//  at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504)
//  at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
```
If I change the model to include the `id` (and adapt the `* <>` mapping) it works.
```scala
case class Product(id: Option[Long], name: String, desc: String)
```

**Comment by jcranky** [comment]
Not sure if related, but I have a similar problem. A normal insert works. If I change it to something like `users returning users`, I the `java.util.NoSuchElementException: Invoker.first` error. And I don't have an `id` field, neither in the model, nor in the database.

**Comment by MattRMcFarland** [comment]
I'm using Slick 3.0 and seeing the same error. Why is this happening? Is there a best-practice work-around until a fix is introduced?

**Comment by djx314** [comment]
I think the problem is
```scala
def * = (name, desc) <> (Product.tupled, Product.unapply)
```
slick can't find the id field in your table, so it throw the error. It likes the error when use
```scala
products.returning(products.map(_ => ())) += p
```
So use
```scala
case class Product(id: Option[Long], name: String, desc: String)

class ProductTable(tag: Tag) extends Table[Product](tag, "product") {
  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def name = column[String]("name")
  def desc = column[String]("desc")

  def * = (id.?, name, desc) <> (Product.tupled, Product.unapply)
}
```
is OK. I think it not a bug.
But @cvogt when I write a wrap in slick, some times it will throw this error, and the terrible thing is no any error message. Is it possible to add a friendly error message when `returning` method returning a empty column?

**Comment by cvogt** [comment]
> I think it not a bug.

I think it can be considered a bug or missing feature. Workaround is including the id.

> But @cvogt when I write a wrap in slick, some times it will throw this error, and the terrible thing is there is no any error message. Is it possible to add a friendly error message when returning method autally returning a empty column?

I am not sure what you are talking about exactly. Sounds like a separate issue. Maybe create a ticket with an example?

**Comment by charlescapps** [comment]
I'm getting this error for an identical query as the author of this post, when we _did_ include the `id` field in our case class. We have an analogous schema with `O.PrimaryKey` and `O.AutoInc`. 

The strange thing is that this seems to work most of the time, but last night for PagerDuty this was failing with the same error:
```
//Caused by: java.util.NoSuchElementException: Invoker.first
//  at slick.jdbc.Invoker$class.first(Invoker.scala:34)
```

**Comment by djx314** [comment]
@yln @charlescapps @cvogt 
Juse a workaround, use the code to show and hope for solving the problem:
```scala
case class Friends2(name: String, nick: String, age: Int)

class FriendTable2(tag: slick.lifted.Tag) extends Table[Friends2](tag, "firend2") with SlickMapper {
  def id   = column[Long]("id", O.AutoInc)
  def name = column[String]("name")
  def nick = column[String]("nick")
  def age  = column[Int]("age")

  def oldMapper = (name, nick, age).<>(Friends2.tupled, Friends2.unapply)

  override def * : ProvenShape[Friends2] =
    (oldMapper, id.?).<>[Friends2](f = { s =>
      s._1
    }, g = { r =>
      Option((r, Option.empty))
    })
}

val friend1 = Friends2(faker.name.name, faker.weather.description, 23)
val friend2 = Friends2(faker.name.name, faker.weather.description, 26)
val friend3 = Friends2(faker.name.name, faker.weather.description, 20)

val insert = friendTq2.returning(friendTq2.map(_.id))

val friend1DBIO = insert += friend1
val friend2DBIO = insert += friend2
val friend3DBIO = insert += friend3

println(await(db.run(DBIO.sequence(List(friend1DBIO, friend2DBIO, friend3DBIO)))))  //println List(1, 2, 3)
```

**Comment by djx314** [comment]
I am not sure if this change will bring any other problem in update action. Since model without id field is so danger.

**Comment by nsadeh** [comment]
> ```scala
> override def * : ProvenShape[Friends2] =
>     (oldMapper, id.?).<>[Friends2](f = { s =>
>       s._1
>     }, g = { r =>
>       Option((r, Option.empty))
>     })
> ```

@djx314 does this need the SlickMapper dependency?

**Comment by djx314** [comment]
> 
> 
> > ```scala
> > override def * : ProvenShape[Friends2] =
> >     (oldMapper, id.?).<>[Friends2](f = { s =>
> >       s._1
> >     }, g = { r =>
> >       Option((r, Option.empty))
> >     })
> > ```
> 
> @djx314 does this need the SlickMapper dependency?

Just common slick api.

**Comment by nsadeh** [comment]
Hm @djx314 this didn't work for me getting the same error still.

**Comment by djx314** [comment]
What's driver are you using? I wish have a try.

**Comment by nsadeh** [comment]
Here is my config for Postgres:

```
db = {
  connectionPool = "HikariCP" //use HikariCP for our connection pool
  dataSourceClass = "org.postgresql.ds.PGSimpleDataSource" //Simple datasource with no connection pooling. The connection pool has already been specified with HikariCP.
  properties = {
    serverName = "localhost"
    portNumber = "5432"
    databaseName = "postgres"
    # user = "postgres"
    # password = "postgres"
  }
  numThreads = 10
}
```

**Comment by nsadeh** [comment]
@djx314 turns out I had a small typo in a function composed with my query that caused an unrelated but very similar error (Caused by: java.util.NoSuchElementException: None.get). It works quite well, thanks.

**Comment by djx314** [comment]
@nsadeh Thanks, I went my New Year holiday and want to have a test tody. No problem is the best.
