### ISSUE TITLE
NullPointerException when opening 2 concurrent connections

### ISSUE THREAD

**Issue by LirazRom** [slick/slick#1511]
I am using Slick 3.3.1 with Mysql Driver
this is the configuration
lazy val config = ConfigFactory.parseString(
    s"""
       |slick.dbs.default {
       |    driver = "slick.driver.MySQLDriver$$"
       |    db {
       |      url = "jdbc:mysql://localhost:${OCCMProperties.mySqlPort}/oncloud"
       |      driver = com.mysql.jdbc.Driver
       |      user = root
       |      password = ${OCCMProperties.mySqlPassword}
       |      connectionPool = disabled
       |    }
       |}
       |
    """.stripMargin

when two objects tries to insert entry into the db - into the same table , I get exception
java.lang.NullPointerException
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:98)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:64)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareInsertStatement(JdbcBackend.scala:312)
	at slick.jdbc.JdbcBackend$BaseSession.prepareInsertStatement(JdbcBackend.scala:407)
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:353)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:407)
	at slick.driver.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:636)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.nativeUpsert(JdbcActionComponent.scala:557)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.f$1(JdbcActionComponent.scala:540)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.run(JdbcActionComponent.scala:553)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32)
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by rktechie** [comment]
Did you resolve this?

**Comment by hvesalai** [comment]
@rktechie can you reproduce this?
