### ISSUE TITLE
SQlite typepattern cant match BIGDECIMAL with precision

### ISSUE THREAD

**Issue by trevorsibanda** [slick/slick#1550]
Run code generator on the following produces a match error in SQLiteProfile.scala 
```sql
CREATE TABLE "DEC"("ID" INT NOT NULL , "W" DECIMAL(16,8) NOT NULL DEFAULT 0.00 );
```

```scala
[info] Running slick.test.codegen.GenerateMainSources /home/trevor/git/slick/slick-testkit/target/scala-2.11/src_managed/test/slick-codegen
scala.MatchError: DECIMAL(16,8) (of class java.lang.String)
	at slick.jdbc.SQLiteProfile$ModelBuilder$$anon$1.<init>(SQLiteProfile.scala:101)
	at slick.jdbc.SQLiteProfile$ModelBuilder.createColumnBuilder(SQLiteProfile.scala:98)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:161)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:96)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:93)
	at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
	at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
	at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
	at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

The issue seems to be here [https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/SQLiteProfile.scala#L100](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/SQLiteProfile.scala#L100)

**Comment by hvesalai** [comment]
see #1624
