### ISSUE TITLE
getColumns leads to ClassCastException

### ISSUE THREAD

**Issue by borschet** [slick/slick#1566]
code-Generation from sbt leads to a ClassCastException when generating code for a SQLServer DB.

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getInt(SQLServerResultSet.java:2315)
        at slick.jdbc.PositionedResult.nextIntOption(PositionedResult.scala:62)
        at slick.jdbc.GetResult$GetIntOption$.apply(GetResult.scala:39)
        at slick.jdbc.GetResult$GetIntOption$.apply(GetResult.scala:39)
        at slick.jdbc.PositionedResult.$less$less(PositionedResult.scala:31)
        at slick.jdbc.PositionedResult.$less$less$qmark(PositionedResult.scala:32)
        at slick.jdbc.meta.MColumn$$anonfun$getColumns$2.apply(MColumn.scala:27)
        at slick.jdbc.meta.MColumn$$anonfun$getColumns$2.apply(MColumn.scala:20)
        at slick.jdbc.ResultSetInvoker$$anon$4.extractValue(ResultSetInvoker.scala:37)
        at slick.jdbc.ResultSetInvoker$$anon$2.extractValue(ResultSetInvoker.scala:26)
        at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
        at slick.util.ReadAheadIterator$class.slick$util$ReadAheadIterator$$update(ReadAheadIterator.scala:34)
        at slick.util.ReadAheadIterator$class.hasNext(ReadAheadIterator.scala:40)
        at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
        at slick.jdbc.Invoker$class.foreach(Invoker.scala:49)
        at slick.jdbc.ResultSetInvoker.foreach(ResultSetInvoker.scala:14)
        at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
        at slick.jdbc.ResultSetAction$$anon$1.run(ResultSetInvoker.scala:42)
        at slick.jdbc.ResultSetAction$$anon$1.run(ResultSetInvoker.scala:42)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by cvogt** [comment]
side-note: https://github.com/slick/slick/issues/1560 should help us identify such issues

**Comment by NickMcAvoy** [comment]
Does this issue being open mean the code generation is currently not working with SQL Server databases?

**Comment by NickMcAvoy** [comment]
Still seeing this issue when using Microsoft's drivers, but not with jtds.

**Comment by trevorsibanda** [comment]
@NickMcAvoy sorry about this :(, I am assigned to this issue and will submit a fix once #1560 is merged

**Comment by NickMcAvoy** [comment]
@trevorsibanda I see #1560 references #1570 which has been merged. Does that mean this can proceed?

**Comment by nafg** [comment]
Verified fixed, so closing.

**The fix:** 4f696a53 (2017) changed the `SOURCE_DATA_TYPE` read in `MColumn.getColumns` from the typed `r.<<?[Int]` (which delegated to the driver's `getInt`, where old Microsoft sqljdbc versions threw the reported `ClassCastException: java.lang.String cannot be cast to java.lang.Integer`) to `r.nextObjectOption()`, which cannot throw regardless of what type the driver returns.

**Verification against live SQL Server 2025 + current mssql-jdbc (today):**
- Current code: `MColumn.getColumns` on a real table succeeds; `SOURCE_DATA_TYPE` values are read fine via `nextObjectOption`.
- I also temporarily reverted the fix to the pre-2017 `r.<<?[Int]` read: it **also** succeeds on the modern driver, which now returns the column as a numeric. So the original failure mode was specific to old sqljdbc driver versions (consistent with the report above that jTDS was unaffected) and is extinct in addition to being fixed defensively in Slick.

**Coverage notes for the record:** `JdbcMetaTest.testMeta` does not run on the `sqlserver-sqljdbc` profile in CI — `StandardTestDBs.SQLServerSQLJDBC` overrides `capabilities` with `profile.capabilities - JdbcCapabilities.createModel`, which (unlike the base `TestDB` definition) omits all testkit capabilities, including `test.jdbcMeta`. While investigating I also found that enabling it isn't a one-liner: `MUDT.getUDTs(MQName.local("%"))` fails on the Microsoft driver with *"An object or column name is missing or empty"* before `getColumns` is ever reached. Given the fix is structurally CCE-proof, that gap doesn't keep this issue alive, but it may interest anyone touching SQL Server test coverage.

🤖 Verified and written via [Claude Code](https://claude.com/claude-code)
