### ISSUE TITLE
Aggregate in `GroupBy` don't allow parameters

### ISSUE THREAD

**Issue by tminglei** [slick/slick#1589]
When resolving tminglei/slick-pg#289, I noticed that slick's groupBy aggregate didn't support parameters.

Use below codes can reproduce it:
```scala
import slick.ast.Library.SqlAggregateFunction
import slick.ast.{LiteralNode, TypedType}
import slick.lifted.OptionMapperDSL

/**
  * Created by tminglei on 8/8/16.
  */
object AggFuncErrorDemo {
  import slick.jdbc.PostgresProfile.api._

  val StringAgg = new SqlAggregateFunction("string_agg")

  implicit class GeneralAggQueryExtensionMethods[T: TypedType, C[_]](q: Query[Rep[T], _, C]) {
    def stringAgg[R](delimiter: String)(implicit om: OptionMapperDSL.arg[String, T]#to[String, R]) =
      om.column(StringAgg, q.toNode, LiteralNode(delimiter))
  }

  ///---

  val db = Database.forURL(url = "jdbc:postgresql://localhost/test?user=postgres", driver = "org.postgresql.Driver")

  case class Tab(name: String, count: Int, bool: Boolean, x: Double, y: Double)

  class Tabs(tag: Tag) extends Table[Tab](tag, "test_agg_tab1") {
    def name = column[String]("col2")
    def count = column[Int]("count")
    def bool = column[Boolean]("bool")
    def x = column[Double]("x")
    def y = column[Double]("y")

    def * = (name, count, bool, x, y) <> (Tab.tupled, Tab.unapply)
  }
  val tabs = TableQuery(new Tabs(_))

  ///---

  def main(args: Array[String]): Unit = {
    val sql = tabs.groupBy(_.bool).map { case (bool, group) =>
      (bool, group.map(_.name.?).stringAgg(","))
    }.result.statements.head
    println(s"sql: $sql")
  }
}
```

When running it, I got an exception:
```
Exception in thread "main" slick.SlickTreeException: Cannot convert node to SQL Comprehension
| Path s9._2 : Vector[t18<{s22: Boolean', s23: String'}>]

	at slick.compiler.MergeToComprehensions$$anonfun$26.apply(MergeToComprehensions.scala:174)
	at slick.compiler.MergeToComprehensions$$anonfun$26.apply(MergeToComprehensions.scala:174)
	at scala.Option.getOrElse(Option.scala:121)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertBase$1(MergeToComprehensions.scala:174)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:351)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeFilterWhere$1(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeGroupBy$1(MergeToComprehensions.scala:163)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$14.apply(MergeToComprehensions.scala:103)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$14.apply(MergeToComprehensions.scala:103)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:351)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeSortBy$1(MergeToComprehensions.scala:103)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:351)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createTopLevel$1(MergeToComprehensions.scala:260)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$createSourceOrTopLevel$1$1.apply(MergeToComprehensions.scala:243)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$createSourceOrTopLevel$1$1.apply(MergeToComprehensions.scala:241)
	at scala.Option.getOrElse(Option.scala:121)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createSourceOrTopLevel$1(MergeToComprehensions.scala:241)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertBase$1(MergeToComprehensions.scala:173)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeFilterWhere$1$2.apply(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:351)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeFilterWhere$1(MergeToComprehensions.scala:168)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeGroupBy$1(MergeToComprehensions.scala:163)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$14.apply(MergeToComprehensions.scala:103)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeSortBy$1$14.apply(MergeToComprehensions.scala:103)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:351)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeSortBy$1(MergeToComprehensions.scala:103)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$10.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:351)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$9.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$mergeTakeDrop$1$9.apply(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:326)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$mergeTakeDrop$1(MergeToComprehensions.scala:68)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$createTopLevel$1(MergeToComprehensions.scala:260)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:276)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convert1$1$6.apply(MergeToComprehensions.scala:287)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convert1$1$6.apply(MergeToComprehensions.scala:287)
	at slick.util.ConstArray.endoMap(ConstArray.scala:122)
	at slick.ast.Node$class.mapChildren(Node.scala:51)
	at slick.ast.Apply.mapChildren(Node.scala:547)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:287)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convert1$1$6.apply(MergeToComprehensions.scala:287)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convert1$1$6.apply(MergeToComprehensions.scala:287)
	at slick.util.ConstArray.endoMap(ConstArray.scala:122)
	at slick.ast.Node$class.mapChildren(Node.scala:51)
	at slick.ast.StructNode.mapChildren(Node.scala:151)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:287)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1(MergeToComprehensions.scala:293)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:292)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:292)
	at slick.ast.UnaryNode$class.mapChildren(Node.scala:224)
	at slick.ast.Pure.mapChildren(Node.scala:243)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1(MergeToComprehensions.scala:292)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:292)
	at slick.compiler.MergeToComprehensions$$anonfun$slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1$1.apply(MergeToComprehensions.scala:292)
	at slick.util.ConstArray.endoMap(ConstArray.scala:122)
	at slick.ast.Node$class.mapChildren(Node.scala:51)
	at slick.ast.Comprehension.mapChildren(Comprehension.scala:8)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convertOnlyInScalar$1(MergeToComprehensions.scala:292)
	at slick.compiler.MergeToComprehensions.slick$compiler$MergeToComprehensions$$convert1$1(MergeToComprehensions.scala:276)
	at slick.compiler.MergeToComprehensions.convert(MergeToComprehensions.scala:296)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1$$anonfun$15.apply(MergeToComprehensions.scala:29)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1$$anonfun$15.apply(MergeToComprehensions.scala:28)
	at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:24)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1.apply(MergeToComprehensions.scala:28)
	at slick.compiler.MergeToComprehensions$$anonfun$apply$1.apply(MergeToComprehensions.scala:28)
	at slick.compiler.CompilerState.map(QueryCompiler.scala:228)
	at slick.compiler.MergeToComprehensions.apply(MergeToComprehensions.scala:28)
	at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:79)
	at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:78)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at slick.ast.SymbolNamer.use(Symbol.scala:112)
	at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
	at slick.compiler.QueryCompiler$$anonfun$3.apply(QueryCompiler.scala:65)
	at slick.compiler.QueryCompiler$$anonfun$3.apply(QueryCompiler.scala:63)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:63)
	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
	at slick.basic.BasicProfile$API$class.streamableQueryActionExtensionMethods(BasicProfile.scala:59)
	at slick.jdbc.JdbcProfile$$anon$1.streamableQueryActionExtensionMethods(JdbcProfile.scala:67)
	at com.github.tminglei.slickpg.AggFuncErrorDemo$.main(AggFuncErrorDemo.scala:40)
	at com.github.tminglei.slickpg.AggFuncErrorDemo.main(AggFuncErrorDemo.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by JeremiasIsnardy** [comment]
Are there any news on this topic?
Would be nice to have the aggregation functions from postgres in combination with a groupBy syntax, but as far as I can see this issue needs to be solved first.

**Comment by cirellamhcs** [comment]
Got the same problem on my side. Would be great to be able to use the groupBy syntax!

**Comment by mattfeury** [comment]
another vote to get this fixed here. scala is great, but if i have to write raw sql to make queries, it makes less and less sense to use a typed language.

**Comment by hvesalai** [comment]
Anyone doing a PR to fix this?

**Comment by evbo** [comment]
@hvesalai @tminglei I'm a newcomer to slick, but the way I worked around this issue was inline with how @gedejong solved it here: https://github.com/tminglei/slick-pg/issues/289

So if `ExtensionMethods` classes like [SingleColumnQueryExtensionMethods](https://github.com/slick/slick/blob/42d787b4950fe876569b5fd68e98c4e0379ac83c/slick/src/main/scala/slick/lifted/ExtensionMethods.scala#L156) didn't have a `final` modifier, then one could simply incorporate a mixin that adds the desired aggregation function. Because of the final modifier, currently you have to re-implement the classes yourself, which is terrible code smell of course.

How opposed are maintainers of slick to lifting the final modifiers off of `ExtensionMethods` classes? Is that do-able, or are the final modifiers there for an important reason that as a newbie I'm missing?

I sense someone put the `final` modifiers there for a good reason, so this may just be me grabbing at straws trying to find a work around.
