### ISSUE TITLE
Invalid default value None for non-nullable column. (Oracle)

### ISSUE THREAD

**Issue by OUeasley** [slick/slick#1592]
``` sbt
"com.typesafe.slick" %% "slick" % "3.2.0-M1",
"com.typesafe.slick" %% "slick-codegen" % "3.2.0-M1",
```

I was running a schema code generation test and encountered this error. The problem is that Oracle allows the default value to be **NULL** on a **NOT-NULL** column. I'm more than certain this is our fault for bad table creation but thought I would at least create an issue.

Thanks

Full Error:

``` scala
Invalid default value None for non-nullable column FOO.BEGIN_DATE of type java.sql.Timestamp, meta data: MColumn(MQName(FOO),BEGIN_DATE,93,TIMESTAMP(0),Some(7),Some(0),10,Some(false),None,Some(NULL ),7,3,Some(false),None,None,Some(false))
slick.SlickException: Invalid default value None for non-nullable column FOO.BEGIN_DATE of type java.sql.Timestamp, meta data: MColumn(MQName(FOO),BEGIN_DATE,93,TIMESTAMP(0),Some(7),Some(0),10,Some(false),None,Some(NULL ),7,3,Some(false),None,None,Some(false))
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3$$anonfun$apply$18$$anonfun$apply$19.apply(JdbcModelBuilder.scala:257)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3$$anonfun$apply$18$$anonfun$apply$19.apply(JdbcModelBuilder.scala:257)
    at scala.Option.getOrElse(Option.scala:121)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3$$anonfun$apply$18.apply(JdbcModelBuilder.scala:257)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3$$anonfun$apply$18.apply(JdbcModelBuilder.scala:254)
    at scala.Option.map(Option.scala:146)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder$$anonfun$defaultColumnOption$3.apply(JdbcModelBuilder.scala:254)
    at scala.Option.getOrElse(Option.scala:121)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:253)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:263)
    at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:281)
    at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
    at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:163)
    at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:163)
    at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:161)
    at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
    at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:285)
    at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:96)
    at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:93)
    at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
    at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
    at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
    at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cvogt** [comment]
@OUeasley What's the behavior in that case? What will a new row contain? NULL despite being NOT NULL or some other value?

**Comment by OUeasley** [comment]
@cvogt I'm actually unsure. The more I think about it...our constraint is valid. We want the default value to be null and reject if nothing is there. There would never be a row inserted unless that value is set. Does that make sense?

**Comment by hvesalai** [comment]
I'll close this for now. Reopen with if there is a bug
