### ISSUE TITLE
"subquery in FROM must have an alias" although an alias was defined

### ISSUE THREAD

**Issue by EndeNeu** [slick/slick#1593]
I have a simple sql (obviously my query is not so simple but for the sake of simplicity):

```
val query = sql"""SELECT COUNT(result.id) FROM (SELECT d.id FROM document d) AS result""".as[Int]
```

Which I then simply run with a `database.run(query)`. This query runs well on the console, but in my application is throwing this exception:

```
[debug] - application - Could not execute database call: ERROR: subquery in FROM must have an alias
  Hint: For example, FROM (SELECT ...) [AS] foo.
  Position: 57
[error] - application - sql state: 42601
[error] - application - Generic database error occurred.
org.postgresql.util.PSQLException: ERROR: subquery in FROM must have an alias
  Hint: For example, FROM (SELECT ...) [AS] foo.
  Position: 57
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:413)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.execute(HikariPreparedStatementProxy.java)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:100)
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:100)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using slick 3.1.1 on Scala 2.11.8.

**Comment by cvogt** [comment]
Slick passes this SQL query straight to postgres. This error message comes from postgres. Seems like your query is invalid. Check the postgres docs.

Feel free to re-open if you still think Slick is somehow responsible for this.
