### ISSUE TITLE
MySQL testDiscriminatorTest fails

### ISSUE THREAD

**Issue by rbellamy** [slick/slick#1608]
When running `sbt test` against MySQL on master, I see the following failed test:
```scala
[error] Test com.typesafe.slick.testkit.tests.JoinTest.testDiscriminatorCheck[mysql] failed: java.lang.AssertionError: expected:<Set(3)> but was:<Set()>, took 0.054 sec
[error]     at com.typesafe.slick.testkit.tests.JoinTest$$anonfun$testDiscriminatorCheck$2.apply(JoinTest.scala:347)
[error]     at com.typesafe.slick.testkit.tests.JoinTest$$anonfun$testDiscriminatorCheck$2.apply(JoinTest.scala:347)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
[error]     at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:44)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anonfun$runInContext$1.apply(BasicBackend.scala:149)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
[error]     at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error]     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by hvesalai** [comment]
Any fix for this?
