### ISSUE TITLE
slick-codegen postgres driver not found for 3.2.0-M1

### ISSUE THREAD

**Issue by chris-baynes** [slick/slick#1616]
Codegen fails for slick-codegen `3.2.0-M1` with the following error:

```
 java.lang.ClassNotFoundException: slick.driver.PostgresDriver$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at slick.codegen.SourceCodeGenerator$.run(SourceCodeGenerator.scala:66)
	at slick.codegen.SourceCodeGenerator$.main(SourceCodeGenerator.scala:94)
	at slick.codegen.SourceCodeGenerator.main(SourceCodeGenerator.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

This is working in our Play application for slick-codegen `3.1.1`. Wanted to upgrade to 3.2 to get access to the `ignoreInvalidDefaults` flag.

**Comment by cvogt** [comment]
pass "slick.jdbc.PostgresProfile" as the profile probably from your sbt configuration. Package and object name changed

**Comment by kag0** [comment]
hey @cvogt , @chris-baynes I have this same issue on `3.2.0`, could you elaborate more on what you did to resolve the issue?

**Comment by djx314** [comment]
@chris-baynes @kag0 `slick.driver` package already rename to `slick.jdbc` in 3.2.0
