### ISSUE TITLE
Update top n rows of a Table

### ISSUE THREAD

**Issue by PeterQT** [slick/slick#1672]
I want to update top n rows of a table not the entire one when using `slick 3.0`

This is the update all version:

```
    val active = this.filter(a => a.status =!= AccountStatus.DISABLED)
    db.run(
        active.filter(a => a.usedBy.isEmpty || a.usedBy === Host.name)
        .map(a => a.usedBy)
        .update("host-a")
    )
```

I tried to use this version but it didn't work and thrown an exception

```
    val active = this.filter(a => a.status =!= AccountStatus.DISABLED)
    db.run(
        active.filter(a => a.usedBy.isEmpty || a.usedBy === Host.name)
        .take(10)
        .map(a => a.usedBy)
        .update(Option(Host.name))
    )
```

**Exception**

```
    Caused by: slick.SlickException: A query for an UPDATE statement must resolve to a comprehension with a single table -- Unsupported shape: Comprehension s2, Some(Apply Function and), None, ConstArray(), None, None, Some(LiteralNode 100 (volatileHint=false)), None
	at slick.driver.JdbcStatementBuilderComponent$QueryBuilder.buildUpdate(JdbcStatementBuilderComponent.scala:447)
	at slick.driver.JdbcProfile$$anonfun$updateCompiler$1.apply(JdbcProfile.scala:30)
	at slick.driver.JdbcProfile$$anonfun$updateCompiler$1.apply(JdbcProfile.scala:30)
	at slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.compileServerSideAndMapping(JdbcMappingCompilerComponent.scala:59)

```
Posted question on SO - [link](http://stackoverflow.com/questions/41311802/update-top-n-rows-of-a-table-in-slick)

**Comment by cvogt** [comment]
error message is misleading

thanks for the cross linking to SO :)

**Comment by jarcane** [comment]
I seem to have encountered this same issue, and the workaround suggested in the SO link doesn't work either. Some additional wrinkles may be involved in this, as I'm attempting a multi-column update, and the query is to be run transactionally. 

Code basically looks like this (apologies for scrubbing to toy code): 

```scala
    val selectQuery = table
      .filter(someTest)
      // lots more filters
      .take(1)

    val updateQuery = selectQuery
      .map(item => (shift.optionColumn, shift.stringColumn))
      .update(Some(1), "FREE")

    db.run(updateQuery.transactionally)
```

exception: 
```
slick.SlickException: A query for an UPDATE statement must resolve to a comprehension with a single table -- Unsupported shape: Comprehension s2, Some(Apply Function and), None, ConstArray(), None, None, Some(LiteralNode 1 (volatileHint=false)), None

	at slick.driver.JdbcStatementBuilderComponent$QueryBuilder.buildUpdate(JdbcStatementBuilderComponent.scala:447)
	at slick.driver.JdbcProfile$$anonfun$updateCompiler$1.apply(JdbcProfile.scala:30)
	at slick.driver.JdbcProfile$$anonfun$updateCompiler$1.apply(JdbcProfile.scala:30)
	at slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.compileServerSideAndMapping(JdbcMappingCompilerComponent.scala:59)
	at slick.compiler.CodeGen$$anonfun$apply$2$$anonfun$1.apply(CodeGen.scala:22)
	at slick.compiler.CodeGen$$anonfun$apply$2$$anonfun$1.apply(CodeGen.scala:20)
```

Any further ideas on this, or how I might work around the issue? I'd prefer not to do multiple queries here as  it's a potentially time-sensitive transaction.

**Comment by djx314** [comment]
What sql are you want to generate to?

**Comment by avremel** [comment]
I have the same issue. The update statement I am using doesn't compile:
```scala
Orders.filter(_.cookie === cookie).sortBy(_.id.desc).map(_.payTypeId).take(1)
```
The MySQL I want to generate:
```
         UPDATE
            orders
         SET
          orders.pay_type_id = $id
         WHERE
            orders.cart_cookie = $cookie
         ORDER BY id desc
         LIMIT 1
```
[See my SO question](https://stackoverflow.com/questions/52634158/update-statement-with-filter-sortby-map-and-take)
