### ISSUE TITLE
"No type for symbol..." error when implicit join returns a tuple

### ISSUE THREAD

**Issue by stephenjudkins** [slick/slick#1681]
I've written a failing test that exercises this here: https://github.com/stephenjudkins/slick/commit/553418b3f535edf3404ff814c94d2b278cfd9954

Note that moving the tuple-returning join to the tail position addresses this problem. This is the workaround we're using locally.

I'd appreciate any guidance on where and how I might try to fix this bug. I'm looking to contribute back however possible.

**Comment by stephenjudkins** [comment]
If we change the expression to the following, it compiles and works as expected:
```  
val query2 = for {
      d <- ds
      c <- cs
      (a, b) <- query1(d.idD)
    } yield (a, b, c, d)
```

Here's a dump of the working query:
```Bind
┣ from @917503399: TableExpansion
┃ ┣ table @130686143: Table d_join
┃ ┗ columns: Path @130686143.id_d : Int'
┗ select: Bind
  ┣ from @1938478549: TableExpansion
  ┃ ┣ table @1267171675: Table c_join
  ┃ ┗ columns: Path @1267171675.id_c : Int'
  ┗ select: Bind
    ┣ from @34348873: Bind
    ┃ ┣ from @1442108499: Filter @1895143237
    ┃ ┃ ┣ from @1895143237: TableExpansion
    ┃ ┃ ┃ ┣ table @126836057: Table a_join
    ┃ ┃ ┃ ┗ columns: Path @126836057.id_a : Int'
    ┃ ┃ ┗ where: Apply Function =
    ┃ ┃   ┣ 0: Path @1895143237.id_a : Int'
    ┃ ┃   ┗ 1: Path @917503399.id_d : Int'
    ┃ ┗ select: Bind
    ┃   ┣ from @1696332982: Filter @373221898
    ┃   ┃ ┣ from @373221898: TableExpansion
    ┃   ┃ ┃ ┣ table @1244469303: Table b_join
    ┃   ┃ ┃ ┗ columns: Path @1244469303.id_b : Int'
    ┃   ┃ ┗ where: Apply Function =
    ┃   ┃   ┣ 0: Path @1442108499.id_a : Int'
    ┃   ┃   ┗ 1: Path @373221898.id_b : Int'
    ┃   ┗ select: Pure $@926278078
    ┃     ┗ value: ProductNode
    ┃       ┣ 1: Ref @1442108499
    ┃       ┗ 2: Ref @1696332982
    ┗ select: Pure $@225531298
      ┗ value: ProductNode
        ┣ 1: Path @34348873._1
        ┣ 2: Path @34348873._2
        ┣ 3: Ref @1938478549
        ┗ 4: Ref @917503399
```

And here's a dump of the original, broken query:
```
Bind
┣ from @1459245129: TableExpansion
┃ ┣ table @949999089: Table d_join
┃ ┗ columns: Path @949999089.id_d : Int'
┗ select: Bind
  ┣ from @1785861627: Bind
  ┃ ┣ from @410068299: Filter @470636052
  ┃ ┃ ┣ from @470636052: TableExpansion
  ┃ ┃ ┃ ┣ table @1518020665: Table a_join
  ┃ ┃ ┃ ┗ columns: Path @1518020665.id_a : Int'
  ┃ ┃ ┗ where: Apply Function =
  ┃ ┃   ┣ 0: Path @470636052.id_a : Int'
  ┃ ┃   ┗ 1: Path @1459245129.id_d : Int'
  ┃ ┗ select: Bind
  ┃   ┣ from @551297856: Filter @831918445
  ┃   ┃ ┣ from @831918445: TableExpansion
  ┃   ┃ ┃ ┣ table @1205685437: Table b_join
  ┃   ┃ ┃ ┗ columns: Path @1205685437.id_b : Int'
  ┃   ┃ ┗ where: Apply Function =
  ┃   ┃   ┣ 0: Path @410068299.id_a : Int'
  ┃   ┃   ┗ 1: Path @831918445.id_b : Int'
  ┃   ┗ select: Pure $@1155833503
  ┃     ┗ value: ProductNode
  ┃       ┣ 1: Ref @410068299
  ┃       ┗ 2: Ref @551297856
  ┗ select: Bind
    ┣ from @90403680: TableExpansion
    ┃ ┣ table @75438040: Table c_join
    ┃ ┗ columns: Path @75438040.id_c : Int'
    ┗ select: Pure $@694815566
      ┗ value: ProductNode
        ┣ 1: Path @1785861627._1
        ┣ 2: Path @1785861627._2
        ┣ 3: Ref @90403680
        ┗ 4: Ref @1459245129
```

**Comment by hvesalai** [comment]
Hi which slick version is this, can you still reproduce it?

**Comment by stephenjudkins** [comment]
I can still reproduce this on the latest `master` (f0776fb4c217c4aaf20d62a76b9fed718899f713). Here's the failure:

```
[error] Test com.typesafe.slick.testkit.tests.JoinTest.testTupleQueryAggregation[h2mem] failed: slick.SlickException: No type for symbol s2 found for Ref s2, took 0.019 sec
[error]     at slick.ast.Ref.withInferredType(Node.scala:559)
[error]     at slick.ast.Ref.withInferredType(Node.scala:553)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Ref.infer(Node.scala:553)
[error]     at slick.ast.SimplyTypedNode$$anonfun$2.apply(Node.scala:122)
[error]     at slick.ast.SimplyTypedNode$$anonfun$2.apply(Node.scala:122)
[error]     at slick.ast.UnaryNode$class.mapChildren(Node.scala:223)
[error]     at slick.ast.Select.mapChildren(Node.scala:527)
[error]     at slick.ast.SimplyTypedNode$class.withInferredType(Node.scala:122)
[error]     at slick.ast.Select.withInferredType(Node.scala:527)
[error]     at slick.ast.Select.withInferredType(Node.scala:527)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Select.infer(Node.scala:527)
[error]     at slick.ast.SimplyTypedNode$$anonfun$2.apply(Node.scala:122)
[error]     at slick.ast.SimplyTypedNode$$anonfun$2.apply(Node.scala:122)
[error]     at slick.util.ConstArray.endoMap(ConstArray.scala:122)
[error]     at slick.ast.Node$class.mapChildren(Node.scala:50)
[error]     at slick.ast.Apply.mapChildren(Node.scala:546)
[error]     at slick.ast.SimplyTypedNode$class.withInferredType(Node.scala:122)
[error]     at slick.ast.Apply.withInferredType(Node.scala:546)
[error]     at slick.ast.Apply.withInferredType(Node.scala:546)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Apply.infer(Node.scala:546)
[error]     at slick.ast.SimplyTypedNode$$anonfun$2.apply(Node.scala:122)
[error]     at slick.ast.SimplyTypedNode$$anonfun$2.apply(Node.scala:122)
[error]     at slick.util.ConstArray.endoMap(ConstArray.scala:122)
[error]     at slick.ast.Node$class.mapChildren(Node.scala:50)
[error]     at slick.ast.Apply.mapChildren(Node.scala:546)
[error]     at slick.ast.SimplyTypedNode$class.withInferredType(Node.scala:122)
[error]     at slick.ast.Apply.withInferredType(Node.scala:546)
[error]     at slick.ast.Apply.withInferredType(Node.scala:546)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Apply.infer(Node.scala:546)
[error]     at slick.ast.Join.withInferredType(Node.scala:437)
[error]     at slick.ast.Join.withInferredType(Node.scala:423)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Join.infer(Node.scala:423)
[error]     at slick.ast.Bind.withInferredType(Node.scala:472)
[error]     at slick.ast.Bind.withInferredType(Node.scala:462)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Bind.infer(Node.scala:462)
[error]     at slick.ast.Join.withInferredType(Node.scala:433)
[error]     at slick.ast.Join.withInferredType(Node.scala:423)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Join.infer(Node.scala:423)
[error]     at slick.ast.Join.withInferredType(Node.scala:434)
[error]     at slick.ast.Join.withInferredType(Node.scala:423)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Join.infer(Node.scala:423)
[error]     at slick.ast.Bind.withInferredType(Node.scala:472)
[error]     at slick.ast.Bind.withInferredType(Node.scala:462)
[error]     at slick.ast.Node$class.infer(Node.scala:89)
[error]     at slick.ast.Bind.infer(Node.scala:462)
[error]     at slick.compiler.VerifyTypes.check(VerifyTypes.scala:30)
[error]     at slick.compiler.VerifyTypes$$anonfun$apply$1.apply(VerifyTypes.scala:17)
[error]     at slick.compiler.VerifyTypes$$anonfun$apply$1.apply(VerifyTypes.scala:15)
[error]     at slick.compiler.CompilerState.map(QueryCompiler.scala:230)
[error]     at slick.compiler.VerifyTypes.apply(VerifyTypes.scala:15)
[error]     at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:89)
[error]     at slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:78)
[error]     at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error]     at slick.ast.SymbolNamer.use(Symbol.scala:111)
[error]     at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
[error]     at slick.compiler.QueryCompiler$$anonfun$runPhases$4.apply(QueryCompiler.scala:75)
[error]     at slick.compiler.QueryCompiler$$anonfun$runPhases$4.apply(QueryCompiler.scala:75)
[error]     at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
[error]     at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[error]     at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
[error]     at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
[error]     at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:75)
[error]     at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
[error]     at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
[error]     at slick.basic.BasicProfile$API$class.streamableQueryActionExtensionMethods(BasicProfile.scala:56)
[error]     at slick.jdbc.JdbcProfile$$anon$1.streamableQueryActionExtensionMethods(JdbcProfile.scala:67)
[error]     at com.typesafe.slick.testkit.tests.JoinTest.testTupleQueryAggregation(JoinTest.scala:395)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:498)
[error]     at com.typesafe.slick.testkit.util.TestMethod.run(Testkit.scala:102)
[error]     at com.typesafe.slick.testkit.util.Testkit$$anonfun$runChildren$2.apply(Testkit.scala:68)
[error]     at com.typesafe.slick.testkit.util.Testkit$$anonfun$runChildren$2.apply(Testkit.scala:60)
[error]     at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[error]     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]     at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
[error]     at com.typesafe.slick.testkit.util.Testkit.runChildren(Testkit.scala:60)
[error]     at com.typesafe.slick.testkit.util.SimpleParentRunner.run(SimpleParentRunner.scala:56)
[error]     ...
[info] Test com.typesafe.slick.testkit.tests.JoinTest.testJoin[h2mem] started
```

**Comment by stephenjudkins** [comment]
Additionally, I've rebased this test on top of the latest `master`: https://github.com/stephenjudkins/slick/tree/tuple-join-regression

**Comment by hvesalai** [comment]
Did you have a PR to fix this?

**Comment by stephenjudkins** [comment]
No. Happy to hear any advice on the best way to dig in and try to fix this, though

**Comment by hvesalai** [comment]
I can't give any definite pointers, but the thing seems to work when the `Pure` referring to the tuple is a direct `select` child of the `Bind`, whose `from` is referred to.

@szeiger could give more pointers if he has time.
