### ISSUE TITLE
java.util.concurrent.RejectedExecutionException without transactionally

### ISSUE THREAD

**Issue by djx314** [slick/slick#1683]
I have to update 30,000 rows in mysql. I divided the data to about 5 groups and update them. Here's the code:
```scala
class IdTable(tag: Tag, tableName: String) extends Table[Long](tag, tableName) {
	def id = column[Long]("id")
	def * = id
}
def genTq(tableName: String): TableQuery[IdTable] = {
	new TableQuery(tag => new IdTable(tag, tableName))
}

def getPingYin(src: String): String = ???

val execFuture = {
	val tableName = "contacter_new"
	db.run {
		(for {
			enTable <- genTq(tableName) if ! (enTable.column[Option[String]]("pinyin").isDefined && (enTable.column[Option[String]]("pinyin") != ""))
		} yield {
			(enTable.column[Long]("id"), enTable.column[String]("name"))
		}).result
	}.flatMap { dataList =>
		println(s"要转换 ${dataList.size} 行数据")
		val bb: List[List[(Long, String)]] = (0 to (dataList.size - 1) by 6000).zipWithIndex.map { case (dataIndex, arrayIndex) =>
			dataList.drop(dataIndex).take(6000).toList
		}.toList
		Future.sequence {
			bb.map { splitData =>
				Future.sequence {
					splitData.map { case (id, name) =>
						db.run(
							genTq(tableName).filter(s => s.column[Long]("id") === id).map { s => s.column[String]("pinyin") }.update(getPingYin(name))
						)
					}
				}
			}
		}
	}
}

println("查找了" + Await.result(execFuture, duration.Duration.Inf) + "行数据")
```

There is no transactionally in it. And it throw the exception below:
```
[error] (run-main-5) java.util.concurrent.RejectedExecutionException: Task slick
.basic.BasicBackend$DatabaseDef$$anon$2@7356e20b rejected from slick.util.AsyncE
xecutor$$anon$2$$anon$1@b1c702d[Running, pool size = 20, active threads = 20, qu
eued tasks = 999, completed tasks = 2564]
java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$D
atabaseDef$$anon$2@7356e20b rejected from slick.util.AsyncExecutor$$anon$2$$anon
$1@b1c702d[Running, pool size = 20, active threads = 20, queued tasks = 999, com
pleted tasks = 2564]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution
(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.jav
a:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.ja
va:1369)
        at slick.util.AsyncExecutor$$anon$2$$anon$3.execute(AsyncExecutor.scala:
120)
        at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(Bas
icBackend.scala:233)
        at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(Ba
sicBackend.scala:231)
        at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcB
ackend.scala:38)
        at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:
210)
        at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala
:142)
        at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)

        at slick.basic.BasicBackend$DatabaseDef.runInternal(BasicBackend.scala:7
8)
        at slick.basic.BasicBackend$DatabaseDef.runInternal$(BasicBackend.scala:
77)
        at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:38)
        at slick.basic.BasicBackend$DatabaseDef.run(BasicBackend.scala:75)
        at slick.basic.BasicBackend$DatabaseDef.run$(BasicBackend.scala:75)
        at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:38)
        at ConnectTest$.$anonfun$execFuture$6(ConnectTest.scala:98)
        at scala.collection.immutable.List.map(List.scala:276)
        at ConnectTest$.$anonfun$execFuture$5(ConnectTest.scala:96)
        at scala.collection.immutable.List.map(List.scala:272)
        at ConnectTest$.$anonfun$execFuture$3(ConnectTest.scala:94)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:
37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(E
xecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java
:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.ja
va:157)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 39 s, completed 2017-1-18 11:24:00
```

**Comment by AtkinsChang** [comment]
This is the intended behavior. You can config `queueSize` which default is 1000.

**Comment by djx314** [comment]
Thanks. I will have a try after the holiday. And I will close it if the test is success.

**Comment by cvogt** [comment]
please reopen if this still exists

**Comment by djx314** [comment]
@cvogt Because I needed to insert 200 lows each time. And I have 230,000 rows to insert. Finally `queueSize` doesn't work, I use the code below(the parameter is so large sine the mysql schema is offline):
```scala
val jdbcDriver = "com.mysql.cj.jdbc.Driver"

  val ds = new com.zaxxer.hikari.HikariDataSource()
  ds.setDriverClassName(jdbcDriver)
  ds.setUsername("root")
  ds.setPassword("root")
  ds.setJdbcUrl(url)
  ds.setReadOnly(false)
  ds.setConnectionTimeout(30000)
  ds.setMaximumPoolSize(240)
  ds.setConnectionTestQuery("select 1;")

  val db = Database.forDataSource(ds, Option(300))
```

**Comment by szeiger** [comment]
We generally recommend to use Akka Streams for this kind of job. You can write a flow that does reads the source data, does all the necessary transformations, and then performs the inserts inside a `mapAsync` call to limit the number of concurrent database actions.

**Comment by djx314** [comment]
@szeiger @cvogt Already use db.stream in slick and `ds.setMaximumPoolSize(largeNumber)` is necessary. Because in jdbc connection pool, the connection close use to watse some time and the default setting is not enough to support such large number of DBIOActions. When it has enough connections need to close and not be closed, it will cause the RejectedExecutionException.

**Comment by hvesalai** [comment]
Running into this also

```
java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@3cb503be rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@48bf4020[Running, pool size = 10, active threads = 5, queued tasks = 0, completed tasks = 753206]
```

Can't understand what it is saying. Looks like there are zero queued tasks and still one is being rejected.

**Comment by hvesalai** [comment]
Opened a new issue #1827
