### ISSUE TITLE
insertOrUpdate generates invalid SQL without primary key

### ISSUE THREAD

**Issue by marko-asplund** [slick/slick#1699]
If insertOrUpdate is used with a row object for which no primary key is specified, invalid SQL gets generated:

```
2017-03-06 14:47:02.675 DEBUG slick.jdbc.JdbcBackend.statement - Preparing statement: insert into "foo" ("a", "b", "c") values (?, ?, ?) on conflict () do update set "a"=EXCLUDED."a", "b"=EXCLUDED."b", "c"=EXCLUDED."c"
```

Which results in the following database error with PostgreSQL:
```
org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 132
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412) ~[postgresql-42.0.0.jar:42.0.0]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125) ~[postgresql-42.0.0.jar:42.0.0]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297) ~[postgresql-42.0.0.jar:42.0.0]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428) ~[postgresql-42.0.0.jar:42.0.0]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354) ~[postgresql-42.0.0.jar:42.0.0]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169) ~[postgresql-42.0.0.jar:42.0.0]
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136) ~[postgresql-42.0.0.jar:42.0.0]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-2.5.1.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-2.5.1.jar:na]
        at slick.jdbc.LoggingPreparedStatement$$anonfun$executeUpdate$5.apply$mcI$sp(LoggingStatement.scala:155) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.LoggingPreparedStatement$$anonfun$executeUpdate$5.apply(LoggingStatement.scala:155) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.LoggingPreparedStatement$$anonfun$executeUpdate$5.apply(LoggingStatement.scala:155) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:84) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.LoggingPreparedStatement.executeUpdate(LoggingStatement.scala:155) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction$$anonfun$nativeUpsert$1.apply(JdbcActionComponent.scala:564) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction$$anonfun$nativeUpsert$1.apply(JdbcActionComponent.scala:561) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:372) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:434) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:502) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.nativeUpsert(JdbcActionComponent.scala:561) ~[slick_2.11-3.2.0.jar:na]
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.f$1(JdbcActionComponent.scala:544) ~[slick_2.11-3.2.0.jar:na]
...
```

Slick should detect this mapping anomaly issue an error message.

This is with Slick 3.2.0 and PostgreSQL.

**Comment by greenhat** [comment]
I took a stab at it. I've tried the code to fail as early as possible at #1836
