### ISSUE TITLE
Task slick.basic.BasicBackend$DatabaseDef$$anon$2@dc100cf rejected from slick.util.AsyncExecutor

### ISSUE THREAD

**Issue by yurique** [slick/slick#1730]
With Slick 3.2 (hikaricp, default settings) we had this:

```
Task slick.basic.BasicBackend$DatabaseDef$$anon$2@dc100cf rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@2f716c9e[Running, pool size = 20, active threads = 0, queued tasks = 0, completed tasks = 74259]
```

`pool size = 20, active threads = 0, queued tasks = 0`

And it was not recovering from it, every DB action was failing with this exception. Had to restart the app server.

This happened twice over the last week.

**Comment by johann-abraham** [comment]
+1

**Comment by cvogt** [comment]
@trevorsibanda I know you haven't worked on Slick's concurrency aspects before, but maybe you could start diving into that an providing some help to our community? This may partly just be documentation, saner defaults, sanity checks. Maybe also bug fixes.

**Comment by pangwa** [comment]
+1 meeting the same issue, have to rollback to 3.1.

**Comment by pettyjamesm** [comment]
Just had what I believe is a related issue occur in slick. The stacktrace is here:

```
Exception in thread "slick-hikaricp-1" java.lang.IllegalArgumentException: requirement failed: count cannot be decreased 
  	at scala.Predef$.require(Predef.scala:224) 
  	at slick.util.ManagedArrayBlockingQueue$$anonfun$decreaseInUseCount$1.apply$mcV$sp(ManagedArrayBlockingQueue.scala:53) 
  	at slick.util.ManagedArrayBlockingQueue$$anonfun$decreaseInUseCount$1.apply(ManagedArrayBlockingQueue.scala:52) 
  	at slick.util.ManagedArrayBlockingQueue$$anonfun$decreaseInUseCount$1.apply(ManagedArrayBlockingQueue.scala:52) 
  	at slick.util.ManagedArrayBlockingQueue.slick$util$ManagedArrayBlockingQueue$$locked(ManagedArrayBlockingQueue.scala:217) 
  	at slick.util.ManagedArrayBlockingQueue.decreaseInUseCount(ManagedArrayBlockingQueue.scala:52) 
  	at slick.util.AsyncExecutor$$anon$2$$anon$1.afterExecute(AsyncExecutor.scala:87) 
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150) 
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
  	at java.lang.Thread.run(Thread.java:745)
```

After reading through the code, I can tell you I'm scared that someone attempted to customize the queue implementation without understanding practical concurrency issues. Both `slick.util.ManagedArrayBlockingQueue` calls into `slick.util.InternalArrayBlockingQueue#count` in multiple places in multiple threads to determine whether to accept or reject work, but those `count` variables are not marked `@volatile` and are therefore not reliable when read from different threads.

This is a serious issue for anyone running this in production, but it seems to also exist in earlier versions of slick (although the code was different, the same fundamental issue of non-volatile reads can manifest itself).

**Comment by pettyjamesm** [comment]
In addition to my prior comments, you'll find that https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/ManagedArrayBlockingQueue.scala#L109 also has no call to `notFull.signal()` which is necessary to wake up threads that are blocked trying to enqueue more work. I'm working on replacing the built-in `AsyncExecutor` in our codebase entirely due to these issues.

**Comment by cvogt** [comment]
@pettyjamesm mind trying to feed things back as PRs?

**Comment by pettyjamesm** [comment]
@cvogt I'm worried that my implementation is going to only cover my use-cases, and from what I've seen so far- there are a lot of `private[slick.util]` visibility modifiers and pattern matches in awkward locations that make it difficult to understand the intention of the original design.

Where can I get a starting point covering the intended design? Anyone I can talk to? Feels like there are a lot of gotchas hidden in around the slick execution model, and I don't want to be the one that accidentally breaks slick's concurrency further.

**Comment by cvogt** [comment]
@szeiger knows best by far, he might be reachable via gitter

**Comment by szeiger** [comment]
> After reading through the code, I can tell you I'm scared that someone attempted to customize the queue implementation without understanding practical concurrency issues. Both `slick.util.ManagedArrayBlockingQueue` calls into `slick.util.InternalArrayBlockingQueue#count` in multiple places in multiple threads to determine whether to accept or reject work, but those count variables are not marked `@volatile` and are therefore not reliable when read from different threads.

@pettyjamesm Except for the initialization of the iterator in `ManagedArrayBlockingQueue.iterator` all uses of `InternalArrayQueue` look safe to me. `InternalArrayQueue` does not perform any synchronization of its own, instead it relies on the caller to ensure proper synchronization. Except for the iterator initialization, all calls to an `InternalArrayQueue` occur inside a `locked` or `lockedInterruptibly` block of the `ManagedArrayBlockingQueue`. While the definition of `iterator` is indeed wrong, the method is never used by Slick. I just verified this by successfully running the test suite with `???` as the implementation of `iterator.

> This is a serious issue for anyone running this in production, but it seems to also exist in earlier versions of slick (although the code was different, the same fundamental issue of non-volatile reads can manifest itself).

Thread transitions are managed as efficiently as possible by Slick, without unnecessary memory barriers (but in full compliance with the Java memory model - we do not take any shortcuts that work on known implementations but are illegal according to the spec). In particular, happens-before relationships are established in core parts of the asynchronous execution engine through *specific* volatile vars. It is not necessary that all shared vars are volatile as long as they are written and read in the correct order.

> In addition to my prior comments, you'll find that https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/ManagedArrayBlockingQueue.scala#L109 also has no call to `notFull.signal()` which is necessary to wake up threads that are blocked trying to enqueue more work.

We never block on enqueuing, so this should not be an issue.

@kwark may have an idea what's wrong because he implemented this fix. After reviewing the code again, the use counter handling looks a bit strange. In particular, `decreaseInUseCount` does not take a `PrioritizedRunnable` in order to unset its `inUseCounterSet` flag atomically. Instead this is done at the call site even when the connection was *not* released. It looks to me like this would lead to duplicate counter increases in some cases (which could cause a `RejectedExecutionException` on an empty pool).

OTOH, are we sure that the behavior is really a bug? From the thread pool state ("pool size = 20, active threads = 0, queued tasks = 0") alone this is not clear. After all, the new connection counting is *supposed* to stall the thread pool when the connection pool is exhausted. Anyone who observes this behavior with 3.2. please report the current connection pool usage (e.g. via HikariCP's JMX interface). This could help narrow this problem down.

**Comment by pangwa** [comment]
I enabled the HikariPool log, the pool status looks OK before/after application hang. 
`
**2017-05-21 11:02:44 +0800 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in db h
ousekeeper - db - After cleanup  stats (total=21, active=1, idle=20, waiting=0)**

play.api.UnexpectedException: Unexpected exception[RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@57294dc rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@3286b82f[Running, pool size = 20, active threads = 0, queued tasks = 0, completed tasks = 13619874]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
 
**2017-05-21 11:03:14 +0800 [DEBUG] from com.zaxxer.hikari.pool.HikariPool in db housekeeper - db - After cleanup  stats (total=21, active=1, idle=20, waiting=0)**
2
`

**Comment by szeiger** [comment]
Hm, this is really strange. Are we perhaps counting too many actions (i.e. also the ones without a connection)? Do you have any pinned sessions or transactions with asynchronous computations in between?

What puzzles me is that the exceptions are intermittent. If this was really caused by a leak in the counter (more increments than decrements) I would expect the failure state to be permanent when there are no active threads at the time of the exception. The count can only go down when there are still pending Futures that eventually complete and cause the counter to be decremented again.

**Comment by nukemichaels** [comment]
Currently I'm facing pretty same problem on Slick 3.2.0 and 3.2.0-M1. Our application starts about ~60 short queries per second and throws exception after ~30 seconds of processing:
```
Task slick.basic.BasicBackend$DatabaseDef$$anon$2@66454e6e rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@4997c527[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 1824]
```
We are consistently getting such exceptions in our application: 10 crashes out of 10 runs.
We noticed a difference between default and our own HikariCP configuration. We are using
`numThreads = 10` and `maxConnections = 10` opposing to default `maxConnections = 5 * numThreads`. We tried to switch to default setting of `maxConnections = 50` and now our application crushes little bit later with another exception!
```
Task slick.basic.BasicBackend$DatabaseDef$$anon$2@60f8433a rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@23942d7c[Running, pool size = 10, active threads = 10, queued tasks = 996, completed tasks = 4010]
```
AFAIK, such exceptions is intended behavior of Slick.

**Comment by szeiger** [comment]
@nukemichaels Yes, the second one looks normal (assuming a queue size of around 1000; the reported number may not be precise because other threads could have modified it between the moment the error occurred and constructing the error message). In this case you'll want to benchmark increased thread pool sizes to find the best performing size, and then adjust the queue size for the desired latency trade-off.

The fact that the original problem doesn't occur with a larger connection pool is another indicator that you are either observing the intended behavior of the deadlock prevention or that we are counting too many actions.

**Comment by kwark** [comment]
@szeiger I had a look at the call site of `decreaseInUseCount`. There is indeed a call to unset the `inUseCounterSet` flag even if the connection was not released. This is however only a problem when the PrioritizedRunnable is re-run/re-scheduled. I don't think that ever happens.
It might be fine to just remove that line.

**Comment by pangwa** [comment]
@szeiger 
> Hm, this is really strange. Are we perhaps counting too many actions (i.e. also the ones without a connection)? Do you have any pinned sessions or transactions with asynchronous computations in between?

There is no pinned sessions/transactions in our code. This error is unrecoverable but happens randomly.

**Comment by kwark** [comment]
@szeiger There is possibly a `readSync` call missing at the beginning of https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/basic/BasicBackend.scala#L379

This might lead to the priority being incorrectly determined and the `inUseCount` of the `ManagedBlockingArrayQueue` being incremented incorrectly.

Unfortunately I'm not able to reproduce the behaviour seen by others and so I can't confirm if adding a readSync fixes this issue or not.

**Comment by kwark** [comment]
I finally managed to reproduce this issue.

In my scenario a `decreaseInUseCount` call was missing, because the priority was calculated incorrectly. The priority calculation uses the `BasicActionContext.currentSession` variable. The thread that executes the SynchronousDatabaseAction still saw an incorrect non-null `currentSession` variable in the `afterExecute` method and hence did not call the `decreaseInUseCount` method.

@szeiger The only possible solution I have found is to use an AtomicReference for the `currentSession` in the `BasicActionContext`.
Using the `readSync`trick apparently does not work for reference variables and will only protect primitive variables in the `BasicActionContext`

I'll prepare a PR.

**Comment by szeiger** [comment]
That's strange. It shouldn't matter what you read because happens-before affects all reads and writes, no matter how it was established. Is there a corresponding write to `ctx.sync` after setting the state in the other thread?

**Comment by kwark** [comment]
@szeiger After another look at the code and running some more tests, it looks like we just have a race condition between two threads accessing/modifying the `BasisActionContext` simultaneously.

When we run a SynchronousDatabaseAction the promise is first completed (https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/basic/BasicBackend.scala#L248) before the `afterExecute` method of the ThreadPoolExecutor is called.
 (https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/AsyncExecutor.scala#L83)

This means that for example a flatMapped, unpinned DBIOAction can start running on the threadpool and acquire a session (and JDBC connection) before the check to call `decreaseInUseCount` by the other thread finishing its work. This last thread will then incorrectly determine the priority and not call `decreaseInUseCount`.

In this case we can move the additional check for the priority to the `runSynchronousDatabaseAction` method:

```
      } finally {
          if (!ctx.isPinned && ctx.priority(continuation) != WithConnection) connectionReleased = true
          ctx.sync = 0
      }
```

This covers the scenario where we miss decreasing the inUseCount and the ManagedBlockingArrayQueue staying paused forever.

However there might still be scenarios where the increaseInUseCount is incremented incorrectly twice or not incremented when it should be.

I think we also need an additional readSync call as mentioned in https://github.com/slick/slick/issues/1730#issuecomment-307620788

**Comment by szeiger** [comment]
Ah, good catch. The ActionContext is only supposed to be accessed sequentially. I agree with moving the check into `runSynchronousDatabaseAction`.

**Comment by yurique** [comment]
Is there a chance for something like `3.0.0.1` release with this one? :)  (the `3.2.1` milestone seems far away from being released)

**Comment by szeiger** [comment]
Reopening because the fix still needs to be backported to 3.2.x. We'll do 3.2.1 as soon as this is in. We recently automated much of the release process so we can easily do more frequent releases.

**Comment by yurique** [comment]
The backport has been merged, any plans for a release? :)

**Comment by trevorsibanda** [comment]
@yurique we are releasing 3.2.1 today

**Comment by Deep-1991** [comment]
@trevorsibanda 3.2.1 hasn't been released, right?

**Comment by djx314** [comment]
Already add tag, I think it will be see in maven soon. @Deep-1991

**Comment by Discipe** [comment]
Just encountered it on Slick 3.2.1 with local Postgres DB:

java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@5ba5c871 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@52cfc71[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 14]

I'm wondering what "pool size = 0" could possibly mean O_o.

**Comment by EndeNeu** [comment]
I'm experiencing the same issue at the moment:

`Task slick.basic.BasicBackend$DatabaseDef$$anon$2@79767ab6 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@2708583a[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 178] 
Promise already completed.  
`

Not sure what this is supposed to mean, I also have set the same `numThreads` as n the execution context. My use case is (as most of the people who encountered this issue I think) I have a lot of concurrent operations which are executed transactionally.

**Comment by wkronmiller** [comment]
We have switched to version 3.2.1 but are still experiencing this error:

`java.util.concurrent.RejectedExecutionException: Task
slick.basic.BasicBackend$DatabaseDef$$anon$2@54d51bc rejected from
slick.util.AsyncExecutor$$anon$2$$anon$1@5ef0b89[Running, pool size = 20, active threads = 20,
queued tasks = 1001, completed tasks = 12256939]`

After upgrading to 3.2.1, it has taken over a week of high-volume usage for a server to enter this failed state. When the server starts to throw this exception, the number of completed and queued tasks remains fixed.

**Comment by t3hnar** [comment]
I'm experiencing same issue with version `3.2.1`
```
evopcore06 java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@6bfb0b44 rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@6bb83b71[Running, pool size = 64, active threads = 29, queued tasks = 0, completed tasks = 6710731]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
at slick.util.AsyncExecutor$$anon$2$$anon$3.execute(AsyncExecutor.scala:118)
at slick.basic.BasicBackend$DatabaseDef$class.runSynchronousDatabaseAction(BasicBackend.scala:231)
at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:37)
at slick.basic.BasicBackend$DatabaseDef$class.runInContext(BasicBackend.scala:208)
at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:37)
at slick.basic.BasicBackend$DatabaseDef$class.runInternal(BasicBackend.scala:76)
at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:37)
at slick.basic.BasicBackend$DatabaseDef$class.run(BasicBackend.scala:73)
at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:37)
```

**Comment by t3hnar** [comment]
There are also many exceptions like the one above, which occurs just after after sick problems raised.
```
java.lang.IllegalStateException: Promise already completed.
at scala.concurrent.Promise$class.complete(Promise.scala:55)
at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157)
at scala.concurrent.Promise$class.failure(Promise.scala:104)
at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:157)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:257)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
```

**Comment by szeiger** [comment]
Since all kinds of exceptions are piling up here:

@Discipe This is unrelated. The pool has been shut down, probably because database.close() was called. It could be a previous error that led to a shutdown but I'm not even sure such a situation is possible (i.e. the pool would ever initiate a shutdown on its own).

@wkronmiller This looks like a normal overloaded pool. All threads are used, the queue is full. If the situation persists, check for running queries on the database side. Also see https://github.com/slick/slick/issues/1614#issuecomment-285115180.

The other two look like the original problem but I have no idea how this could still happen in 3.2.1.

**Comment by hvesalai** [comment]
Most probably the same as this: #1614

**Comment by hvesalai** [comment]
I have created a series of PRs that most probably fix this or reveal bad configurations leading to this. Please everybody take a look and if you can, test.

https://github.com/slick/slick/pull/1853
https://github.com/slick/slick/pull/1854
https://github.com/slick/slick/pull/1855

**Comment by fancywriter** [comment]
@hvesalai awesome! Where are you going to release it? Is it going to 3.2.2 ?

**Comment by hvesalai** [comment]
Yes, 3.2.2. I will release it soon. I'm waiting for two last PRs to be reviewed.

**Comment by rockjam** [comment]
As far as I understand, this issue should be fixed in 3.2.2 already, but we encountered the bug that looks exactly the same in 3.2.2 anyway.
The setup is:
* slick 3.2.2
* slick-hikaricp 3.2.2
* number of threads and connection pool size  are 20

Here is the stack trace:
```
java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$2@335e47ae rejected from slick.util.AsyncExecutor$$anon$2$$anon$1@11324348[Running, pool size = 20, active threads = 0, queued tasks = 1000, completed tasks = 375006]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at slick.util.AsyncExecutor$$anon$2$$anon$3.execute(AsyncExecutor.scala:161)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:264)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:262)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:241)
	at slick.basic.BasicBackend$DatabaseDef.runInContextSafe(BasicBackend.scala:147)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:171)
	at slick.basic.BasicBackend$DatabaseDef.runInContextSafe(BasicBackend.scala:147)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:171)
	at slick.basic.BasicBackend$DatabaseDef.runInContextSafe(BasicBackend.scala:147)
	at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:141)
	at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:140)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.runInternal(BasicBackend.scala:76)
	at slick.basic.BasicBackend$DatabaseDef.runInternal$(BasicBackend.scala:75)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.run(BasicBackend.scala:73)
	at slick.basic.BasicBackend$DatabaseDef.run$(BasicBackend.scala:73)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:37)
	at com.company.service.services.ReadService.find(ReadService.scala:16)
	at com.company.service.resources.EntityResource$.$anonfun$apply$3(EntityResource.scala:40)
	at akka.http.scaladsl.server.directives.OnSuccessMagnet$$anon$1.$anonfun$directive$2(FutureDirectives.scala:97)
	... 131 frames truncated
```

**Comment by hvesalai** [comment]
@rockjam This is not the same issue. Can you make a new issue where you describe your setup in detail. I will ask more questions there.

**Comment by mahesh2492** [comment]
@hvesalai I am having the same issue.
Slick version 3.3.2
HikariCp Version 3.3.0

`java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$3@5ce93494 rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@2346719[Running, pool size = 20, active threads = 20, queued tasks = 1000, completed tasks = 27339]
`

Please help how can I fix this?

**Comment by hvesalai** [comment]
@mahesh2492 based on the numbers your issue is not the same. It is actually not even a bug, but normal operation. Please consult the documentation or join gitter.im on slick channel to ask questions. This is not a support forum.

**Comment by mahesh2492** [comment]
@hvesalai Thanks for the response. I will ask in slack.
