### ISSUE TITLE
Uncaught exceptions in Slick 3

### ISSUE THREAD

**Issue by nukemichaels** [slick/slick#1737]
I'm facing uncaught exceptions thrown from Slick ThreadPoolExecutor on database errors.
Here is the actual stacktrace:
```
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '17030' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_112]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_112]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.Util.getInstance(Util.java:383) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1049) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4208) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1366) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:829) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262) ~[mysql-connector-java-5.1.32.jar:na]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246) ~[mysql-connector-java-5.1.32.jar:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-2.5.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-2.5.1.jar:na]
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$8.apply(JdbcActionComponent.scala:511) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$8.apply(JdbcActionComponent.scala:508) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:372) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:434) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:502) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:508) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:31) ~[slick_2.11-3.2.0.jar:na]
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28) ~[slick_2.11-3.2.0.jar:na]
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240) ~[slick_2.11-3.2.0.jar:na]
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240) ~[slick_2.11-3.2.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

```
I'm running my DBIOActions with DatabaseDef run method and I expected to handle all DB errors via failure callbacks on Future object retrieved from run method. But this particular exception was thrown outside the expected pipeline, so it can't be handled by client code.
How I can handle such exceptions?

I'm using Slick 3.2.0 + MySQL + Scala 2.11.8

**Comment by trevorsibanda** [comment]
@nukemichaels I hope I'm understanding this right,

You can use ```.onComplete```  on the future returned from db.run or you can use ```.asTry``` on the action

```scala
db.run(action.asTry).onComplete{
    case Success(x) => ...
    case Failure(x) => ...
}
```
