### ISSUE TITLE
a StackOverflow Error caused by endless loop.

### ISSUE THREAD

**Issue by LoranceChen** [slick/slick#1752]
```
java.lang.StackOverflowError
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:172)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:180)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder$$anonfun$expr$7.apply(JdbcStatementBuilderComponent.scala:382)
        at slick.util.SQLBuilder.sep(SQLBuilder.scala:31)
```

Currently,I just has the trace stack info.Does someone has same error?

**Comment by LoranceChen** [comment]
limit data count could solve the problem temporarily

**Comment by LoranceChen** [comment]
It will caused by such query operation:
`db.run(chartScheme.filter(chart => creatorIds.map(chart.creatorId === _).foldLeft(false: Rep[Boolean])(_ || _)).result)`

NOT 100% occurred. All of mysql connection status become CLOSE_WAIT once appear.

**Comment by WellingR** [comment]
I have had this issue occur too. Basically it happens when query conditions are created from collections of 200+ elements using a foldLeft or reduce statement as shown in the comment above

**Comment by hvesalai** [comment]
Monads need to be trampolined.

**Comment by hvesalai** [comment]
Duplicate of #1606
