### ISSUE TITLE
Codegen issues on sqlite3 `SMALLINT UNSIGNED` data type

### ISSUE THREAD

**Issue by jccode** [slick/slick#1771]
`build.sbt`

    lazy val slickVersion = "3.2.1"

    // slick
    libraryDependencies += "com.typesafe.slick" %% "slick" % slickVersion
    libraryDependencies += "com.typesafe.slick" %% "slick-codegen" % slickVersion
    libraryDependencies += "org.xerial" % "sqlite-jdbc" % "3.8.7"

    // slick task
    lazy val slick = taskKey[Seq[File]]("gen-tables")
    slick := {
      val dir = (scalaSource in Compile).value
      val cp = (dependencyClasspath in Compile).value
      val r = (runner in Compile).value
      val s = streams.value
      val outputDir = dir.getPath

      val profile = "slick.jdbc.SQLiteProfile"
      val jdbcDriver = "org.sqlite.JDBC"
      val url = "jdbc:sqlite:/Users/IT/temp/db.sqlite3"
      val pkg = "com.suyun.train.slick.djgen"
      toError(r.run("slick.codegen.SourceCodeGenerator", cp.files, Array(profile, jdbcDriver, url, outputDir, pkg), s.log))
      val fname = outputDir + "/djgen/Tables.scala"

      Seq(file(fname))
    }

Error logs

    [error] (run-main-0) scala.MatchError: SMALLINT UNSIGNED (of class java.lang.String)
    scala.MatchError: SMALLINT UNSIGNED (of class java.lang.String)
        at slick.jdbc.SQLiteProfile$ModelBuilder$$anon$1.<init>(SQLiteProfile.scala:99)
        at slick.jdbc.SQLiteProfile$ModelBuilder.createColumnBuilder(SQLiteProfile.scala:94)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$columns$1(JdbcModelBuilder.scala:162)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
        at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$6(JdbcModelBuilder.scala:95)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$4(JdbcModelBuilder.scala:95)
        at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
        at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContext$1(BasicBackend.scala:147)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    [debug] 	Thread run-main-0 exited.

**Comment by cvogt** [comment]
requires a patch loosely similar to this one: https://github.com/slick/slick/pull/1735

Happy to merge a PR

**Comment by greenhat** [comment]
I've reproduced the exception and fixed it in #1828.
