### ISSUE TITLE
SQL Server collation issue.

### ISSUE THREAD

**Issue by fancywriter** [slick/slick#1801]
Suppose I have the following table in SQL Server database. Don't ask my why.
```
CREATE TABLE people (
first_name VARCHAR(100) COLLATE Latin1_General_CI_AI,
last_name VARCHAR(100) COLLATE Latin1_General_CI_AI_WS NOT NULL
);
```

And the following slick code for it.
```
import slick.jdbc.SQLServerProfile.api._

class People(tag: Tag) extends Table[(Option[String], String)](tag, "people") {
  def firstName = column[Option[String]]("first_name")
  def lastName = column[String]("last_name")

  def * = (firstName, lastName)
}

object People {
  val firstOrLast = TableQuery[People].map(r => r.firstName.getOrElse(r.lastName))
}

import scala.concurrent.Await
import scala.concurrent.duration._

object Main extends App {
  val db = Database.forURL(???) // url to SQL server database, I used localhost
  println(Await.result(db.run(People.firstOrLast.result), 10.seconds))
}
```

I have provided this example in a separate repo (without SQL code) https://github.com/fancywriter/slick-sql-collate

I am getting the following exception:
```
Exception in thread "main" java.sql.SQLException: Implicit conversion of varchar value to varchar cannot be performed because the collation of the value is unresolved due to a collation conflict between "Latin1_General_CI_AI" and "Latin1_General_CI_AI_WS" in CASE operator.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:613)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:572)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:784)
	at slick.jdbc.LoggingPreparedStatement.$anonfun$execute$5(LoggingStatement.scala:153)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:84)
	at slick.jdbc.LoggingPreparedStatement.execute(LoggingStatement.scala:153)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:215)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:215)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:242)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is because the query `TableQuery[People].map(r => r.firstName.getOrElse(r.lastName))` is translated to the following SQL:
```
16:23:43.604 [AsyncExecutor.default-1] DEBUG slick.jdbc.JdbcBackend.statement - Preparing statement: select (case when ("first_name" is null) then "last_name" else "first_name" end) from "people"
```

And if I run it directly in SQL, I am received exactly the same error. However, it's known issue and can be solved easily on SQL side with adding `collate database_default` (or any other collate, just it has to be identical for two columns).
```
select (case when ("first_name" is null) then "last_name" else "first_name" collate database_default end) from "people";
```

It is possible to work around if I use plain SQL http://slick.lightbend.com/doc/3.2.1/sql.html
However, would be awesome if you solve it for types queries too, it can be either done automatically, or possible with some extra methods... like
```
TableQuery[People].map(r => r.firstName.getOrElse(r.lastName).collate(blah-blah-blah))
```

**Comment by hvesalai** [comment]
If you can, please submit a PR to fix this.
