### ISSUE TITLE
Slick in invoking ConfigFactory.load directly without any possibility to override

### ISSUE THREAD

**Issue by pshirshov** [slick/slick#1837]
`ConfigFactory.load` is a bad practice which leads to fragile code which behaves mysteriously under isolated classloaders or in case you have customized config loading routines. For some details check [this issue ](https://github.com/lightbend/config/issues/405) please

Unfortunately slick is promoting bad practices and calling that damn method directly.  I guess you guys should provide a way to alter config loading logic.

```
java.lang.ExceptionInInitializerError: null
	at slick.util.TreePrinter$.<init>(TreePrinter.scala:70)
	at slick.util.TreePrinter$.<clinit>(TreePrinter.scala)
	at slick.basic.BasicBackend$DatabaseDef.logAction(BasicBackend.scala:335)
	at slick.basic.BasicBackend$DatabaseDef.logAction$(BasicBackend.scala:330)
	at slick.jdbc.JdbcBackend$DatabaseDef.logAction(JdbcBackend.scala:38)
	at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:143)
	at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:142)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:38)
	at slick.basic.BasicBackend$DatabaseDef.runInternal(BasicBackend.scala:78)
	at slick.basic.BasicBackend$DatabaseDef.runInternal$(BasicBackend.scala:77)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:38)
	at slick.basic.BasicBackend$DatabaseDef.run(BasicBackend.scala:75)
	at slick.basic.BasicBackend$DatabaseDef.run$(BasicBackend.scala:75)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:38)
    <strip>
	at akka.stream.impl.fusing.Map$$anon$7.onPush(Ops.scala:47)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:488)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:541)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:659)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:707)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalStateException: Default config loading is prohibited!
	at org.bitbucket.pshirshov.izumitk.config.FailingConfigLoadingStrategy.parseApplicationConfig(NamedConfigLoadingStrategy.scala:37)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:256)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:256)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:232)
	at slick.util.GlobalConfig$.<init>(GlobalConfig.scala:19)
	at slick.util.GlobalConfig$.<clinit>(GlobalConfig.scala)
	... 45 common frames omitted
```

**Comment by tavoaqp** [comment]
Yes, having a hard time here too with this issue. This makes impossible to test custom application configuration files!

**Comment by mfulgo** [comment]
In my use case, I have references in my `application.conf` that must be resolved with a custom `ConfigResolver`. Since this call to `.load()` ultimately uses `ConfigResolveOptions.default()`, without allowing me to append the custom resolver, Slick blows up when I try to make the first connection.

**Comment by kbreidenbach** [comment]
Any chance this is being worked on s it seems like an anti-pattern to me?

**Comment by hvesalai** [comment]
No, I haven't seen anybody make a PR about it. As said, all good PRs are welcome.

**Comment by tavoaqp** [comment]
Actually I solved it by calling like this:
`env JAVA_OPTS="-Dconfig.file=./src/test/resources/test-application.conf" sbt test`
In my case I need to do this because the configuration for the test environment is specific. This solved my problem but I still think that a better pattern could be adopted by Slick.

**Comment by pshirshov** [comment]
@tavoaqp : there are even better options, like not to use libraries which does not allow you to control your contexts. We migrated to doobie and feel bit better now.

**Comment by tavoaqp** [comment]
@pshirshov : Very interesting stuff! I will try doobie!

**Comment by adrianomelo** [comment]
I found an alternative to it. I am keeping only the static configuration at `application.conf`.

```
# Some example for application.conf
http {
  port: 8081
}

```

If the project needs something dynamic, I move it to a different conf file (let's say, `application-dynamic.conf`).
```
# Some example for application-dynamic.conf
include "application.conf"

slick {
  dbs {
     default {
        profile: "slick.jdbc.MySQLProfile$"
        db {
           driver: ${database.driver}
           url: ${someconfig.database.url}
           user: ${someconfig.database.user}
           password: ${someconfig.database.password}
        }
     }
  }
}
```

The problem is this line: https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/GlobalConfig.scala#L19

**Comment by caeus** [comment]
@adrianomelo Still, an ugly workaround... And nobody seems to be fixing it

**Comment by dwalend** [comment]
Same problem in SHRINE. We need to be able to pass in the .conf file we want slick to use at a minimum, would prefer to pass in a Config instance.
