### ISSUE TITLE
Unsigned Type for LiteralNode

### ISSUE THREAD

**Issue by kuzmycz** [slick/slick#1843]
I implemented a SimpleExpression to allow a full text search in MySql. 

`  object SearchModifier extends Enumeration {
    val InBooleanMode = Value("IN BOOLEAN MODE")
    val InNaturalLanguageMode = Value("IN NATURAL LANGUAGE MODE")
    val InNaturalLanguageModeWithQueryExpansion = Value("IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION")
    val WithQueryExpansion = Value("WITH QUERY EXPANSION")
  }

  case class Match(cols: Rep[_]*) {
    def against(what: Rep[_], modifier: SearchModifier.Value = SearchModifier.InNaturalLanguageMode) =
      SimpleExpression[Boolean] {
        case (nodes, qb) =>
          qb.sqlBuilder += "MATCH("
          qb.sqlBuilder.sep(nodes, ", ")(qb.expr(_))
          qb.sqlBuilder += ") AGAINST("
          qb.expr(what.toNode)
          qb.sqlBuilder += " "
          qb.sqlBuilder += modifier.toString
          qb.sqlBuilder += ")"
      }.apply(cols)
  }
`

The problem is when you use a string literal you get the exception:

`slick.SlickException: JdbcProfile has no JdbcType for type UnassignedType
	at slick.jdbc.JdbcTypesComponent.jdbcTypeFor(JdbcTypesComponent.scala:74)
	at slick.jdbc.JdbcTypesComponent.jdbcTypeFor$(JdbcTypesComponent.scala:59)
	at slick.jdbc.MySQLProfile$.jdbcTypeFor(MySQLProfile.scala:330)
	at slick.jdbc.JdbcTypesComponent$JdbcType$.unapply(JdbcTypesComponent.scala:56)
	at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:311)
	at slick.jdbc.MySQLProfile$QueryBuilder.expr(MySQLProfile.scala:195)
	at models.CustomSlickTypes$Match.$anonfun$against$1(CustomSlickTypes.scala:35)
	at models.CustomSlickTypes$Match.$anonfun$against$1$adapted(CustomSlickTypes.scala:30)
	at models.CustomSlickTypes$Match$$Lambda$4668/772236251.apply(Unknown Source)
	at slick.lifted.SimpleExpression$$anon$3.toSQL(SimpleFunction.scala:81)
`

The code I used to execute the simple expression is:
`    (for {
      c <- conversations if Match(c.from.name, c.transcript).against("Hello", SearchModifier.InBooleanMode)
    } yield c).result.statements.mkString
`

What I have found is that Slick turns the literal string "Hello" into a LiteralNode with the type of UnsignedType. Which leads to the exception.

**Comment by hvesalai** [comment]
Please post this as a question to one of the community forums and reopen if you think it is really a bug.
