### ISSUE TITLE
AsyncExecutor requirement failed: count cannot be decreased

### ISSUE THREAD

**Issue by hvesalai** [slick/slick#1856]
When shutting down, this exception can sometimes be seen.

```
Exception in thread "AsyncExecutor.default-17" java.lang.IllegalArgumentException: requirement failed: count cannot be decreased
	at scala.Predef$.require(Predef.scala:224)
	at slick.util.ManagedArrayBlockingQueue$$anonfun$decreaseInUseCount$1.apply$mcV$sp(ManagedArrayBlockingQueue.scala:54)
	at slick.util.ManagedArrayBlockingQueue$$anonfun$decreaseInUseCount$1.apply(ManagedArrayBlockingQueue.scala:53)
	at slick.util.ManagedArrayBlockingQueue$$anonfun$decreaseInUseCount$1.apply(ManagedArrayBlockingQueue.scala:53)
	at slick.util.ManagedArrayBlockingQueue.locked(ManagedArrayBlockingQueue.scala:202)
	at slick.util.ManagedArrayBlockingQueue.decreaseInUseCount(ManagedArrayBlockingQueue.scala:53)
	at slick.util.AsyncExecutor$$anon$2$$anon$1.afterExecute(AsyncExecutor.scala:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lenin122** [comment]
We still have this issue with Slick 3.3.2 inside Play Framework with play-slick 5.0.0
Exception in thread "db-5" java.lang.IllegalArgumentException: requirement failed: count cannot be decreased

We are using rather heavy queries inside transactional block and before we get timeout exception on get connection, we see this error.

**Comment by nafg** [comment]
If you have the issue with Slick 3.4.0-M1 then please reopen this, otherwise there isn't anything to do on Slick's end
