### ISSUE TITLE
java.lang.StackOverflowError when use more condition and Concurrent environment

### ISSUE THREAD

**Issue by hongBry** [slick/slick#1895]
java.lang.StackOverflowError
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:55)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)

        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
        at slick.util.ConstArray.endoMap(ConstArray.scala:122)
        at slick.ast.Node.mapChildren(Node.scala:50)
        at slick.ast.Node.mapChildren$(Node.scala:48)
        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
        at slick.util.ConstArray.endoMap(ConstArray.scala:122)
        at slick.ast.Node.mapChildren(Node.scala:50)
        at slick.ast.Node.mapChildren$(Node.scala:48)
        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
        at slick.util.ConstArray.endoMap(ConstArray.scala:122)
        at slick.ast.Node.mapChildren(Node.scala:50)
        at slick.ast.Node.mapChildren$(Node.scala:48)
        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)

**Comment by hvesalai** [comment]
@hongBry please follow the instructions on how to file a bug report. This report is missing many details -- such as, for example -- how to reproduce it. I will re-open this once you have provided the required information.
