### ISSUE TITLE
java.lang.StackOverflowError when using reduceLeft on filter in high concurrency

### ISSUE THREAD

**Issue by hongBry** [slick/slick#1896]
slick version is 3.2.1

Reported on  postgres profiles.

i use reduceLeft in the filter clause, there may be a java.lang.StackOverflowError, if the Array reduced is too big（>30） in high concurrency.
it will occur the StackOverflowError error.

Some stacktrace:
java.lang.StackOverflowError
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:55)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)

        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
        at slick.util.ConstArray.endoMap(ConstArray.scala:122)
        at slick.ast.Node.mapChildren(Node.scala:50)
        at slick.ast.Node.mapChildren$(Node.scala:48)
        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
        at slick.util.ConstArray.endoMap(ConstArray.scala:122)
        at slick.ast.Node.mapChildren(Node.scala:50)
        at slick.ast.Node.mapChildren$(Node.scala:48)
        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)
        at slick.util.ConstArray.endoMap(ConstArray.scala:122)
        at slick.ast.Node.mapChildren(Node.scala:50)
        at slick.ast.Node.mapChildren$(Node.scala:48)
        at slick.ast.Apply.mapChildren(Node.scala:546)
        at slick.compiler.AssignUniqueSymbols.tr$1(AssignUniqueSymbols.scala:56)
        at slick.compiler.AssignUniqueSymbols.$anonfun$apply$8(AssignUniqueSymbols.scala:56)

**Comment by hongBry** [comment]
i found the fault.
i use the ‘ls’ has same elem

    val query = tPosts.filter{ p =>
      val a = ls.map{
        l =>
          p.origin === l._3 && p.boardName === l._1 && p.postId === l._2
      }
      a.reduceLeft(_ || _)
    }
    db.run{query.result}

it will report the stackoverflowError
