### ISSUE TITLE
slick result unable to send as akka message

### ISSUE THREAD

**Issue by liaolunhui** [slick/slick#1906]
` sender()  !  ScalaTools.syncSlick(utils.Tables.Markets.result)`
utils.Tables are made by slick codegen
ScalaTools.syncSlick use Await.result to sync the result

The error is as the flowing:

[ERROR] [05/16/2018 11:04:14.888] [trade-akka.remote.default-remote-dispatcher-8] [akka.tcp://trade@10.0.1.219:2552/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FMySpec%4010.0.1.219%3A6666-0/endpointWriter] Failed to serialize remote message [class scala.collection.immutable.Vector] using serializer [class akka.serialization.JavaSerializer]. Transient association error (association remains live)
akka.remote.MessageSerializer$SerializationException: Failed to serialize remote message [class scala.collection.immutable.Vector] using serializer [class akka.serialization.JavaSerializer].
	at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:62)
	at akka.remote.EndpointWriter.$anonfun$serializeMessage$1(Endpoint.scala:898)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.remote.EndpointWriter.serializeMessage(Endpoint.scala:898)
	at akka.remote.EndpointWriter.writeSend(Endpoint.scala:788)
	at akka.remote.EndpointWriter$$anonfun$4.applyOrElse(Endpoint.scala:763)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.remote.EndpointActor.aroundReceive(Endpoint.scala:454)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.NotSerializableException: utils.Tables$
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at akka.serialization.JavaSerializer.$anonfun$toBinary$1(Serializer.scala:333)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at akka.serialization.JavaSerializer.toBinary(Serializer.scala:333)
	at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:47)
	... 17 more

**Comment by hvesalai** [comment]
We will not implement this unless somebody provides a PR for it.
