### ISSUE TITLE
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption

### ISSUE THREAD

**Issue by sanjarbek** [slick/slick#1911]
I wrote here because didn't know any community forum about slick.
My app worked on prod until yesterday. It is simply generate pdf document by getting data from ms sql server.
Now I am getting this error:
`Exception in thread "main" java.sql.SQLTransientConnectionException: myroute.db - Connection is not available, request timed out after 5009ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server did not return a response. The connection has been closed. ClientConnectionId:1a35707f-0c00-42bc-9168-0540a715069d".
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2670)
	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1837)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2257)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
`
The same app work on my laptop, but not on the server.
`libraryDependencies ++= Seq(
  "com.itextpdf" % "kernel" % "7.1.0",
  "com.itextpdf" % "layout" % "7.1.0",
  "com.itextpdf" % "io" % "7.1.0",
  "com.typesafe.slick" %% "slick" % "3.2.3",
  "org.slf4j" % "slf4j-nop" % "1.6.4",
  "com.typesafe.slick" %% "slick-hikaricp" % "3.2.3",
  "com.microsoft.sqlserver" % "mssql-jdbc" % "6.1.0.jre8",
  "org.postgresql" % "postgresql" % "42.2.2"
)`
Please help!

**Comment by sanjarbek** [comment]
@hvesalai thank you for replay. I will write on there.
