### ISSUE TITLE
SimpleArrayUtils.fromString fails when parsing some valid expression

### ISSUE THREAD

**Issue by klpx** [slick/slick#1934]
**DESCRIPTION:**

SimpleArrayUtils.fromString fails when parses quoted element with the first character is closing round bracket at the beginning.

**STEPS TO REPRODUCE:**

```
SimpleArrayUtils.fromString(identity)("""{")"}""")
```

**EXPECTED RESULT:**

`Seq(")")`

**ACTUAL RESULT:**

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1(PgTokenHelper.scala:232)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1$adapted(PgTokenHelper.scala:166)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.grouping(PgTokenHelper.scala:166)
	at com.github.tminglei.slickpg.utils.SimpleArrayUtils$.fromString(SimpleArrayUtils.scala:13)
	... (scratch trace)
(no root cause)
```

**NOTICE:**

Cases `{)}` and `{"prefix)"}` works fine. Cases `{"other",")"}` and `{")suffix"}` also fails.

**SETUP:**

No setup needed.

**Comment by hvesalai** [comment]
Well described bug! Would you happen to have a PR to fix it?

**Comment by klpx** [comment]
Hmm I am going to look

**Comment by klpx** [comment]
Oops that helper is from slick-pg repository, moving there
