### ISSUE TITLE
SQLite ModelBuilder Regex bug

### ISSUE THREAD

**Issue by GlulkAlex** [slick/slick#1939]
I'm trying to extract a [db](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite_AutoIncrementPKs.sqlite) schema  to build tables models  
e.g. for this table:   
```SQL
CREATE TABLE [Invoice]
(
    -- ...
    [Total] NUMERIC(10,2)  NOT NULL,
    -- ...
);
```
and I got an exception:
```
scala.MatchError: NUMERIC(10,2) (of class java.lang.String)
	at slick.jdbc.SQLiteProfile$ModelBuilder$$anon$1.<init>(SQLiteProfile.scala:99)
	at slick.jdbc.SQLiteProfile$ModelBuilder.createColumnBuilder(SQLiteProfile.scala:94)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$columns$1(JdbcModelBuilder.scala:162)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
	at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$6(JdbcModelBuilder.scala:95)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$4(JdbcModelBuilder.scala:95)
	at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
	at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:171)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```  
I think that cased by this expression: 
https://github.com/slick/slick/blob/5013db0fb332379bcccad1f654f8c40b4ffbc7d7/slick/src/main/scala/slick/jdbc/SQLiteProfile.scala#L99  
e.g. following test snippet recreates the original error:  
```Scala
scala> val TypePattern = "^([A-Z\\s]+)(\\(([0-9]+)\\))?$".r
TypePattern: scala.util.matching.Regex = ^([A-Z\s]+)(\(([0-9]+)\))?$

scala> "NUMERIC(10,2)" match {
     |           case TypePattern(d,_,s) => (d, Option(s).map(_.toInt))
     |           case "" => ("TEXT", None)
     |         }
scala.MatchError: NUMERIC(10,2) (of class java.lang.String)
  ... 39 elided
```  
as a workaround I wrote my own extension for `SQLiteProfile`  
with override for `createModelBuilder`  
where replaced RegEx pattern with this function:  
```scala
/** Regex matcher 
to extract name and length 
out of a db type name 
with length ascription */
def extract( 
  s: String = "NUMERIC(10,2)"
, pattern: scala.util.matching.Regex = "^([A-Z\\s]+)(\\(([0-9]+),?([0-9]+)?\\))?$".r
): ( String, Option[ Int ] ) = s match {
  case pattern( 
    name_Group, numeric_Group, integer_Group, fractional_Group 
  ) => ( name_Group, Option( integer_Group ).map( _.toInt ) )
  case "" => ( "TEXT", None )
}
private 
      val ( _dbType, _size ) = extract( 
        s = meta.typeName
      , pattern = "^([A-Z\\s]+)(\\(\\s?([0-9]+)\\s?,?\\s?([0-9]+)?\\s?\\))?$".r 
      )
```

**Comment by trevorsibanda** [comment]
Hi @GlulkAlex 

Do you mind submitting this as a pull request and adding the test case to the sqlite schema used by the codegen tests.

**Comment by GlulkAlex** [comment]
Hi @trevorsibanda, 
I don't know much 
about the sqlite schema and the codegen tests yet, 
but I'll see what I can do .

**Comment by GlulkAlex** [comment]
Also 
after exploring [Affinity Name Examples](https://www.sqlite.org/datatype3.html#affinity_name_examples) 
I'm not sure 
that use of `NUMERIC(10,2)` ( instead of `DECIMAL(10,2)` ) 
in the column type definition 
for tables in [Chinook_Sqlite db](https://raw.githubusercontent.com/lerocha/chinook-database/master/ChinookDatabase/DataSources/Chinook_Sqlite.sql) 
was entirely appropriate .
