### ISSUE TITLE
SQLite codegen fails with java.util.NoSuchElementException

### ISSUE THREAD

**Issue by samikrc** [slick/slick#1955]
**DESCRIPTION:**

When I try to generate the schema from a database, I get java.util.NoSuchElementException on one of the column names.

**STEPS TO REPRODUCE:**

Attaching a very small database which produces the error, when trying to generate code with the following snippet. Note: the attachment is zipped.
[apollo.db.zip](https://github.com/slick/slick/files/2435017/apollo.db.zip)

```
object TableCodeGenerator extends App
{
    slick.codegen.SourceCodeGenerator.main(Array(
        "slick.jdbc.SQLiteProfile",
        "org.sqlite.JDBC",
        "jdbc:sqlite:/home/samik/db/apollo.db",
        "/home/samik/git/project/src/main/scala",
        "full.qualified.name")
    )
}
```

**EXPECTED RESULT:**

Expected to see the table schema in a scala file.

**ACTUAL RESULT:**

Here is the stack trace:
```
Exception in thread "main" java.util.NoSuchElementException: key not found: clientid
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at slick.jdbc.JdbcModelBuilder$PrimaryKeyBuilder.model(JdbcModelBuilder.scala:291)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.primaryKey$lzycompute(JdbcModelBuilder.scala:166)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.primaryKey(JdbcModelBuilder.scala:166)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:95)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:95)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:95)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3.apply(JdbcModelBuilder.scala:92)
	at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
	at slick.dbio.DBIOAction$$anonfun$map$1.apply(DBIOAction.scala:43)
	at slick.basic.BasicBackend$DatabaseDef$$anonfun$slick$basic$BasicBackend$DatabaseDef$$runInContextInline$1.apply(BasicBackend.scala:171)
	at slick.basic.BasicBackend$DatabaseDef$$anonfun$slick$basic$BasicBackend$DatabaseDef$$runInContextInline$1.apply(BasicBackend.scala:171)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**SETUP:**

The database has to exist at the path mentioned in the code. Using sqlite-jdbc v3.8.7 and Slick v3.2.3. 

**NOTES:**
It seems to me from the error that some case mismatch is going on. In this database, there are a few fields which uses camel casing, e.g., the field mentioned in the stacktrace is provided as 'clientId', however some code is trying to find a key named "clientid". Another table which has all the column names in lower case didn't have any issue.

**Comment by samikrc** [comment]
I am using sqlite database in this case, however looks like in general it would probably be a better idea to treat column names as case sensitive.
