### ISSUE TITLE
Postgres profile in 3.3.0 fails to parse some timestamps when Instant is used

### ISSUE THREAD

**Issue by WellingR** [slick/slick#2005]
**DESCRIPTION:**

Our database classes used the `Instant` type rather than `java.sql.Timestamp` already in slick 3.2.x because we had defined an implicit `BaseColumnType[Instant]` in scope. As of 3.3.0 this BaseColumnType is no longer used because slick now supports some of the java.time types such as `Instant` by default.

Our database schema uses the `TIMESTAMP WITH TIMEZONE` type, because the timestamp without timezone has some DST issues. Since the `Instant` type is relative to the standard Java epoch of 1970-01-01T00:00:00Z (and therefore does not have DST issues), this is exactly what we need.

Unfortunately, when reading values with the type `TIMESTAMP WITH TIMEZONE` from the postgres database, the parsing of the timestamps seems to fail.

**STEPS TO REPRODUCE:**

Using postgres 
Create a table with a `TIMESTAMP WITH TIMEZONE` field and insert a value (works) then read the value back again.

**EXPECTED RESULT:**

Everything works fine as it did in Slick 3.2.x

**ACTUAL RESULT:**

```
java.time.format.DateTimeParseException: Text '2019-03-26 20:33:03.43661+01' could not be parsed at index 10
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at java.base/java.time.Instant.parse(Instant.java:395)
	at slick.jdbc.PostgresProfile$JdbcTypes$InstantJdbcType.getValue(PostgresProfile.scala:412)
	at slick.jdbc.PostgresProfile$JdbcTypes$InstantJdbcType.getValue(PostgresProfile.scala:382)
	at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:26)
	at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:53)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:43)
	at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:133)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:53)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:43)
	at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
	at slick.jdbc.StatementInvoker$$anon$2.extractValue(StatementInvoker.scala:66)
	at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
	at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
	at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
	at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
	at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
	at slick.jdbc.Invoker.foreach(Invoker.scala:48)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:216)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:216)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Alternative timestamp error message (tested with Asia/Calcutta Time Zone)
```
java.time.format.DateTimeParseException: Text '2019-03-27 01:16:25.512783+05:30' could not be parsed at index 10
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
...
```

**WORKAROUND:**

Currently it is possible to work around this by overriding the `instantType` in the postgres profile. This can be done as follows:

```scala
        new PostgresProfile {
          override val columnTypes: JdbcTypes = new JdbcTypes {
            override val instantType: InstantJdbcType = new InstantJdbcType {
              private[this] val formatter = {
                new DateTimeFormatterBuilder()
                  .append(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
                  .optionalStart()
                  .appendFraction(ChronoField.NANO_OF_SECOND, 0, 6, true)
                  .optionalEnd()
                  .optionalStart()
                  .appendOffset("+HH:mm:ss", "+00")
                  .optionalEnd()
                  .toFormatter()

              }
              override implicit val parseFiniteTime: String => Instant = {
                s => Instant.from(formatter.parse(s))
              }
            }
          }
        }
```

**Comment by hvesalai** [comment]
> Since the Instant type is relative to UTC, this is exactly what we need, and I do not understand the choice made by slick to map the Instant type to UTC by default.

What do you mean "Instant is relative to UTC ...  do not understand ... map the Instant type to UTC"?

That sounds like you are contradicting your self. 

First of all UTC is not a timezone, it is a standard for timezones. Furthermore Instant is NOT a date time in the same way as all DateTime and LocalDateTime, and it is not expressed in the UTC system. Instant is a point on the time-line measured by the number of nanoseconds that have passed since 1970-01-01T00:00:00Z. 

As such, you are correct that we are not using the best approach to store it. The best approach would have been to store Instant as a Number rather than a Timestamp.

Storing a timezone with Instant sounds backwards to me. What is it that you are trying to achieve with this choise? Why don't you use ZonedDateTime instead?

**Comment by WellingR** [comment]
> What do you mean "Instant is relative to UTC ... do not understand ... map the Instant type to UTC"?
> That sounds like you are contradicting your self.

You are correct, my wording was not clear. I have changed the issue description. Also by relative to UTC i meant relative to 1970-01-01T00:00:00Z (changed that in the issue description too).

I also meant to ask the following (since it seems a separate issue, I removed it from the original issue description):

I do not understand why it has been chose to map the java type `Instant` to the SQL type `TIMESTAMP` in the postgres profile. (while for some other database profiles the SQL type `TIMESTAMP WIHT TIME ZONE` has been used.

**Comment by WellingR** [comment]
> Storing a timezone with Instant sounds backwards to me. What is it that you are trying to achieve with this choise? Why don't you use ZonedDateTime instead?

In the past our application had some issues with time offsets. I believe that sometimes database timestamps had a 1 hour offset because of DST changes. Furthermove, if no timezone is included there is 1 hour in each year which occurs twice. Therefore timestamps in that hour may refer to two points in time, but it is unclear which.

This is why, in my opinion, using `TIMESTAMP WITH TIME ZONE` is better.

The postgres docs contain the following: (see https://www.postgresql.org/docs/9.6/datatype-datetime.html)
> All timezone-aware dates and times are stored internally in UTC. They are converted to local time in the zone specified by the TimeZone configuration parameter before being displayed to the client.

For my scenario this is exactly what I need. I do not want to preserve the original time zone or time offset of the timestamp. I just want to know the moment in time at which something happened. Therefore the java type `Instant` seems like the best tool for the job.
In addition, since `OffsetDateTime` and `ZonedDateTime` are stored as `VARCHAR` by slick. These do not seem to be good choices at all.

**Comment by hvesalai** [comment]
> Furthermove, if no timezone is included there is 1 hour in each year which occurs twice. 

This only happens if you are not providing any TZ with the string that is given to Postgres. Here is a quote from the documentation: _If no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's TimeZone parameter, and is converted to UTC using the offset for the timezone zone._ (as a side note, I would strongly recommend always running all systems in UTC, so setting both psql and java default timezone to that).

However, Slick includes a timezone with the Instant when it is written to the database. It uses the `.toString` method of Instant, yielding strings, such as `2019-03-27T08:15:52.194Z`, with Z meaning UTC+0. As is, there should be no double hours for the way slick uses Instant.

Having said that, I don't think you need a timezone for your use case. When parsing Instants, you expect the DB to provide the timestamps in Zulu time and when you write them, you specify Z.

I concur with you that OffsetDateTime and ZonedDateTime are not very usefull at all (not just in Slick, but more generally also). I would not use them in use cases where I needed to do time arithmetics. The only use I can find for them is to preserve an user input or similar user displayable string.

**Comment by WellingR** [comment]
I think you may be right that I do not need the timezone for my usecase. I think in a previous situation we did not include time timezone when it was written to the database which was causing the DST issues.

Still, it would be good if slick can convert all timestamps from postgres to an Instant (with timezone or not). Since I prefer not changing the db schema of the system we are running in production unless absolutely needed.
With #2006 I add support for parsing timestamps received from postgres in cases where a timestamp is included. Which gives users the freedom to choose between `TIMESTAMP` and `TIMESTAMP WITH TIME ZONE`

**Comment by hvesalai** [comment]
Yes, I'm with you that it doesn't harm to be able to parse the timestamp. So that's why I said in the PR that I support it.
