### ISSUE TITLE
Create if not exists produces already exceptions on each run with multiple key index

### ISSUE THREAD

**Issue by ASchmidt84** [slick/slick#2117]
**Description:**
On a Lagom project on each run an readside the globalprepare methods call the slick createIfNotExists method. On single keys their is no exception thrown to anytime. On a multiple key index an error will be thrown.

**Setup**
Using Slick 3.3.2 wiht scala 2.13

Table and Data
```
case class FulfillerUserProcessorData(username: String,
                                        vendorNumber: Option[String],
                                        entityId: UUID)

  class FulfillerUserProcessorTable(tag: Tag) extends Table[FulfillerUserProcessorData](tag,"fulfiller_user_repository") {

    def username = column[String]("username")
    def vendorNumber = column[Option[String]]("vendor_number")
    def entityId = column[UUID]("entity_id")

    def uniqueIndex = index("username_entity_unique_idx",(username,entityId),unique = true)

    def * = (username,vendorNumber,entityId) <> ( FulfillerUserProcessorData.tupled, FulfillerUserProcessorData.unapply )

  }
```

**Exception**
On each run the createIfNotExists (AFTER) first creation (which runs with no problems)
```
07:41:33.800 [error] akka.actor.OneForOneStrategy [akkaAddress=akka://fulfiller-article-management-impl-application@127.0.0.1:64063, sourceThread=fulfiller-article-management-impl-application-akka.actor.default-dispatcher-30, akkaSource=akka://fulfiller-article-management-impl-application/user/readSideGlobalPrepare-ArticleProcessor-singleton/singleton/readSideGlobalPrepare-ArticleProcessor, sourceActorSystem=fulfiller-article-management-impl-application, akkaTimestamp=05:41:33.799UTC] - ERROR: relation "article_number_fulfiller_idx" already exists
  Ort: Datei: index.c, Routine: index_create, Zeile: 884.
  Server SQLState: 42P07
org.postgresql.util.PSQLException: ERROR: relation "article_number_fulfiller_idx" already exists
  Ort: Datei: index.c, Routine: index_create, Zeile: 884.
  Server SQLState: 42P07
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$7(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$7$adapted(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$6(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$6$adapted(JdbcActionComponent.scala:292)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.run(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.run(JdbcActionComponent.scala:290)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
To look what happens I printed out the generated SQL Script

Generated SQL Script
```
create table if not exists "fulfiller_user_repository" ("username" VARCHAR NOT NULL,"vendor_number" VARCHAR,"entity_id" UUID NOT NULL)
---
create unique index "username_entity_unique_idx" on "fulfiller_user_repository" ("username","entity_id")
```

**Expected behavior**
I expected no exceptions because the table already exists. Either the creation process should be canceld in this case or the index creation should contain an if not exists like this:

```
create unique index if not exists "username_entity_unique_idx" on "fulfiller_user_repository" ("username","entity_id")
```

**Comment by hvesalai** [comment]
You must define a primary key for the feature to work. So far you have only defined an unique index, which is not the same.

**Comment by ASchmidt84** [comment]
Hi hvesalai,

sorry but this also not work like expected. I changed like you said
```
case class FulfillerUserProcessorData(pkHelper:String,
                                        username: String,
                                        vendorNumber: Option[String],
                                        entityId: UUID)

  class FulfillerUserProcessorTable(tag: Tag) extends Table[FulfillerUserProcessorData](tag,FulfillerUserProcessorTable.TableName) {

    def primaryKeyHelper = column[String]("pk_helper",O.PrimaryKey)
    def username = column[String]("username")
    def vendorNumber = column[Option[String]]("vendor_number")
    def entityId = column[UUID]("entity_id")

    def uniqueIndex = index("username_entity_unique_idx",(username,entityId),unique = true)

    def * = (primaryKeyHelper,username,vendorNumber,entityId) <> ( FulfillerUserProcessorData.tupled, FulfillerUserProcessorData.unapply )

  }
```
and added a primary key. Even I change the index to primary key the second run produces this error.

```
08:16:56.396 [error] akka.actor.OneForOneStrategy [akkaAddress=akka://full-filler-management-impl-application@127.0.0.1:54189, sourceThread=full-filler-management-impl-application-akka.actor.default-dispatcher-32, akkaSource=akka://full-filler-management-impl-application/system/sharding/FulfillerUserProcessor/de.athene.fullFillerManagement.impl.fuliller.Fulfiller%24Event2/de.athene.fullFillerManagement.impl.fuliller.Fulfiller%24Event2/backoff-FulfillerUserProcessor-de.athene.fullFillerManagement.impl.fuliller.Fulfiller%24Event2/FulfillerUserProcessor-de.athene.fullFillerManagement.impl.fuliller.Fulfiller%24Event2, sourceActorSystem=full-filler-management-impl-application, akkaTimestamp=06:16:56.379UTC] - ERROR: relation "username_entity_unique_idx" already exists
  Ort: Datei: index.c, Routine: index_create, Zeile: 884.
  Server SQLState: 42P07
org.postgresql.util.PSQLException: ERROR: relation "username_entity_unique_idx" already exists
  Ort: Datei: index.c, Routine: index_create, Zeile: 884.
  Server SQLState: 42P07
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$7(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$7$adapted(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$6(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$6$adapted(JdbcActionComponent.scala:292)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.run(JdbcActionComponent.scala:292)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.run(JdbcActionComponent.scala:290)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by hvesalai** [comment]
Please show that it doesn't work when you remove the `uniqueIndex` completely. Just comment it out and reproduce.

**Comment by hvesalai** [comment]
@ASchmidt84 if you need help, you should use one of the community channels, such as the slick gitter.im channel.

The above error is trivial, the error message is very clear: `ERROR: relation "username_entity_unique_idx" already exists`

**Comment by ASchmidt84** [comment]
Yes it works fine if i remove the unqiueIndex. But then I have not an unqiue index. 
And yes the error is absolutly clear. But I expected when I start my program and command to create if not exists it throws an error because it exists. But it should throw an error like this, because command was create it WHEN it NOT exists. That is the issue. So I would expected a "if not exists" also in the index create statement.

**Comment by hvesalai** [comment]
Hmm... ok. It's a know issue

https://github.com/lagom/lagom/issues/1720

#1999

**Comment by ASchmidt84** [comment]
Thank you
