### ISSUE TITLE
Authentication scheme errors in use with Postgres

### ISSUE THREAD

**Issue by alivcor** [slick/slick#2172]
**DESCRIPTION:**

When using Slick and HickariCP with PostgreSQL out of the box on Mac OS, client throws errors related to encryption

**STEPS TO REPRODUCE:**

1. Download and install latest version of PostgreSQL from the website - 
2. Use the configuration described on the [documentation page](https://scala-slick.org/doc/3.3.0/database.html) and code in [examples](https://github.com/slick/slick/blob/v3.3.0/doc/code/FirstExample.scala) to create a connection. 
3. Observe the following error

Just using _Slick_
```
An error has occurred: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
```

Using _Slick + HikariCP_
```
org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
	at org.postgresql.Driver$ConnectThread.getResult(Driver.java:365)
	at org.postgresql.Driver.connect(Driver.java:288)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:88)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:71)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**EXPECTED RESULT:**

Connection goes through without any errors and creates the two tables

**ACTUAL RESULT:**

Error message above

**SETUP:**

build.sbt

```scala
libraryDependencies ++= Seq(
    "com.typesafe.slick" %% "slick" % "3.3.0",
    "org.slf4j" % "slf4j-nop" % "1.6.4",
    "com.typesafe.slick" %% "slick-hikaricp" % "3.3.0",
    "org.postgresql" % "postgresql" % "9.4-1206-jdbc42" //org.postgresql.ds.PGSimpleDataSource dependency
)
```

Also tried with `"org.postgresql" % "postgresql" % "42.2.5"` to no avail (throws `java.lang.NoClassDefFoundError: org/postgresql/shaded/com/ongres/scram/client/ScramClient$ChannelBinding`)

Tried with and without _HikariCP_:

```
pgsql1 = {
  url = "jdbc:postgresql://localhost:5432/mydb"
  driver = org.postgresql.Driver
  connectionPool = disabled
  keepAliveConnection = true
  user = "postgres"
  password = "postgres"
}
```

```
pgsql2 = {
  connectionPool = "HikariCP" //use HikariCP for our connection pool
  dataSourceClass = "org.postgresql.ds.PGSimpleDataSource" //Simple datasource with no connection pooling. The connection pool has already been specified with HikariCP.
  properties = {
    serverName = "localhost"
    portNumber = "5432"
    databaseName = "mydb"
    user = "postgres"
    password = "postgres"
  }
  numThreads = 10
}
```

Is Slick really certified to work with Postgres ? Has this been tested recently ? Thanks in advance

**Comment by PAStheLoD** [comment]
PostgreSQL defaults to using scram-sha-256 instead of the old md5 for password encryption. Modify password_encryption in  postgresql.conf and then change pg_hba.conf too. (You probably have to reset the password for the user too.)

Or if it's possible to pass the right flags to the underlying JDBC driver, then that should work too. (Since version 42.2 the driver has support for this and Slick seems to depend on version 42.2.5, though I have no idea how to pass this configuration.)

**Comment by alivcor** [comment]
Thanks @PAStheLoD - that was the temporary route I took (chainging encryption to md5 and updating pg_hba.conf entries, then resetting the password. 

Wanted to check if there was a better way of doing this.

Adding steps here if someone comes across:

1. Modify `pg_hba.conf` - for MacOS it should be under /Library/PostgreSQL/13/share/postgresql

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
host    all             all             127.0.0.1/32            md5
```

If you wish to allow all ip addresses and ports, substitute last line with 0.0.0.0/0

2. Modify encryption in postgresql.conf in same directory

```
password_encryption = md5		# md5 or scram-sha-256
```

3. Reset password by running `ALTER ROLE postgres WITH PASSWORD '<new password>'`

**Comment by LeUser111** [comment]
We ran into the same issue here (cost our trainee about a day). It's now working as expected (with out-of-the-box scram authentication) with these versions:

<dependency>
  <groupId>com.typesafe.slick</groupId>
  <artifactId>slick_2.13</artifactId>
  <version>3.3.3</version>
</dependency>
<dependency>
  <groupId>com.typesafe.slick</groupId>
  <artifactId>slick-hikaricp_2.13</artifactId>
  <version>3.3.3</version>
</dependency>
<dependency>
  <groupId>org.postgresql</groupId>
  <artifactId>postgresql</artifactId>
  <version>42.3.4</version>
</dependency>

Please consider updating the example in the documentation page!

Postgres is probably one of the most common use cases and it is to be expected that new users use the latest postgres version when evaluating slick. The postgresql version in the example is from November 2015.
