### ISSUE TITLE
Add support to omit LiteralColumn in InsertCompiler, instead of throwing exception

### ISSUE THREAD

**Issue by TonyNa** [slick/slick#2219]
I'm trying to map my DB table into Scala Case Classes that contain fields not available in the table. Instead of having to define my own constructor & extractor functions to map over the tuple, I found that using `LiteralColumn` would achieve what I need:
```
case class Account(
  id: Long = NewId,
  body: Option[JsonString] = None
)

class AccountTable(tag: Tag) extends Table[Account](tag, "accounts") {
  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def body = LiteralColumn[Option[JsonString]](None)
}

def * = (id, body) <> ((Account.apply _).tupled, Account.unapply)
```

However, `insertOrUpdate` would fail if I try to write the model back into DB, with the following exception:
```
slick.SlickException: Cannot use node LiteralNode None (volatileHint=false) for inserting data
	at slick.compiler.InsertCompiler.tr$1(InsertCompiler.scala:54)
	at slick.compiler.InsertCompiler.$anonfun$apply$3(InsertCompiler.scala:36)
	at slick.util.ConstArray.endoMap(ConstArray.scala:123)
	at slick.ast.Node.mapChildren(Node.scala:50)
	at slick.ast.Node.mapChildren$(Node.scala:48)
	at slick.ast.ProductNode.mapChildren(Node.scala:128)
	at slick.compiler.InsertCompiler.tr$1(InsertCompiler.scala:36)
	at slick.compiler.InsertCompiler.$anonfun$apply$3(InsertCompiler.scala:36)
	at slick.ast.UnaryNode.mapChildren(Node.scala:223)
	at slick.ast.UnaryNode.mapChildren$(Node.scala:221)
	at slick.ast.TypeMapping.mapChildren(Node.scala:715)
	at slick.compiler.InsertCompiler.tr$1(InsertCompiler.scala:36)
	at slick.compiler.InsertCompiler.$anonfun$apply$1(InsertCompiler.scala:56)
	at slick.compiler.CompilerState.map(QueryCompiler.scala:230)
	at slick.compiler.InsertCompiler.apply(InsertCompiler.scala:16)
	at slick.compiler.QueryCompiler.$anonfun$runPhase$1(QueryCompiler.scala:79)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at slick.ast.SymbolNamer.use(Symbol.scala:111)
	at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
	at slick.compiler.QueryCompiler.$anonfun$runPhases$9(QueryCompiler.scala:75)
	at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:187)
	at scala.collection.TraversableOnce$folder$1$.apply(TraversableOnce.scala:185)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:189)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:184)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
	at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:75)
	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
	at slick.jdbc.JdbcStatementBuilderComponent$JdbcCompiledInsert.compile(JdbcStatementBuilderComponent.scala:36)
	at slick.jdbc.JdbcStatementBuilderComponent$JdbcCompiledInsert.upsert$lzycompute(JdbcStatementBuilderComponent.scala:48)
	at slick.jdbc.JdbcStatementBuilderComponent$JdbcCompiledInsert.upsert(JdbcStatementBuilderComponent.scala:48)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.<init>(JdbcActionComponent.scala:549)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.insertOrUpdate(JdbcActionComponent.scala:478)
```

I think `LiteralColumn` should behave the same way as `AutoInc` columns -- getting omitted in the generated SQL insert statement.

**Comment by nafg** [comment]
What about regular insert and regular update?
