### ISSUE TITLE
DB2 dependency not found error in GitHub Actions CI

### ISSUE THREAD

**Issue by dboreham** [slick/slick#2309]
Hello, I'm setting up private CI for Slick (to test some enhancements I'm working on that will be ultimately available for upstream contribution). I noticed the error below in my setup, which I see is also present in the CI runs here.

I'd like to debug and fix this, or perhaps alternatively come to a conclusion that it's benign...

If anyone has any thoughts or tips please let me know. 

For reasons I don't understand the error doesn't result in the build step failing.

I see here we fetch a DB2 jar from inside the docker image: https://github.com/slick/slick/blob/main/.github/workflows/ci.yml#L63
This jar is also available these days from maven-central fwiw, but it seems it isn't picked up later when needed in the build?

Anyways, thanks for any pointers.

```
[error] (Timer-2) java.lang.NoClassDefFoundError: com/ibm/db2/jcc/am/cm
[error] java.lang.NoClassDefFoundError: com/ibm/db2/jcc/am/cm
[error] 	at com.ibm.db2.jcc.am.lx.run(lx.java:150)
[error] 	at java.util.TimerThread.mainLoop(Timer.java:555)
[error] 	at java.util.TimerThread.run(Timer.java:505)
[error] Caused by: java.lang.ClassNotFoundException: com.ibm.db2.jcc.am.cm
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error] 	at com.ibm.db2.jcc.am.lx.run(lx.java:150)
[error] 	at java.util.TimerThread.mainLoop(Timer.java:555)
[error] 	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by nafg** [comment]
It says it's happening in a TimerThread. So it's not part of the tests' main thread, and I'm assuming that Slick does not create timers. So maybe it's some background process that DB2 sets up, and for some reason is not finding some class?

I wonder if it's missing the license jar?
