### ISSUE TITLE
groupBy does not allow group key in the nested query

### ISSUE THREAD

**Issue by nebehr** [slick/slick#2422]
Runtime error occurs if one of the grouping columns is used inside the nested query during flattening phase in groupBy: 

java.util.NoSuchElementException: key not found: s2
        at scala.collection.MapOps.default(Map.scala:241)
        at scala.collection.MapOps.default$(Map.scala:240)
        at scala.collection.AbstractMap.default(Map.scala:372)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:425)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.$anonfun$expr$1(JdbcStatementBuilderComponent.scala:301)
        at scala.collection.immutable.List.foldRight(List.scala:352)
        at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.expr(JdbcStatementBuilderComponent.scala:300)
        at slick.jdbc.PostgresProfile$QueryBuilder.expr(PostgresProfile.scala:210)
...

The following code will trigger this:
```scala
Query(1 -> 2).groupBy(_._1).map { case (x, xs) => xs.map(_._1 + x).sum }
```
If `x` is removed from the `map`, everything is ok.

The corresponding valid SQL query would be:
```sql
select c1, sum(c2 + c1)
from (select 1 as c1, 2 as c2) t
group by c1
```
Please disregard the table literal, it is used only for this quick contrived example, the error will occur with real tables too.

Slick version: 3.3.3
Database: PostgreSQL

**Comment by nafg** [comment]
PR welcome ;)
