### ISSUE TITLE
codegen: Null default values on numerics not handled correctly (e.g. "Null:numeric")

### ISSUE THREAD

**Issue by scprek** [slick/slick#2531]
**DESCRIPTION:**

When using slick codegen with Postgres Profile on a nullable numeric column, it tries to still instantiate a BigDecimal with the string `"Null:numeric"` which then fails with the exception below.

**STEPS TO REPRODUCE:**

Create a table with a column that is numeric and default null
```sql
CREATE TABLE test
(
    id                          uuid PRIMARY KEY,
    some_numeric                DECIMAL(7,2) DEFAULT NULL,
    created_at                  TIMESTAMP NOT NULL
);
```

If you look at the DDL of this table in a tool like DataGrip it resolves `some_numeric` to `numeric(7, 2) default NULL::numeric`

**EXPECTED RESULT:**

Match this if statement and return None
https://github.com/slick/slick/blob/main/slick/src/main/scala/slick/jdbc/JdbcModelBuilder.scala#L216

**ACTUAL RESULT:**

Tries to instantiate `BigDecimal("NULL::numeric")` and throws exception
https://github.com/slick/slick/blob/main/slick/src/main/scala/slick/jdbc/JdbcModelBuilder.scala#L231

```
java.lang.NumberFormatException: Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:518)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:401)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:834)
        at scala.math.BigDecimal$.exact(BigDecimal.scala:126)
        at scala.math.BigDecimal$.apply(BigDecimal.scala:284)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.$anonfun$default$1(JdbcModelBuilder.scala:231)
        at scala.Option.map(Option.scala:230)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.default(JdbcModelBuilder.scala:215)
        at slick.jdbc.PostgresProfile$ModelBuilder$ColumnBuilder.super$default(PostgresProfile.scala:117)
        at slick.jdbc.PostgresProfile$ModelBuilder$ColumnBuilder.$anonfun$default$3(PostgresProfile.scala:117)
        at scala.Option.getOrElse(Option.scala:189)
        at slick.jdbc.PostgresProfile$ModelBuilder$ColumnBuilder.default(PostgresProfile.scala:116)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.$anonfun$defaultColumnOption$3(JdbcModelBuilder.scala:255)
        at scala.Option.getOrElse(Option.scala:189)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:255)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:264)
        at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:282)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$columns$1(JdbcModelBuilder.scala:162)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.columnsByName$lzycompute(JdbcModelBuilder.scala:164)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.columnsByName(JdbcModelBuilder.scala:164)
        at slick.jdbc.JdbcModelBuilder$ForeignKeyBuilder.buildModel(JdbcModelBuilder.scala:315)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$buildForeignKeys$1(JdbcModelBuilder.scala:169)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.buildForeignKeys(JdbcModelBuilder.scala:169)
        at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
        at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$6(JdbcModelBuilder.scala:95)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$4(JdbcModelBuilder.scala:95)
        at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
        at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:172)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**SETUP:**

```
"com.typesafe.slick" %% "slick-codegen" % "3.3.3"
  "com.typesafe.slick" %% "slick" % "3.3.3",
  "com.typesafe.slick" %% "slick-hikaricp" % "3.3.3",
  "org.postgresql" % "postgresql" % "42.3.1",
  "com.github.tminglei" %% "slick-pg_spray-json" % "0.20.3"
```

**Comment by scprek** [comment]
Not sure the implications of doing a regex match on `Null*` instead of just `Null` https://github.com/slick/slick/blob/main/slick/src/main/scala/slick/jdbc/JdbcModelBuilder.scala#L216

**Comment by nafg** [comment]
PR welcome, alternatively perhaps give my code generator a try: https://github.com/nafg/slick-additions#slick-additions-codegen

It's based on scalameta instead of raw strings, and should be very easy to work with.

**Comment by nafg** [comment]
Also, please test on 3.4.0-RC3
