### ISSUE TITLE
`ifNull` may not work

### ISSUE THREAD

**Issue by sauntor** [slick/slick#2642]
**DESCRIPTION:**

if a table column is defined as the fellowing:

```scala
//class UserTable(tag: Tag) extends Table ... {
def avatar = column[String]("avatar", O.Length(255)).?
//}
val users = TableQuery[UserTable]
```
Then, `ifNull` will not work in `map()` :
```
db.run(users.map(_.avatar ifNull "N/A").result)
```

**EXPECTED RESULT:**

The generated SQL should be:
```sql
select coalesce("avatar", "N/A") from "USERS"
```

**ACTUAL RESULT:**
The actual generated SQL is as the fellows:
```sql
select "avatar" from "USERS"
```

And an exception will be thrown by Slick:

```stacktrace
Exception in thread "main" slick.SlickException: Read NULL value (null) for ResultSet column <computed>
	at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:27)
	at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:54)
	at slick.relational.ProductResultConverter.read(ResultConverter.scala:44)
	at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
	at slick.jdbc.StatementInvoker$$anon$2.extractValue(StatementInvoker.scala:70)
	at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
	at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:30)
	at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:36)
	at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:35)
	at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
	at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
	at slick.jdbc.Invoker.foreach(Invoker.scala:50)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:48)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**SETUP:**

1. PostgreSQL 14.1 (Docker)
2. openSUSE Leap 15.4
3. OpenJDK 17
4. slick 3.3.3/3.4.1
5. scala 2.13.10

**Comment by nafg** [comment]
If it's nullable shouldn't it be an Option type?

**Comment by sauntor** [comment]
The `?`  function makes a column's type from  `Rep[T]`  to `Rep[Option[T]]`, so, I think they should have the same behaviour, but the actual result is different, also, it will not work for the following code:

```scala
users.map(t => (t.id, t.name.?)).filter(_._2 === None: Option[String])
//The desired equivalent SQL is:
// select id, name from users where name is null
```

**Comment by sauntor** [comment]
@nafg ,  another thing is, not this one, I have solved the issue #2640 (update fields dynamically) by using streaming and `mutate` action, and write the solution to the Slick's document as an example (see pull request #2641 ).

I tried and wrote some codes for this problem, but I think my codes is ugly, so I drop it (see pull request #2640 ). The higher-kind and AST almost drove me crazy 😂.

**Comment by jkugiya** [comment]
The following code worked, though not as expected.

```scala
import slick.jdbc.PostgresProfile.api._

class User(tag: Tag) extends Table[(Int, Option[String])](tag, "users") {
  def id: Rep[Int] = column("id", O.PrimaryKey, O.AutoInc)
  def avatar: Rep[Option[String]] = column[String]("avatar", O.Length(255)).?
  override def * = (id, avatar)
}

val users = TableQuery[User]
println(users.map(_.avatar.get ifNull "N/A").result.statements.mkString)
// select coalesce("avatar", 'N/A') from "users"
```

**Comment by jkugiya** [comment]
This does not appear to be an appropriate use of `?`.

```scala
class User(tag: Tag) extends Table[(Int, Option[String])](tag, "users") {
  def id: Rep[Int] = column("id", O.PrimaryKey, O.AutoInc)

  def avatar: Rep[Option[String]] = column[Option[String]]("avatar", O.Length(255)) // Don't use `?`

  override def * = (id, avatar)
}
val users = TableQuery[User]
println(users.map(_.avatar ifNull "N/A").result.statements.mkString)
// select coalesce("avatar", 'N/A') from "users"
```

**Comment by nafg** [comment]
@sauntor can this be closed?
