### ISSUE TITLE
Codegen - Invalid Defaults in Case Classes

### ISSUE THREAD

**Issue by funkrusher** [slick/slick#2827]
**DESCRIPTION:**

I use the Slick-Codegen to create a case class for the following database schema:

```sql
CREATE TABLE lang
(
    langId      INT     NOT NULL AUTO_INCREMENT,
    code        CHAR(2) NOT NULL,
    description VARCHAR(50),
    PRIMARY KEY (langId)
);
```

**STEPS TO REPRODUCE:**

Please use my attached examples in the `SETUP` section, to reproduce this bug. 
It is easy to reproduce it, as it seems to be the default behavior for NULL fields in general.

**EXPECTED RESULT:**

I would expect the case class to look like this, notice the default value for the description field.

```scala
  case class LangRow(langId: Int, code: String, description: Option[String] = None)
```

**ACTUAL RESULT:**

The Slick-Codege creates the following case class for this database schema:
```scala
  case class LangRow(langId: Int, code: String, description: Option[String] = Some("NULL"))
```

Notice that it wraps the NULL in a Some, but as a plain-string. This would cause people that work with those generated case classes to produce wrong data in their database: Seemingly a String "NULL". This bug is in my opinion a bit critical as it can lead to all users of the slick-codegen to potentially create wrong database-entries, if they let the default-values be filled by the case class automatically.

I would love to have a feature-flag, that allows me to disable the generation of Default values in the case classes, as they are not really necessary. I already tried the following potential fix (`override def default: Option[String] = None`) in the codegen, but the codegenerator does not expect this to be set, and would crash if it is set like this:

```scala
// .. other example code from docs
  override def Table = new Table(_){
    // override contained column generator
    override def Column = new Column(_){
      override def default: Option[String] = None
    }
  }
```

It crashes like this for the above setting:
```scala
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:627)
    at scala.None$.get(Option.scala:626)
    at slick.codegen.AbstractSourceCodeGenerator$TableDef$ColumnDef.$anonfun$columnOptionCode$1(AbstractSourceCodeGenerator.scala:223)
    at slick.codegen.AbstractGenerator$TableDef$ColumnDef.$anonfun$options$2(AbstractGenerator.scala:256)
    at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
```
The crashing line is in AbstractSourceGenerator:
```
    case Default(value)     => Some(s"O.Default(${default.get})") // .get is safe here
```

**SETUP:**

- Database: Mariadb - 10.4.11
- JDK 1.8.0_241

Build.sbt:
```scala
lazy val dependencies = Seq(
  guice,
  "com.typesafe.play"  %% "play-slick"            % "5.1.0",
  "com.typesafe.play"  %% "play-slick-evolutions" % "5.1.0",
  "com.typesafe.slick" %% "slick-codegen"         % "3.4.1",
  "org.mariadb.jdbc"    % "mariadb-java-client"   % "3.1.2",
  "org.scalaz"         %% "scalaz-core"           % "7.3.2",
)

lazy val codegen = (project in file("codegen"))
  .settings(
    settings,
    libraryDependencies ++= dependencies,
  )

lazy val root = (project in file("."))
  .enablePlugins(PlayScala)
  .aggregate(codegen)
  .dependsOn(codegen)
  .settings(
    settings,
    libraryDependencies ++= dependencies,
    PlayKeys.playDefaultPort := 9000,
  )

TaskKey[Unit]("codegen") := (runMain in Compile).toTask(" init SlickCodegenApp").value
```

Slick-Codegen-Implementation:
```scala
    println("SlickCodegen - start")
    val filename        = "./conf/application.conf"
    val applicationConf = new File(filename)
    val conf            = ConfigFactory.parseFile(applicationConf);

    val url      = conf.getString("slick.dbs.default.db.url")
    val username = conf.getString("slick.dbs.default.db.user")
    val password = conf.getString("slick.dbs.default.db.password")

    val slickDriver = "slick.jdbc.MySQLProfile"
    val jdbcDriver  = "org.mariadb.jdbc.Driver"
    val outputDir   = "./app"
    val pkg         = "tables"

    if (clearOld) {
      println("SlickCodegen - clear old files...")
      val folder2: String = outputDir + "/" + (pkg.replace(".", "/")) + "/"
      new File(folder2).delete()
      println("SlickCodegen - clear old files done!")
    }

    val db                                  = slick.jdbc.MySQLProfile.api.Database.forURL(url, username, password, driver = jdbcDriver)
    val dbio                                = MySQLProfile.createModel(Some(MTable.getTables(None, None, None, Some(Seq("TABLE", "VIEW")))))
    val futureModel                         = db.run(dbio)
    val future: Future[SourceCodeGenerator] = futureModel.map(model => new SimpleCodeGenerator(model))
    try {
      println("SlickCodegen - creating files...")
      val codegen: SourceCodeGenerator = Await.result(future, Duration.create(5, TimeUnit.MINUTES))
      codegen.writeToMultipleFiles(profile = slickDriver, folder = outputDir, pkg = "tables", container = "Tables")
      println("SlickCodegen - creating files done!")
    } catch {
      case e: Exception =>
        println("SlickCodegen - creating files error!")
        e.printStackTrace()
    }
```

SimpleCodeGenerator Class:
```scala
class SimpleCodeGenerator(model: slick.model.Model) extends SourceCodeGenerator(model) {

  override def tableName =
    dbTableName => dbTableName.toLowerCase.toCamelCase

  override def Table =
    new Table(_) {
      // override contained column generator
      override def Column =
        new Column(_) {
          override def rawName = this.model.name
          override def rawType =
            if (model.name.startsWith("fineWithAnswer")) "Boolean" else super.rawType
        }
    }
}
```

**Comment by funkrusher** [comment]
hey, just for the record, for anybody who also stumbled into this problem.

i think i have found a rather invasive quick-fix, which solves my problem but needs me to copy-paste the code from the abstract-base class into my own generator and change it a bit... 

```scala
  override def Table = {
    new Table(_) {
      override def EntityType =
        new EntityType {
          override def code: String = {
            val args = columns.map(c =>
                s"${c.name}: ${c.exposedType}"
            ).mkString(", ")
            if (classEnabled) {
              val prns = (parents.take(1).map(" extends " + _) ++ parents.drop(1).map(" with " + _)).mkString("")
              (if (caseClassFinal) "final " else "") +
                s"""case class $name($args)$prns"""
            } else {
              if (columns.size > 254)
                s"type $name = $types" // constructor method would exceed JVM parameter limit
              else
                s"""
                type $name = $types
                /** Constructor for $name providing default values if available in the database schema. */
                def $name($args): $name = {
                ${compoundValue(columns.map(_.name))}
                }
                  """.trim
            }
          }
        }
    }
  }
}
```
the only line i changed is:
```scala
  c.default.map( v =>
    s"${c.name}: ${c.exposedType} = $v"
  ).getOrElse(
    s"${c.name}: ${c.exposedType}"
  )
```
i just removed the default there, and only left it at this:
```scala
 s"${c.name}: ${c.exposedType}"
```
as i don't need defaults, this is good enough for now.

**Comment by nafg** [comment]
Contributions welcome. (And I can help if you want to do a call.)

Also consider the code generator in https://github.com/nafg/slick-additions.
