### ISSUE TITLE
OracleProfile LocalDateTime can have 9 nanoseconds numbers but there is a restriction to just 3 in OracleProfile

### ISSUE THREAD

**Issue by matusbarabas** [slick/slick#3026]
LocalDateTime method valueToSQLLiteral can accept LocalDateTime only with 3 nano second numbers, but java LocalDateTime can have 9 nano second numbers, so when giving date time with more then 3 nanosecond numbers I am getting the error

_ORA-01830: date format picture ends before converting entire input string_

Can we please change line 420 in OracleProfile from

_s"TO_TIMESTAMP(${super.valueToSQLLiteral(value)}, 'YYYY-MM-DD HH24:MI:SS.FF3')"_

to

_s"TO_TIMESTAMP(${super.valueToSQLLiteral(value)}, 'YYYY-MM-DD HH24:MI:SS.FF9')"_

to be 100% compatible with Java LocalDateTime? 

I am expecting the same issue with instant and offset date time formats.

**Comment by nafg** [comment]
You can submit that change as a PR and if it passes the tests I'm happy to merge it!

Speaking of which, the Oracle tests often fail (sporadically) due to some time conversion issue. If you have domain expertise, perhaps you could help figure out the issue?

```
[error] Test com.typesafe.slick.testkit.tests.JdbcTypeTest.testZonedDateTime[oracle] failed: java.lang.AssertionError: expected:<(420,Some(2028-01-03T13:22:26.571+02:00[Europe/Zaporozhye]))> but was:<(420,Some(1772-01-03T13:24:30.571+02:02:04[Europe/Zaporozhye]))>, took 0.14 sec
[error] at scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] at com.typesafe.slick.testkit.tests.JdbcTypeTest.roundTrip$default$3$$anonfun$1(JdbcTypeTest.scala:128)
[error] at com.typesafe.slick.testkit.tests.JdbcTypeTest.roundTrip$default$3$$anonfun$adapted$1(JdbcTypeTest.scala:128)
[error] at com.typesafe.slick.testkit.tests.JdbcTypeTest.$anonfun$27$$anonfun$1(JdbcTypeTest.scala:150)
Error: expected:<(420,Some(2028-01-03T13:22:26.571+02:00[Europe/Zaporozhye]))> but was:<(420,Some(1772-01-03T13:24:30.571+02:02:04[Europe/Zaporozhye]))>
[error] at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:1895)
[error] at scala.collection.immutable.Vector.foreach(Vector.scala:1901)
[error] at com.typesafe.slick.testkit.tests.JdbcTypeTest.$anonfun$27(JdbcTypeTest.scala:150)
[error] at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] at slick.dbio.DBIOAction.map$$anonfun$1(DBIOAction.scala:42)
[error] at slick.basic.BasicBackend$BasicDatabaseDef.runInContextInline$$anonfun$1(BasicBackend.scala:191)
[error] at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
[error] at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[error] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
```
