### ISSUE TITLE
Building queries with dynamic columns in conditions

### ISSUE THREAD

**Issue by cvogt** [slick/slick#542]
Reproduce code

```
println(Coffees.filter(_.column[String]("SUP_ID") === "101").run)
```

```
  class Coffees(tag: Tag) extends Table[CoffeesRow](tag,"COFFEES"){
    val supId = column[Int]("SUP_ID")
    ...
  }
```

Result:

```
[error] (run-main) java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:106)
    at demo.Tables$CoffeesRow$.apply(Tables.scala:17)
    at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
    at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
    at scala.slick.lifted.MappedProjection$$anonfun$toNode$5.apply(Shape.scala:249)
    at scala.slick.ast.MappedScalaType.toMapped(Type.scala:100)
    at scala.slick.compiler.CreateResultSetMapping$$anonfun$scala$slick$compiler$CreateResultSetMapping$$f$1$5.apply(CreateResultSetMapping.scala:77)
    at scala.slick.profile.RelationalMappingCompilerComponent$TypeMappingResultConverter.read(RelationalProfile.scala:262)
    at scala.slick.driver.JdbcInvokerComponent$QueryInvoker.extractValue(JdbcInvokerComponent.scala:45)
    at scala.slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:36)
    at scala.slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:211)
    at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:94)
    at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:9)
    at scala.slick.jdbc.Invoker$class.build(Invoker.scala:69)
    at scala.slick.jdbc.StatementInvoker.build(StatementInvoker.scala:9)
    at scala.slick.jdbc.Invoker$class.list(Invoker.scala:59)
    at scala.slick.jdbc.StatementInvoker.list(StatementInvoker.scala:9)
    at scala.slick.jdbc.UnitInvoker$class.list(Invoker.scala:153)
    at scala.slick.driver.JdbcInvokerComponent$UnitQueryInvoker.list(JdbcInvokerComponent.scala:51)
    at LiveDemo$$anonfun$2.apply(LiveDemo.scala:33)
    at LiveDemo$$anonfun$2.apply(LiveDemo.scala:14)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:44)
    at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:331)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:44)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:44)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:44)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withTransaction(JdbcBackend.scala:61)
    at LiveDemo$delayedInit$body.apply(LiveDemo.scala:14)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at LiveDemo$.main(LiveDemo.scala:9)
    at LiveDemo.main(LiveDemo.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
```

**Comment by josephpconley** [comment]
Has an example with dynamic columns been added to an Activator template somewhere?

**Comment by szeiger** [comment]
Since this just came up in a support case, here's an example for even more dynamic queries:

```
  def testDynamic = {
    import slick.ast.TypedType
    import slick.lifted.RepShape
    import scala.reflect.ClassTag

    class A(tag: Tag) extends Table[Int](tag, "DYNAMIC_A") {
      def id = column[Int]("ID", O.PrimaryKey, O.AutoInc)
      def * = id
      override def create_* = collectFieldSymbols((id, column[String]("a"), column[Boolean]("b")).shaped.toNode)
    }
    val as = TableQuery[A]

    case class Dynamic[T <: Table[_], C](val f: T => Rep[C])(implicit val ct: TypedType[C])

    class DynamicProductShape[Level <: ShapeLevel](val shapes: Seq[Shape[_, _, _, _]]) extends MappedProductShape[Level, Seq[Any], Seq[Any], Seq[Any], Seq[Any]] {
      val classTag = implicitly[ClassTag[Seq[Any]]]
      override def getIterator(value: Seq[Any]) = value.iterator
      def getElement(value: Seq[Any], idx: Int) = value(idx)
      def buildValue(elems: IndexedSeq[Any]) = elems
      def copy(shapes: Seq[Shape[_ <: ShapeLevel, _, _, _]]) = new DynamicProductShape(shapes)
    }

    def allForId(id: Int, dyn: Seq[Dynamic[A, _]]): DBIO[Seq[(Int, Seq[Any])]] = {
      implicit def dynamicShape[Level <: ShapeLevel]: Shape[Level, Seq[Any], Seq[Any], Seq[Any]] =
        new DynamicProductShape[Level](dyn.map(d => RepShape))
      val q = as.filter(_.id === id).map(a => (a.id, dyn.map(d => d.f(a))))
      q.result
    }

    DBIO.seq(
      as.schema.create,
      as.map(a => (a.id, a.column[String]("a"), a.column[Boolean]("b"))) += (1, "foo", false),
      as.map(a => (a.id, a.column[String]("a"), a.column[Boolean]("b"))) += (2, "bar", true),
      allForId(2, Seq(
        Dynamic[A, String](_.column("a")),
        Dynamic[A, Boolean](_.column("b"))
      )).map(_ shouldBe Seq((2, Seq("bar", true))))
    )
  }
```

**Comment by evbo** [comment]
@szeiger what advantage does the `Dynamic` type have over the approach above?:
`println(Coffees.filter(_.column[String]("SUP_ID") === "101").run)`

In both cases, you need to explicitly set the correct type and ensure that the column represented by the string value corresponds to that type.
