### ISSUE TITLE
code generator: HSQLDB user defined types result in "incompatible data type in conversion"?

### ISSUE THREAD

**Issue by lJoublanc** [slick/slick#594]
First github post so please bear with me if I do something wrong..

I'm trying to generate a schema from HSQLDB-2.3.1 with the new schema generator in slick 2.0.0-rc1. I'm calling it from in my app using SourceCodeGenerator.main, as described in the docs. Errors below. I'm not sure why this is happening, but I think it may be because of the user defined type. However, there are a number of other types that aren't complaining. Please let me know what more information I should add here to help with diagnosis. Also, any workaround would also be appreciated.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at codegen.Generator.main(Generator.scala)
Caused by: java.sql.SQLSyntaxErrorException: incompatible data type in conversion: from SQL type VARCHAR to java.lang.Integer, value: REXDB.BOOK_ID
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.throwError(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getColumnInType(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.getInt(Unknown Source)
	at scala.slick.jdbc.PositionedResult.nextIntOption(PositionedResult.scala:60)
	at scala.slick.jdbc.GetResult$GetIntOption$.apply(GetResult.scala:39)
	at scala.slick.jdbc.GetResult$GetIntOption$.apply(GetResult.scala:39)
	at scala.slick.jdbc.PositionedResult.$less$less(PositionedResult.scala:31)
	at scala.slick.jdbc.PositionedResult.$less$less$qmark(PositionedResult.scala:32)
	at scala.slick.jdbc.meta.MColumn$$anonfun$getColumns$2.apply(MColumn.scala:36)
	at scala.slick.jdbc.meta.MColumn$$anonfun$getColumns$2.apply(MColumn.scala:29)
	at scala.slick.jdbc.ResultSetInvoker$$anon$2.extractValue(ResultSetInvoker.scala:33)
	at scala.slick.jdbc.ResultSetInvoker$$anon$1.extractValue(ResultSetInvoker.scala:23)
	at scala.slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:211)
	at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:98)
	at scala.slick.jdbc.ResultSetInvoker.foreach(ResultSetInvoker.scala:14)
	at scala.slick.jdbc.Invoker$class.build(Invoker.scala:69)
	at scala.slick.jdbc.ResultSetInvoker.build(ResultSetInvoker.scala:14)
	at scala.slick.jdbc.Invoker$class.list(Invoker.scala:59)
	at scala.slick.jdbc.ResultSetInvoker.list(ResultSetInvoker.scala:14)
	at scala.slick.jdbc.UnitInvoker$class.list(Invoker.scala:157)
	at scala.slick.jdbc.ResultSetInvoker.list(ResultSetInvoker.scala:14)
	at scala.slick.jdbc.meta.package$$anonfun$10.apply(package.scala:90)
	at scala.slick.jdbc.meta.package$$anonfun$10.apply(package.scala:90)
	at scala.collection.MapLike$MappedValues.get(MapLike.scala:249)
	at scala.collection.MapLike$class.apply(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:58)
	at scala.slick.jdbc.meta.package$.scala$slick$jdbc$meta$package$$table$1(package.scala:95)
	at scala.slick.jdbc.meta.package$$anonfun$createModel$2.apply(package.scala:184)
	at scala.slick.jdbc.meta.package$$anonfun$createModel$2.apply(package.scala:184)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at scala.slick.jdbc.meta.package$.createModel(package.scala:184)
	at scala.slick.driver.JdbcProfile$class.createModel(JdbcProfile.scala:66)
	at scala.slick.driver.HsqldbDriver$.createModel(HsqldbDriver.scala:116)
	at scala.slick.model.codegen.SourceCodeGenerator$$anonfun$main$1.apply(SourceCodeGenerator.scala:68)
	at scala.slick.model.codegen.SourceCodeGenerator$$anonfun$main$1.apply(SourceCodeGenerator.scala:67)
	at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
	at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
	at scala.slick.model.codegen.SourceCodeGenerator$.main(SourceCodeGenerator.scala:67)
	at codegen.Generator$.<init>(Generator.scala:23)
	at codegen.Generator$.<clinit>(Generator.scala)
	... 1 more
Caused by: org.hsqldb.HsqlException: incompatible data type in conversion: from SQL type VARCHAR to java.lang.Integer, value: REXDB.BOOK_ID
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	... 44 more
```

The sql that generated the schema doesn't appear to be anything special. Type declaration was:

     create  type  BOOK_ID               as  varchar(5);

And table declaration:

```
  create memory table bus_trade(
  id                 TRADE_ID        generated always as identity,
  version            VERSION_NUMBER,        
  side               TRADE_WAY,
  quantity           MONETARY,
  instrument         INSTRUMENT_ID,
  market             MARKET_ID,
  price              MONETARY,
  consideration      MONETARY        generated always as (quantity*price),
  currency           CURRENCY_ID,
  book               BOOK_ID,
  capture_datetime   DATETIME not null, 
  primary key        (id,version),
  foreign key        (currency) references stat_currency(id),
  foreign key        (instrument,market) references stat_market_instrument(id,market),
  foreign key        (book) references stat_book(id));
```

**Comment by szeiger** [comment]
Reported as fixed in https://sourceforge.net/p/hsqldb/bugs/1352/, so I'm closing this ticket, too.
