### ISSUE TITLE
scala.slick.SlickException: JdbcProfile has no TypeInfo for type Coll[NominalType(t2)((NominalType(@(t3))({ID: Int/INTEGER, NAME: String/VARCHAR}), NominalType(@(t4))({ID: Int/INTEGER, NAME: String/VARCHAR, MANUFACTURER_ID: Int/INTEGER})))]

### ISSUE THREAD

**Issue by soc** [slick/slick#625]
I checked out the scala-codegen-example repo and played a bit with it.

This query:

```
val computersByCompanies =
  Companies.join(Computers)
  .on(_.id === _.manufacturerId)
  .groupBy(elem => elem._1.name)
```

Fails with the following exception when I try to `run` it:

``````
scala.slick.SlickException: JdbcProfile has no TypeInfo for type Coll[NominalType(t2)((NominalType(@(t3))({ID: Int/INTEGER, NAME: String/VARCHAR}), NominalType(@(t4))({ID: Int/INTEGER, NAME: String/VARCHAR, MANUFACTURER_ID: Int/INTEGER})))]
    at scala.slick.driver.JdbcTypesComponent$class.typeInfoFor(JdbcTypesComponent.scala:127)
    at scala.slick.driver.H2Driver$.typeInfoFor(H2Driver.scala:61)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$MappingCompiler$class.createColumnConverter(JdbcMappingCompilerComponent.scala:18)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.createColumnConverter(JdbcMappingCompilerComponent.scala:36)
    at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$class.compileMapping(RelationalProfile.scala:215)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.compileMapping(JdbcMappingCompilerComponent.scala:36)
    at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$$anonfun$compileMapping$1.apply(RelationalProfile.scala:218)
    at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$$anonfun$compileMapping$1.apply(RelationalProfile.scala:218)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$class.compileMapping(RelationalProfile.scala:218)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.compileMapping(JdbcMappingCompilerComponent.scala:36)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$2.apply(JdbcMappingCompilerComponent.scala:44)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$2.apply(JdbcMappingCompilerComponent.scala:41)
    at scala.slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:22)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.apply(JdbcMappingCompilerComponent.scala:41)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$1.apply(JdbcMappingCompilerComponent.scala:38)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$1.apply(JdbcMappingCompilerComponent.scala:38)
    at scala.slick.compiler.CompilerState.map(QueryCompiler.scala:144)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.apply(JdbcMappingCompilerComponent.scala:38)
    at scala.slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:55)
    at scala.slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:54)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at scala.slick.ast.SymbolNamer.use(Symbol.scala:101)
    at scala.slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:54)
    at scala.slick.compiler.QueryCompiler$$anonfun$run$2.apply(QueryCompiler.scala:46)
    at scala.slick.compiler.QueryCompiler$$anonfun$run$2.apply(QueryCompiler.scala:46)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
    at scala.slick.compiler.QueryCompiler.run(QueryCompiler.scala:46)
    at scala.slick.compiler.QueryCompiler.run(QueryCompiler.scala:41)
    at scala.slick.profile.BasicProfile$Implicits$class.queryToQueryExecutor(BasicProfile.scala:44)
    at scala.slick.driver.JdbcProfile$$anon$1.queryToQueryExecutor(JdbcProfile.scala:25)
    at Example$$anonfun$9.apply(Example.scala:31)
    at Example$$anonfun$9.apply(Example.scala:22)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:44)
    at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:331)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:44)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:44)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:44)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withTransaction(JdbcBackend.scala:61)
    at Example$delayedInit$body.apply(Example.scala:22)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at Example$.main(Example.scala:7)
    at Example.main(Example.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)```
``````

**Comment by szeiger** [comment]
Not dropping Scala 2.10 support for now. Rescheduling to 3.1.

**Comment by szeiger** [comment]
We'll drop 2.10 support in 3.2.
