### ISSUE TITLE
CLOBs fail with exception on postgres and mysql

### ISSUE THREAD

**Issue by cvogt** [slick/slick#637]
```
[info] Test scala.slick.test.model.CodeGeneratorRoundTripTest.test[2] started
[Creating test database jdbc:postgresql:slick-test]
[Dropping test database jdbc:postgresql:slick-test]
[error] Test scala.slick.test.model.CodeGeneratorRoundTripTest.test[2] failed: org.postgresql.util.PSQLException: ERROR: type "clob" does not exist
[error]   Position: 513
[error]     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
[error]     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
[error]     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
[error]     at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
[error]     at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
[error]     at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:381)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(JdbcInvokerComponent.scala:58)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(JdbcInvokerComponent.scala:58)
[error]     at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:161)
[error]     at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:297)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1.apply(JdbcInvokerComponent.scala:58)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1.apply(JdbcInvokerComponent.scala:57)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply$mcV$sp(JdbcInvokerComponent.scala:57)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply(JdbcInvokerComponent.scala:57)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply(JdbcInvokerComponent.scala:57)
[error]     at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:331)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker.create(JdbcInvokerComponent.scala:56)
[error]     at scala.slick.test.model.CodeGeneratorRoundTripTest$$anonfun$test$1.apply(CodeGenRoundTripTest.scala:26)
[error]     at scala.slick.test.model.CodeGeneratorRoundTripTest$$anonfun$test$1.apply(CodeGenRoundTripTest.scala:17)
[error]     at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
[error]     at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
[error]     at scala.slick.test.model.CodeGeneratorRoundTripTest.test(CodeGenRoundTripTest.scala:17)
[error]     ...
[Using test database jdbc:mysql://localhost:3306/scala_query_test]
[info] Test scala.slick.test.model.CodeGeneratorRoundTripTest.test[3] started
[Creating test database jdbc:mysql://localhost:3306/scala_query_test]
create table `POSTS` (`id` INTEGER NOT NULL,`title` VARCHAR(254) NOT NULL,`category` INTEGER)
create unique index `fk_to_posts_INDEX_4` on `POSTS` (`id`)
create table `categories` (`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR(254) NOT NULL)
create index `IDX_NAME` on `categories` (`name`)
create table `TYPE_TEST` (`type` VARCHAR(254) NOT NULL,`Boolean` BOOLEAN DEFAULT true NOT NULL,`Byte` TINYINT NOT NULL,`Short` SMALLINT NOT NULL,`Int` INTEGER DEFAULT 5 NOT NULL,`Long` BIGINT DEFAULT 5 NOT NULL,`Float` DOUBLE DEFAULT 9.999 NOT NULL,`Double` DOUBLE DEFAULT 9.999 NOT NULL,`String` VARCHAR(254) DEFAULT 'someDefaultString' NOT NULL,`java_sql_Date` DATE NOT NULL,`java_sql_Time` TIME NOT NULL,`java_sql_Timestamp` TIMESTAMP NOT NULL,`java_sql_Blob` BLOB NOT NULL,`java_sql_Clob` CLOB NOT NULL,`None_Int` INTEGER DEFAULT null,`Option_Boolean` BOOLEAN DEFAULT true,`Option_Byte` TINYINT,`Option_Short` SMALLINT,`Option_Int` INTEGER DEFAULT 5,`Option_Long` BIGINT DEFAULT 5,`Option_Float` DOUBLE DEFAULT 9.999,`Option_Double` DOUBLE DEFAULT 9.999,`Option_String` VARCHAR(254) DEFAULT 'someDefaultString',`Option_java_sql_Date` DATE,`Option_java_sql_Time` TIME,`Option_java_sql_Timestamp` TIMESTAMP NULL,`Option_java_sql_Blob` BLOB,`Option_java_sql_Clob` CLOB)
alter table `TYPE_TEST` add constraint `PK` primary key(`Int`,`Long`)
create table `X` (`pk` INTEGER NOT NULL,`pk2` INTEGER NOT NULL,`val` INTEGER,`column` INTEGER NOT NULL,`schema_name` DOUBLE NOT NULL,`schema_name_x` VARCHAR(254) NOT NULL,`index_1` INTEGER,`posts` INTEGER)
alter table `X` add constraint `X_PK` primary key(`pk`,`pk2`)
create index `i2` on `X` (`index_1`)
create index `X_INDEX_1` on `X` (`index_1`)
alter table `POSTS` add constraint `_` foreign key(`category`) references `categories`(`id`) on update RESTRICT on delete RESTRICT
alter table `X` add constraint `fk_to_posts` foreign key(`posts`) references `POSTS`(`id`) on update RESTRICT on delete RESTRICT
alter table `X` add constraint `fk1` foreign key(`pk`) references `categories`(`id`) on update RESTRICT on delete RESTRICT
alter table `X` add constraint `fk2` foreign key(`pk2`) references `categories`(`id`) on update RESTRICT on delete RESTRICT
[Dropping test database jdbc:mysql://localhost:3306/scala_query_test]
[error] Test scala.slick.test.model.CodeGeneratorRoundTripTest.test[3] failed: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CLOB NOT NULL,`None_Int` INTEGER DEFAULT null,`Option_Boolean` BOOLEAN DEFAULT t' at line 1
[error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
[error]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
[error]     at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
[error]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
[error]     at com.mysql.jdbc.Util.getInstance(Util.java:386)
[error]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
[error]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
[error]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
[error]     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
[error]     at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
[error]     at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
[error]     at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
[error]     at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(JdbcInvokerComponent.scala:58)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$1.apply(JdbcInvokerComponent.scala:58)
[error]     at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:161)
[error]     at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:297)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1.apply(JdbcInvokerComponent.scala:58)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1$$anonfun$apply$mcV$sp$1.apply(JdbcInvokerComponent.scala:57)
[error]     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply$mcV$sp(JdbcInvokerComponent.scala:57)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply(JdbcInvokerComponent.scala:57)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker$$anonfun$create$1.apply(JdbcInvokerComponent.scala:57)
[error]     at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:331)
[error]     at scala.slick.driver.JdbcInvokerComponent$DDLInvoker.create(JdbcInvokerComponent.scala:56)
[error]     at scala.slick.test.model.CodeGeneratorRoundTripTest$$anonfun$test$1.apply(CodeGenRoundTripTest.scala:26)
[error]     at scala.slick.test.model.CodeGeneratorRoundTripTest$$anonfun$test$1.apply(CodeGenRoundTripTest.scala:17)
[error]     at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
[error]     at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
[error]     at scala.slick.test.model.CodeGeneratorRoundTripTest.test(CodeGenRoundTripTest.scala:17)
[error]     ...

```

**Comment by al11al** [comment]
It is still same bug in MySQL. I had to create table with "TEXT", "MEDIUMTEXT" or "LARGETEXT"  with help of raw request that is apropriate to MySQL. Then I used String type in text DB columns. Other way was to override column creation in slick source generator for each db and column types that have bugs.
