### ISSUE TITLE
Delete of joined query

### ISSUE THREAD

**Issue by ghost** [slick/slick#684]
Hello there!
Consider the following code:

```
  class ArticleID(val value: Int) extends AnyVal

  case class Article(id: ArticleID, title: String, tags: Set[String])

  implicit val ArticleIDSupport = MappedColumnType.base[ArticleID, Int](_.value, new ArticleID(_))

  class Articles(t: Tag) extends Table[Article](t, "test_articles") {
    val id = column[ArticleID]("id", O.PrimaryKey, O.AutoInc)
    val title = column[String]("title")

    def * = (id, title).shaped <> (
      { case t => Article(t._1, t._2, Set()) },
      { a: Article => Some((a.id, a.title)) }
    )
  }

  class ArticleTags(t: Tag) extends Table[(Int, ArticleID, String)](t, "test_article_tags") {
    val id = column[Int]("id", O.PrimaryKey, O.AutoInc)
    val articleID = column[ArticleID]("article_id")
    val tag = column[String]("tag_name")

    def articleFK = foreignKey("article_fk", articleID, articles)(_.id)
    def * = (id, articleID, tag)
  }

  val articles = TableQuery[Articles]
  val tags = TableQuery[ArticleTags]

  implicit class ArticlesOpts(val q: Query[Articles, Article]) extends AnyVal {
    def withTags(t: Query[ArticleTags,(Int, ArticleID, String)] = tags) =
      q.innerJoin(t).on(_.id === _.articleID)
  }
```

.....

```
Database.forDataSource(ds) withSession  { implicit s =>
  val testData = Seq(
    Article(noArticleID, "test article 1", Set()),
    Article(noArticleID, "test article 2", Set("testing", "useful")),
    Article(noArticleID, "test article 3", Set("testing")),
    Article(noArticleID, "test article 4", Set("cars"))
  )

  // there I put test data into db and it works fine so far so testData hits respected tables
  testData foreach store

  // then I would like to remove tags for all articles out of storage like so:
  val q1 = articles.withTags().map(_._2)
  println(q1.deleteStatement.mkString("\n"))
  q1.delete

}
```

But the tags deletion results in the following exception:
scala.slick.SlickException: A query for a DELETE statement must resolve to a comprehension with a single table -- Unsupported shape: Comprehension(fetch = None, offset = None)
scala.slick.SlickException: A query for a DELETE statement must resolve to a comprehension with a single table -- Unsupported shape: Comprehension(fetch = None, offset = None)
    at scala.slick.driver.JdbcStatementBuilderComponent$QueryBuilder.buildDelete(JdbcStatementBuilderComponent.scala:328)
    at scala.slick.driver.JdbcProfile$$anonfun$deleteCompiler$1.apply(JdbcProfile.scala:35)
    at scala.slick.driver.JdbcProfile$$anonfun$deleteCompiler$1.apply(JdbcProfile.scala:35)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$2.apply(JdbcMappingCompilerComponent.scala:42)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$2.apply(JdbcMappingCompilerComponent.scala:41)
    at scala.slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:22)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.apply(JdbcMappingCompilerComponent.scala:41)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$1.apply(JdbcMappingCompilerComponent.scala:38)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen$$anonfun$apply$1.apply(JdbcMappingCompilerComponent.scala:38)
    at scala.slick.compiler.CompilerState.map(QueryCompiler.scala:144)
    at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcCodeGen.apply(JdbcMappingCompilerComponent.scala:38)
    at scala.slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:55)
    at scala.slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:54)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at scala.slick.ast.SymbolNamer.use(Symbol.scala:101)
    at scala.slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:54)
    at scala.slick.compiler.QueryCompiler$$anonfun$run$2.apply(QueryCompiler.scala:46)
    at scala.slick.compiler.QueryCompiler$$anonfun$run$2.apply(QueryCompiler.scala:46)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
    at scala.slick.compiler.QueryCompiler.run(QueryCompiler.scala:46)
    at scala.slick.compiler.QueryCompiler.run(QueryCompiler.scala:41)
    at scala.slick.driver.JdbcProfile$Implicits$class.queryToDeleteInvoker(JdbcProfile.scala:48)
    at scala.slick.driver.JdbcProfile$$anon$1.queryToDeleteInvoker(JdbcProfile.scala:25)
    at com.typesafe.slick.examples.lifted.FirstExample$$anonfun$12.apply(FirstExample.scala:91)
    at com.typesafe.slick.examples.lifted.FirstExample$$anonfun$12.apply(FirstExample.scala:88)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
    at com.typesafe.slick.examples.lifted.FirstExample$delayedInit$body.apply(FirstExample.scala:88)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at com.typesafe.slick.examples.lifted.FirstExample$.main(FirstExample.scala:9)
    at com.typesafe.slick.examples.lifted.FirstExample.main(FirstExample.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by asazernik** [comment]
Some notes for future implementors:

`DELETE` and `UPDATE` on joined queries is not standard SQL. Even where multiple databases support the feature, they do so with incompatible syntax. Support will be driver-specific, like upsert. Looking at a few major DB vendors:

1. `DELETE` on a joined query is supported using the same syntax in MySQL and PostgreSQL, though only the former allows deleting rows from more than one table in the join. MSSQL supports deletion on a join query, but with different syntax. SQLite does not support the feature.
2. `UPDATE` on a joined query is supported using incompatible syntaxes by MySQL, PostgreSQL, and MSSQL. Again, only MySQL permits modification of multiple tables while performing this operation. SQLite, again, does not support the feature.

**Comment by park00123** [comment]
## UI 취약점 조사 진행 1차 결과
**조사 결과 첨부파일**
- [2024-02_07_씨티은행 취약점.xlsx](https://github.com/interezen/webhead/files/14191025/2024-02_07_.xlsx)

**주요 이슈 사항**
- handsontable.js 버전[ v10.0.0]이상으로 업그레이드 필요하지만, 이전 버전업 시도시 v8 이상 버전 사용시 시스템 에러 발생.
