### ISSUE TITLE
Invalid SQL generated on inner query from GroupBy

### ISSUE THREAD

**Issue by fzakaria** [slick/slick#871]
An example query I was performing where I used groupBy to get uniquness was throwing an error when I tried to put a where clause on the ids from the sub query.
When I moved the where clause to an if statement it worked!

---ERROR---

CREATE FORCE VIEW PUBLIC._37 AS
SELECT
    X141.X142 AS X108,
    X141.X143 AS X109,
    X141.X144 AS X110,
    X141.X145 AS X111,
    X141.X146 AS X112,
    X141.X147 AS X113,
    X141.X148 AS X114,
    X141.X149 AS X115,
    X141.X150 AS X116,
    X141.X151 AS X117,
    X141.X152 AS X118,
    X141.X153 AS X119,
    X141.X154 AS X120,
    X141.X155 AS X121,
    X141.X156 AS X122
FROM (
    SELECT
        X157."content" AS X142,
        X157."amountReceived" AS X143,
        X157."createdAt" AS X144,
        X157."numOfBurns" AS X145,
        X157."numOfFunders" AS X146,
        X157."fromUserId" AS X147,
        X157."id" AS X148,
        X157."scoreWeight" AS X149,
        X157."updatedAt" AS X150,
        X157."deleted" AS X151,
        X157."forContentPlatform" AS X152,
        X157."voteCount" AS X153,
        X157."toUserId" AS X154,
        X157."numOfLikes" AS X155,
        X157."numOfReported" AS X156
    FROM PUBLIC."votes" X158
        /\* PUBLIC."vote_unique": "voterId" = 21 _/
        /_ WHERE X158."voterId" = 21
        _/
    INNER JOIN PUBLIC."ideas" X157
        /_ PUBLIC.PRIMARY_KEY_5: "id" = X158."ideaId" _/
        ON 1=1
    WHERE (X158."voterId" = 21)
        AND ((X157."deleted" = FALSE)
        AND (X158."ideaId" = X157."id"))
    ORDER BY 9 DESC
) X141
WHERE X141.X148 = X106.X104 [42122-172]]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.3]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:166) [play_2.10.jar:2.2.3]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:163) [play_2.10.jar:2.2.3]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Column "X106.X104" not found; SQL statement:
CREATE FORCE VIEW PUBLIC._37 AS
SELECT
    X141.X142 AS X108,
    X141.X143 AS X109,
    X141.X144 AS X110,
    X141.X145 AS X111,
    X141.X146 AS X112,
    X141.X147 AS X113,
    X141.X148 AS X114,
    X141.X149 AS X115,
    X141.X150 AS X116,
    X141.X151 AS X117,
    X141.X152 AS X118,
    X141.X153 AS X119,
    X141.X154 AS X120,
    X141.X155 AS X121,
    X141.X156 AS X122
FROM (
    SELECT
        X157."content" AS X142,
        X157."amountReceived" AS X143,
        X157."createdAt" AS X144,
        X157."numOfBurns" AS X145,
        X157."numOfFunders" AS X146,
        X157."fromUserId" AS X147,
        X157."id" AS X148,
        X157."scoreWeight" AS X149,
        X157."updatedAt" AS X150,
        X157."deleted" AS X151,
        X157."forContentPlatform" AS X152,
        X157."voteCount" AS X153,
        X157."toUserId" AS X154,
        X157."numOfLikes" AS X155,
        X157."numOfReported" AS X156
    FROM PUBLIC."votes" X158
        /_ PUBLIC."vote_unique": "voterId" = 21 _/
        /_ WHERE X158."voterId" = 21
        _/
    INNER JOIN PUBLIC."ideas" X157
        /_ PUBLIC.PRIMARY_KEY_5: "id" = X158."ideaId" */
        ON 1=1
    WHERE (X158."voterId" = 21)
        AND ((X157."deleted" = FALSE)
        AND (X158."ideaId" = X157."id"))
    ORDER BY 9 DESC
) X141
WHERE X141.X148 = X106.X104 [42122-172]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:329) ~[h2.jar:1.3.172]
    at org.h2.message.DbException.get(DbException.java:169) ~[h2.jar:1.3.172]
    at org.h2.message.DbException.get(DbException.java:146) ~[h2.jar:1.3.172]
    at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144) ~[h2.jar:1.3.172]
    at org.h2.expression.Comparison.optimize(Comparison.java:163) ~[h2.jar:1.3.172]
    at org.h2.command.dml.Select.prepare(Select.java:811) ~[h2.jar:1.3.172

--- Invalid Query-----  
 val ideasQuery = getNonUniqueIdeas()
          val uniqueIdeaIds = ideasQuery.groupBy(_.id).map(_._1)
          // Filter the ideas table and project it onto a list of Ideas
          val offset = pageSize \* page
          val ideasQueryWithUsers = for {
            id <- uniqueIdeaIds
            q <- ideasQuery.where(_.id === id) leftJoin users on (_.fromUserId === _.id) leftJoin users on (_._1.toUserId === _.id)
          } yield (q._1._1, q._1._2, q._2)
          ideasQueryWithUsers.drop(offset).take(pageSize).list

---- Fixed Query (notice the missing where and new if statement in the query)----
 val ideasQuery = getNonUniqueIdeas()
          val uniqueIdeaIds = ideasQuery.groupBy(_.id).map(_._1)
          // Filter the ideas table and project it onto a list of Ideas
          val offset = pageSize \* page
          val ideasQueryWithUsers = for {
            id <- uniqueIdeaIds
            q <- ideasQuery leftJoin users on (_.fromUserId === _.id) leftJoin users on (_._1.toUserId === _.id)
          if q._1._1.id === id
          } yield (q._1._1, q._1._2, q._2)
          ideasQueryWithUsers.drop(offset).take(pageSize).list

**Comment by szeiger** [comment]
Related to #159 but here all the joins are inner joins. This should work in 3.1 (but it doesn't as of RC1).

**Comment by szeiger** [comment]
There are two problems in `RewriteJoins` that prevent this from working: `rearrangeJoinConditions` only deals with actual join conditions but not `Filter` operations. And while it transforms recursively, it still won't pull a condition up by more than one level (the minimized test case requires two levels) unless it also references the levels in between. In order to translate cases such as this one we would have to make it work more like `eliminateIllegalRefs` with an extra set of illegal TermSymbols coming from the outside, lift `Filter` conditions into the nearest `Join` if they reference an illegal symbol, and transform left-hand sides of joins, too (as needed here; this situation cannot occur when you only pull up by one level anyway).
