### ISSUE TITLE
Scala's Slick with multiple PK insertOrUpdate() throws exception ERROR: syntax error at end of input

### ISSUE THREAD

**Issue by President** [slick/slick#966]
I am using Scala' Slick and PostgreSQL. And I am working well with tables with single PK. Now I need to use a table with multiple PKs:

```
case class Report(f1: DateTime,
    f2: String,
    f3: Double)

class Reports(tag: Tag) extends Table[Report](tag, "Reports") {
    def f1 = column[DateTime]("f1")
    def f2 = column[String]("f2")
    def f3 = column[Double]("f3")

    def * = (f1, f2, f3) <> (Report.tupled, Report.unapply)
    def pk = primaryKey("pk_report", (f1, f2))
}

val reports = TableQuery[Reports]
```

when I have empty table and use reports.insert(report) it works well. But when I use reports.insertOrUpdate(report) I receive and exception:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 76
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
    at ....
```

What am I doing wrong? How to fix it?

Thanks in advance.

PS. I tried workaround - tried to implement "if exist update else insert" logic by:

```
  val len = reports.withFilter(_.f1 === report.f1).withFilter(_.f2 === report.f2).length.run.toInt
                    if(len == 1) {
                        println("Update: " + report)
                        reports.update(report)
                    } else {
                        println("Insert: " + report)
                        reports.insert(report)
                    }
```

But I still get exception on update:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_report"
  Detail: Key ("f1", f2)=(2014-01-31 04:00:00, addon_io.aha.connect) already exists.
```

**Comment by mustajarvi** [comment]
I encountered this one as well. In my case the compiled statement looks like this:

```sql
begin;
	update "service_user" set "serviceid"=?,"username"=?,"fetched"=?,"userid"=? where ;

	insert into "service_user" ("serviceid","username","fetched","userid") select ?,?,?,? where not exists (select 1 from "service_user" where );
end
```

(The "where" clause is empty.)

**Comment by aparamonov** [comment]
I've just found a workaround for this bug in 3.0.0.
Just mark appropriate column definition as a primary key. So, in the example above it should look like this:
```
class Reports(tag: Tag) extends Table[Report](tag, "Reports") {
    def f1 = column[DateTime]("f1", O.PrimaryKey)
    def f2 = column[String]("f2", O.PrimaryKey)
    def f3 = column[Double]("f3")

    def * = (f1, f2, f3) <> (Report.tupled, Report.unapply)
}
```
After this modification, insertOrUpdate will generate f1 and f2 columns in where clause.

**Comment by davidhoyt** [comment]
This bug just bit me in 3.0.0 -- any chance it will be addressed soon?

@aparamonov Your workaround worked for me unless you try and create the table in which case you'll get an error saying there are multiple primary keys defined.

For what it's worth, I got the same error when I don't define a primary key via the `ColumnOption` and instead do: `def pk = primaryKey("PK_Foo", myId)`. _Even for non-composite keys._

**Comment by Raymond26** [comment]
+1.  Encountered the same thing!

**Comment by dwickern** [comment]
+1. `primaryKey` should be equivalent to `O.PrimaryKey`. I like naming my constraints for better error messages.

**Comment by vladimir-lu-work** [comment]
Encountered the same thing as well. We worked around it in the tests (the only place where schemas are actually generated from Slick code) by creating a second table with the primary key on the autoincrement column.

**Comment by asazernik** [comment]
The issue is definitely that `O.PrimaryKey` is not set, as @aparamonov stated. The relevant code in `PostgresDriver#UpsertBuilder` is:

```scala
      val update = "update " + tableName + " set " + softNames.map(n => s"$n=?").mkString(",") + " where " + pkNames.map(n => s"$n=?").mkString(" and ")
```

where `softNames` and `pkNames` are distinguished in the following statement in `JdbcCompiledInsert#UpsertBuilder`:

```scala
  class UpsertBuilder(ins: Insert) extends InsertBuilder(ins) {
    protected lazy val (pkSyms, softSyms) = syms.partition(_.options.contains(ColumnOption.PrimaryKey))
    protected lazy val pkNames = pkSyms.map { fs => quoteIdentifier(fs.name) }
    protected lazy val softNames = softSyms.map { fs => quoteIdentifier(fs.name) }
 ```

If, as @davidhoyt indicated, this breaks the SQL generator, that may or may not be a separate bug. The real issue seems to be the lack of a Single Source of Truth with regards to what columns in the table participate in the primary key - is it the `O.PrimaryKey` flag? Or is it the existence of a constraint declared by `primaryKey()`?

This issue is so common with composite keys in particular only because of the behavior of slick-codegen, which emits only the `O.PrimaryKey` flag for single-column keys, and only the `primaryKey()` constraint definition for composite keys.

**Comment by berardino** [comment]
I have encountered the same issue . I have a table oauth2_access_tokens with the following composite primary key(user_id,client_id) .
+1

```
[debug] - slick.backend.DatabaseComponent.action - #1: insertOrUpdate [begin; update "oauth2_access_tokens" set "token"=?,"user_id"=?,"client_id"=?,"created_at"=?,"refresh_token"=?,"scope"=?,"expires_in"=? where ; insert into "oauth2_access_tokens" ("token","user_id","client_id","created_at","refresh_token","scope","expires_in") select ?,?,?,?,?,?,? where not exists (select 1 from "oauth2_access_tokens" where ); end]
[debug] - slick.jdbc.JdbcBackend.statement - Preparing statement: begin; update "oauth2_access_tokens" set "token"=?,"user_id"=?,"client_id"=?,"created_at"=?,"refresh_token"=?,"scope"=?,"expires_in"=? where ; insert into "oauth2_access_tokens" ("token","user_id","client_id","created_at","refresh_token","scope","expires_in") select ?,?,?,?,?,?,? where not exists (select 1 from "oauth2_access_tokens" where ); end
[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 143
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103) ~[postgresql-9.1-901-1.jdbc4.jar:na][debug] - slick.backend.DatabaseComponent.action - #1: insertOrUpdate [begin; update "oauth2_access_tokens" set "token"=?,"user_id"=?,"client_id"=?,"created_at"=?,"refresh_token"=?,"scope"=?,"expires_in"=? where ; insert into "oauth2_access_tokens" ("token","user_id","client_id","created_at","refresh_token","scope","expires_in") select ?,?,?,?,?,?,? where not exists (select 1 from "oauth2_access_tokens" where ); end]
[debug] - slick.jdbc.JdbcBackend.statement - Preparing statement: begin; update "oauth2_access_tokens" set "token"=?,"user_id"=?,"client_id"=?,"created_at"=?,"refresh_token"=?,"scope"=?,"expires_in"=? where ; insert into "oauth2_access_tokens" ("token","user_id","client_id","created_at","refresh_token","scope","expires_in") select ?,?,?,?,?,?,? where not exists (select 1 from "oauth2_access_tokens" where ); end
[error] - play.core.server.netty.PlayDefaultUpstreamHandler - Cannot invoke the action
org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 143
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103) ~[postgresql-9.1-901-1.jdbc4.jar:na]
```

**Comment by domdorn** [comment]
I just encountered the same issue in slick 3.0.0 with PostgreSQL. 
Changing my code form tableQuery.insertOrUpdate(row) to tableQuery += row fixed the issue, obviously with slightly different semantics. IMHO slick should throw an own exception when trying to do insertOrUpdate on PostgreSQL when that is not supported.

**Comment by agapep** [comment]
+1

**Comment by Lykathia** [comment]
+1, also just ran into this.

**Comment by ahjohannessen** [comment]
+1

**Comment by Tvaroh** [comment]
+1

**Comment by nlhkh** [comment]
+1

**Comment by scspijker** [comment]
+1

**Comment by asazernik** [comment]
Public Service Announcement: the "subscribe" button is a way to indicate interest without clogging up the comments thread. +1's Considered Harmful unless they come with extra information on the bug.

**Comment by jurajzachar** [comment]
+1

**Comment by nafg** [comment]
On Thu, Oct 29, 2015, 2:15 PM Asa Zernik <notifications@github.com> wrote:

> Public Service Announcement: the "subscribe" button is a way to indicate
> interest without clogging up the comments thread. +1's Considered Harmful
> unless they come with extra information on the bug.
>

Is that the community policy?

I see it as a voting mechanism -- a way for the community to petition for
something to happen, or a way for the maintainers to measure the value it
holds to the community.

**Comment by asazernik** [comment]
I don't know if that's this particular community's policy, but I have seen it explicitly stated on many open source projects' bug reports. In bug discussions that are swamped in +1's, it's harder to get a clean view of the thread of conversation between people reporting actual additional information and suggesting fixes.

Plus it spams my e-mail and GitHub inboxes -__-

**Comment by asazernik** [comment]
(If you're trying to gauge interest, it's also much easier to compare subscriber counts between issues than it is to go through and count up the +1 comments.)

**Comment by jdahaldev** [comment]
+ 1

**Comment by jdahaldev** [comment]
+ 1

**Comment by jdahaldev** [comment]
+1

**Comment by cvogt** [comment]
As one of the maintainers, I prefer +1s. They come with notifications.

**Comment by amosjyng** [comment]
In that case, +1!

**Comment by OlegEfrem** [comment]
+1

**Comment by Diagoras** [comment]
+1

**Comment by BackendButters** [comment]
+1

**Comment by cwmyers** [comment]
+1

**Comment by etorreborre** [comment]
+1

**Comment by danielyli** [comment]
+1

**Comment by cfusting** [comment]
+1

**Comment by jaapterwoerds** [comment]
+1

**Comment by arshiamufti** [comment]
+1

**Comment by goldsworthy** [comment]
+1

**Comment by tminglei** [comment]
As above, I'm preparing a fix patch for tminglei/slick-pg#288 and slick/slick#966.

It seems almost there, but I encountered an exception:
```
[info] Test com.typesafe.slick.testkit.tests.InsertTest.testInsertOrUpdatePlainWithFuncDefinedPK[derbymem] started
>>> upsert sql: merge into "t_merge3" t using (select ? as "id",? as "name" from sysibm.sysdummy1) s on (t."id"=s."id") when matched then update set t."name"=s."name" when not matched then insert ("id", "name") values (s."id", s."name")
[error] Test com.typesafe.slick.testkit.tests.InsertTest.testInsertOrUpdatePlainWithFuncDefinedPK[derbymem] failed: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 31., took 0.032 sec
[error]     at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedPreparedStatement.this(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.this(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.this(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.this(Unknown Source)
[error]     at org.apache.derby.jdbc.Driver40.newEmbedPreparedStatement(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
[error]     at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:302)
[error]     at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:414)
[error]     at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:351)
[error]     at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:414)
[error]     at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedOther(JdbcActionComponent.scala:500)
[error]     at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.emulate(JdbcActionComponent.scala:564)
[error]     at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.f$1(JdbcActionComponent.scala:539)
[error]     at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$InsertOrUpdateAction.run(JdbcActionComponent.scala:544)
[error]     at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:31)
[error]     at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[error]     at java.lang.Thread.run(Thread.java:745)
[error] Caused by: java.sql.SQLException: Syntax error: Encountered "<EOF>" at line 1, column 31.
[error]     at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
[error]     at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
[error]     ... 28 more
[error] Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 31.
[error]     at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
[error]     at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
[error]     at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
[error]     at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
[error]     at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
[error]     ... 22 more
[info] Test com.typesafe.slick.testkit.tests.InsertTest.testInsertOrUpdateAutoInc[derbymem] started
...
...
[error] Failed: Total 1041, Failed 2, Errors 0, Passed 1039
[error] Failed tests:
[error]         slick.test.profile.DerbyMemTest
[error]         slick.test.profile.DerbyDiskTest
[error] (testkit/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 314 s, completed Jul 7, 2016 6:52:43 AM
```
_p.s. this only occurred on `derbymem` and `derbydisk`._


I haven't found out why. Any idea?

**Comment by cvogt** [comment]
Mh. Is this a derby limitation? Might need a capability flag to exclude derby from this test then

**Comment by tminglei** [comment]
I finally found the cause.

Derby used client side emulate upsert _(it's the only one currently)_, and here's the using sqls:
```
checkSql = select 1 from "t_merge3" where 
updateSql = update "t_merge3" set "name"=? where "id"=?
insertSql = insert into "t_merge3" ("id","name")  values (?,?)
```

The wrong checkSql is related to `checkInsertCompiler` defined in `JdbcProfile`:
```scala
  lazy val checkInsertCompiler = QueryCompiler(Phase.assignUniqueSymbols, Phase.inferTypes, new InsertCompiler(InsertCompiler.PrimaryKeys), new JdbcInsertCodeGen(createCheckInsertBuilder))

...
object InsertCompiler {
...
  /** Include only primary keys. For use in the insertOrUpdate emulation. */
  case object PrimaryKeys extends Mode {
    def apply(fs: FieldSymbol) = fs.options.contains(ColumnOption.PrimaryKey)
  }
}
```
As you see, it doesn't care primary key defined by `primaryKey` function of `Table[_]`.

.
The best fixing way is to enable `InsertCompiler.PrimaryKeys` to check primary keys defined by `primaryKey` function of `Table[_]`. But I didn't find a way to get it.

.
Another workable way is to override `val checkInsertCompiler` in `DerbyProfile` with
```scala
  lazy val checkInsertCompiler = QueryCompiler(Phase.assignUniqueSymbols, Phase.inferTypes, new InsertCompiler(InsertCompiler.AllColumns), new JdbcInsertCodeGen(createCheckInsertBuilder))
```
And override `CheckInsertBuilder.transformMapping(node)` to exclude non-primaryKey columns that was wrongly included by `InsertCompiler.AllColumns` above.
But this way make people confused. I didn't want to use it until it's necessary.

.
_So I gave up the fixing and excluded derby from the test temporarily._

**Comment by tminglei** [comment]
@szeiger @cvogt  I sent a PR, pls help review.

**Comment by justbaker** [comment]
+1

**Comment by vpavkin** [comment]
+1

**Comment by metaheavens** [comment]
+1

**Comment by cvogt** [comment]
will try to get this into 3.2.1 or 3.3 which hopefully comes out very soon

**Comment by pocman** [comment]
Hi, 
I still have the issue using slick 3.2.1

here is my table : 
```scala
  class BotSummaryTable(tag: Tag) extends Table[BotSummary](tag, "bot_summary") {
    def * : ProvenShape[BotSummary] =
      (platform, idOperator, idConnectorVersion, idWebsite) <> (BotSummary.tupled, BotSummary.unapply)
    def platform: Rep[String] = column[String]("platform")
    def idOperator: Rep[String] = column[String]("id_operator")
    def idConnectorVersion: Rep[Option[UUID]] = column[Option[UUID]]("id_connector_version")
    def idWebsite: Rep[String] = column[String]("id_website")
    def pk: PrimaryKey = primaryKey("pk_bot_summary", (platform, idOperator))
  }
```

```scala
  def save(
      botSummary: BotSummary
  )(implicit executionContext: ExecutionContext): DBIOAction[Done.type, NoStream, Effect.Write] = {
    botSummaries.insertOrUpdate(botSummary).map(_ => Done)
  }
```

Here is the error
```
[error] a.s.s.RestartWithBackoffSource - Restarting graph due to failure
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_bot_summary"
  Détail : Key (platform, id_operator)=(5cd57562-5bad-4b03-8047, 912470274d97) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2422)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2167)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
```

This trick is working for me : https://stackoverflow.com/a/42061140/4768481

**Comment by hvesalai** [comment]
@pocman can you make a new issue with a proper test case included so I can reproduce it. Or if you can, a PR for a test case (and even better if you can come up with a fix)
