### ISSUE TITLE
PSQLException querying with custom optional MappedColumnType

### ISSUE THREAD

**Issue by Pyppe** [slick/slick#998]
Given:

``` scala
import org.joda.time.DateTime
import java.sql.Timestamp

// Jodatime mapping
implicit val timestampJodaDateTime = MappedColumnType.base[DateTime, Timestamp] (
  dateTime => new Timestamp(dateTime.getMillis),
  timestamp => new DateTime(timestamp)
)

class FooTable(tag: Tag) extends Table[(String, DateTime)](tag, "foos") {
  def id = column[String]("id")
  def time = column[DateTime]("time")
  override def * = (id,time)
}
val foos = TableQuery[FooTable]

val query = Compiled { (number: Column[Option[DateTime]]) =>
  foos.filter(f => number.isEmpty || f.time >= number) // number.isEmpty causes error at runtime
}

withSession { implicit s => query(None).run }
```

Will throw exception at runtime:

```
2014-10-02 17:29:09.003 [run-main-1] DEBUG s.slick.jdbc.JdbcBackend.statement - Preparing statement: select x2."id", x2."time" from "foos" x2 where (? is null) or (x2."time" >= ?)
org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $1
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412)
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
    at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement$$anonfun$execute$5.apply$mcZ$sp(JdbcBackend.scala:329)
    at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement$$anonfun$execute$5.apply(JdbcBackend.scala:329)
    at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement$$anonfun$execute$5.apply(JdbcBackend.scala:329)
    at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingStatement.logged(JdbcBackend.scala:264)
    at scala.slick.jdbc.JdbcBackend$SessionDef$LoggingPreparedStatement.execute(JdbcBackend.scala:329)
    at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
    at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
    at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
    at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
    at scala.slick.driver.JdbcExecutorComponent$QueryExecutorDef.run(JdbcExecutorComponent.scala:29)
    at $anonfun$1.apply(<console>:23)
    at $anonfun$1.apply(<console>:23)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
...
```

IMO this should work with custom types as well, right?

**Comment by mgosk** [comment]
+1

**Comment by szeiger** [comment]
Looks like PostgreSQL needs to know the type of a value even for a null check. In this simple case it would be better to do the check on the client side anyway (so you don't have to run a query when `number.isEmpty`) but there may be more legitimate cases.

**Comment by kbanman** [comment]
I have encountered the same problem with slightly different parameters:

I am using a mapped type for a non-null string column, and get the same runtime exception. This is with the MySQL driver.

Looks to me like compiled queries simply do not work with type-mapped columns right now.

**Comment by virusdave** [comment]
I also ran into the same problem.

Very simplified query snippet:

```
  private[this] def query(
      maid: Rep[IdOf[MasterAccount]],
      uid: Rep[IdOf[User]],
      startTs: Rep[Option[When[Created]]],
      endTs: Rep[When[Created]],
      skip: ConstColumn[Long],
      take: ConstColumn[Long]) = {

    val events =
      Events
        .filter(_.masterAccountId === maid)
          // Slick bug requiring cast: https://github.com/slick/slick/issues/998
        .filter(_.createdTs >= startTs || (startTs.asColumnOf[Option[java.sql.Timestamp]]).isEmpty)
        .filter(_.createdTs <= endTs)
        .sortBy(_.createdTs.desc)
        .drop(skip)
        .take(take)
  // snip
```

Without the cast it attempts to produce a query that looks like this:

```
select x2.x3, x2.x4, x2.x5, x6."first_name", x6."last_name", x2.x7 from (select "master_account_id" as x8, "created_ts" as x4, "user_id" as x9, "summary" as x7, "event_id" as x3, "event" as x5 from "odo_events" 
where (("master_account_id" = 'XYZ') and (("created_ts" >= to_timestamp('2014-12-31 19:00:00.000', 'yyyy-MM-dd hh24:mi:ss.ff3')) or (to_timestamp('2014-12-31 19:00:00.000', 'yyyy-MM-dd hh24:mi:ss.ff3') is null))) and ("created_ts" <= to_timestamp('2016-03-28 20:00:00.000', 'yyyy-MM-dd hh24:mi:ss.ff3')) 
order by "created_ts" desc limit 20 offset 1) x2, "users" x6 where x2.x9 = x6."user_id";

throws exception: org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $3
org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter $3
```

In general these are query parameters that are known client-side, but it's not really reasonable for us to piece together many different query piece combinations based upon the presence or absence of various pieces of the filtering criteria.
